name: names
description: A starting point for Dart libraries or applications.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dart_helpers:
    path: ../dart_helpers

dev_dependencies:
  json_annotation: ^4.8.1
  lints: ^2.0.0
  test: ^1.21.0
