name: names
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
