name: thematic_names
description: >-
  The dependency-free package generates an infinite number of thematic calibrated unique names.
repository: https://github.com/signmotion/thematic_names.git
topics:
  - generator
  - names-generator
  - random
  - rpg
  - games

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.4.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  json_annotation: ^4.9.0
  lints: ^3.0.0
  strings: ^3.1.1
  test: ^1.25.4
