import '../name_r.dart';

const Set<NameR> en = {
  (title: 'Almond Amore', synopsis: ''),
  (title: 'Amaretto Alchemy', synopsis: ''),
  (title: 'Amaretto Alleys', synopsis: ''),
  (title: 'Amaretto Avenues', synopsis: ''),
  (title: 'Angel Cakery', synopsis: ''),
  (title: 'Angelic Apple Bakes', synopsis: ''),
  (title: 'Angelic Artisan Bakes', synopsis: ''),
  (title: 'Artful Appetizers', synopsis: ''),
  (title: 'Artful Artisan', synopsis: ''),
  (title: 'Artisan Bread Works', synopsis: ''),
  (title: 'Artisan Oven', synopsis: ''),
  (title: 'Artisanal Appetites', synopsis: ''),
  (title: 'Artisanal Bites', synopsis: ''),
  (title: 'Artisanal Breads', synopsis: ''),
  (title: 'Artisanal Cravings', synopsis: ''),
  (title: 'Artisanal Crusts and Castles', synopsis: ''),
  (title: 'Artisanal Decadence', synopsis: ''),
  (title: 'Artisanal Delights', synopsis: ''),
  (title: 'Artisanal Delish', synopsis: ''),
  (title: 'Artisanal Oven', synopsis: ''),
  (title: 'Artisanal Sweets', synopsis: ''),
  (title: 'Artisanal Treats', synopsis: ''),
  (title: 'Bagel Bar', synopsis: ''),
  (title: 'Bagel Barn', synopsis: ''),
  (title: 'Bagel Basket', synopsis: ''),
  (title: 'Bagel Boutique', synopsis: ''),
  (title: 'Baguette', synopsis: ''),
  (title: 'Baguette Basket', synopsis: ''),
  (title: 'Baguette Boutique', synopsis: ''),
  (title: 'Bake and Beyond', synopsis: ''),
  (title: 'Bake Bliss', synopsis: ''),
  (title: 'Bake Bonbons', synopsis: ''),
  (title: 'Bake Bonbons Bliss', synopsis: ''),
  (title: 'Bake Bonbonsville', synopsis: ''),
  (title: 'Bake Me Happy', synopsis: ''),
  (title: 'Bake My Day', synopsis: ''),
  (title: 'Bakeaway Bay', synopsis: ''),
  (title: 'Bakeaway Bay Bakes', synopsis: ''),
  (title: 'Baked and Beyond', synopsis: ''),
  (title: 'Baked Morning', synopsis: ''),
  (title: 'Bakehouse Bliss', synopsis: ''),
  (title: 'Bakehouse Bonanza', synopsis: ''),
  (title: 'Baker Blissful Bites', synopsis: ''),
  (title: 'Baker Delight', synopsis: ''),
  (title: 'Baking Bonanza', synopsis: ''),
  (title: 'Baking Brigade', synopsis: ''),
  (title: 'Baking Brilliance', synopsis: ''),
  (title: 'Baking Haven', synopsis: ''),
  (title: 'Banana Bread Boutique', synopsis: ''),
  (title: 'Batter Up', synopsis: ''),
  (title: 'Berry Bites', synopsis: ''),
  (title: 'Berry Bites Bakes', synopsis: ''),
  (title: 'Berry Blast', synopsis: ''),
  (title: 'Berry Bliss Bakes', synopsis: ''),
  (title: 'Berry Blossom', synopsis: ''),
  (title: 'Berry Bonanza', synopsis: ''),
  (title: 'Berry Boulevard', synopsis: ''),
  (title: 'Berry Bower', synopsis: ''),
  (title: 'Berrylicious Bakes', synopsis: ''),
  (title: 'Biscotti Bliss Boulevard', synopsis: ''),
  (title: 'Biscotti Blissful Bazaar', synopsis: ''),
  (title: 'Biscotti Boulevard', synopsis: ''),
  (title: 'Biscotti Boulevard Bliss', synopsis: ''),
  (title: 'Biscuit Barn', synopsis: ''),
  (title: 'Biscuit Bistro', synopsis: ''),
  (title: 'Biscuit Blessings', synopsis: ''),
  (title: 'Biscuit Bliss', synopsis: ''),
  (title: 'Biscuit Bonanza', synopsis: ''),
  (title: 'Biscuit Boulevard', synopsis: ''),
  (title: 'Biscuit Boutique', synopsis: ''),
  (title: 'Biscuit Brigade', synopsis: ''),
  (title: 'Biscuit Bungalow', synopsis: ''),
  (title: 'Bite Me', synopsis: ''),
  (title: 'Bliss', synopsis: ''),
  (title: 'Bliss Bake', synopsis: ''),
  (title: 'Bliss Berry', synopsis: ''),
  (title: 'Bliss Burst', synopsis: ''),
  (title: 'Blissful Bites', synopsis: ''),
  (title: 'Blissful Bloom', synopsis: ''),
  (title: 'Blissful Buns', synopsis: ''),
  (title: 'Blissful Charm', synopsis: ''),
  (title: 'Blissful Cove', synopsis: ''),
  (title: 'Blissful Delish', synopsis: ''),
  (title: 'Blissful Deluxe', synopsis: ''),
  (title: 'Blissful Euphoria', synopsis: ''),
  (title: 'Blissful Marvel', synopsis: ''),
  (title: 'Blissful Nibble', synopsis: ''),
  (title: 'Blissful Nook', synopsis: ''),
  (title: 'Blissful Sprout', synopsis: ''),
  (title: 'Blissful Swirl', synopsis: ''),
  (title: 'Blissful Twist', synopsis: ''),
  (title: 'Bread and Beyond', synopsis: ''),
  (title: 'Bread and Butter', synopsis: ''),
  (title: 'Bread Basket', synopsis: ''),
  (title: 'Bread Box', synopsis: ''),
  (title: 'Bread Haven', synopsis: ''),
  (title: 'Bread Slice', synopsis: ''),
  (title: 'Brioche Basket', synopsis: ''),
  (title: 'Brioche Bliss', synopsis: ''),
  (title: 'Brioche Bliss Bake', synopsis: ''),
  (title: 'Brioche Boulevard', synopsis: ''),
  (title: 'Brioche Boutique', synopsis: ''),
  (title: 'Brioche Box', synopsis: ''),
  (title: 'Brownie Box', synopsis: ''),
  (title: 'Butter Beat', synopsis: ''),
  (title: 'Butter Bliss', synopsis: ''),
  (title: 'Butter Bliss Bake', synopsis: ''),
  (title: 'Butter Bloom', synopsis: ''),
  (title: 'Butter Boudoir', synopsis: ''),
  (title: 'Butterberry', synopsis: ''),
  (title: 'Buttercream Bliss', synopsis: ''),
  (title: 'Buttercream Delights', synopsis: ''),
  (title: 'Buttercup', synopsis: ''),
  (title: 'Buttercup Bistro', synopsis: ''),
  (title: 'Buttercup Boulevard', synopsis: ''),
  (title: 'Buttered Bliss', synopsis: ''),
  (title: 'Butterfield', synopsis: ''),
  (title: 'Buttermilk Bakehouse', synopsis: ''),
  (title: 'Buttermilk Bakes', synopsis: ''),
  (title: 'Buttermilk Beauties', synopsis: ''),
  (title: 'Buttermilk Bistro', synopsis: ''),
  (title: 'Buttermilk Bliss', synopsis: ''),
  (title: 'Buttermilk Blossoms', synopsis: ''),
  (title: 'Buttermilk Boutique', synopsis: ''),
  (title: 'Buttermilk Delights', synopsis: ''),
  (title: 'Buttermilk Heaven', synopsis: ''),
  (title: 'Butterscotch Blessings', synopsis: ''),
  (title: 'Butterscotch Bliss', synopsis: ''),
  (title: 'Butterscotch Bonanza', synopsis: ''),
  (title: 'Butterscotch Boutique', synopsis: ''),
  (title: 'Butterscotch Brigade', synopsis: ''),
  (title: 'Butterville', synopsis: ''),
  (title: 'Cake', synopsis: ''),
  (title: 'Cake Avenue', synopsis: ''),
  (title: 'Cake Boutique', synopsis: ''),
  (title: 'Cake Box', synopsis: ''),
  (title: 'Cake Canvas', synopsis: ''),
  (title: 'Cake Canvas Creations', synopsis: ''),
  (title: 'Cake Central', synopsis: ''),
  (title: 'Cake Connoisseurs', synopsis: ''),
  (title: 'Cake Conquests', synopsis: ''),
  (title: 'Cake Corner', synopsis: ''),
  (title: 'Cake Cottage', synopsis: ''),
  (title: 'Cake Counter', synopsis: ''),
  (title: 'Cake Couture', synopsis: ''),
  (title: 'Cake Couture Corner', synopsis: ''),
  (title: 'Cake Couturiers', synopsis: ''),
  (title: 'Cake Craze', synopsis: ''),
  (title: 'Cake Creationists', synopsis: ''),
  (title: 'Cake Creations Central', synopsis: ''),
  (title: 'Cake Creations Gallery', synopsis: ''),
  (title: 'Cake Crusaders', synopsis: ''),
  (title: 'Cake Haven', synopsis: ''),
  (title: 'Cake Magic', synopsis: ''),
  (title: 'Cake Walk', synopsis: ''),
  (title: 'Cake Walk Confections', synopsis: ''),
  (title: 'Cakery', synopsis: ''),
  (title: 'Cakery Confessions', synopsis: ''),
  (title: 'Cakery Corner', synopsis: ''),
  (title: 'Cakery Couture', synopsis: ''),
  (title: 'Cakes and Confections', synopsis: ''),
  (title: 'Cakes and Cravings', synopsis: ''),
  (title: 'Cakes and Crumbs', synopsis: ''),
  (title: 'Cakes and Crumbs Corner', synopsis: ''),
  (title: 'Cakes and Crust', synopsis: ''),
  (title: 'Cakes and Cupids', synopsis: ''),
  (title: 'Cakes by Design', synopsis: ''),
  (title: 'Cakes Galore', synopsis: ''),
  (title: 'Cakescape Creations', synopsis: ''),
  (title: 'Candy Bloom', synopsis: ''),
  (title: 'Candy Coast', synopsis: ''),
  (title: 'Candy Crafter', synopsis: ''),
  (title: 'Candy Delight', synopsis: ''),
  (title: 'Candy Deluxe', synopsis: ''),
  (title: 'Candy Fable', synopsis: ''),
  (title: 'Candy Flick', synopsis: ''),
  (title: 'Candy Frost', synopsis: ''),
  (title: 'Candy Glam', synopsis: ''),
  (title: 'Candy Glaze', synopsis: ''),
  (title: 'Candy Glitz', synopsis: ''),
  (title: 'Candy Glow', synopsis: ''),
  (title: 'Candy Grove', synopsis: ''),
  (title: 'Candy Gusto', synopsis: ''),
  (title: 'Candy Hills', synopsis: ''),
  (title: 'Candy Sprinkle', synopsis: ''),
  (title: 'Candy Sprout', synopsis: ''),
  (title: 'Candy Treat', synopsis: ''),
  (title: 'Candy Twist', synopsis: ''),
  (title: 'Candylandia', synopsis: ''),
  (title: 'Caramel Burst', synopsis: ''),
  (title: 'Caramel Carnival', synopsis: ''),
  (title: 'Caramel Carousel', synopsis: ''),
  (title: 'Caramel Carousel Cavalcade', synopsis: ''),
  (title: 'Caramel Carousel Cove', synopsis: ''),
  (title: 'Caramel Castle', synopsis: ''),
  (title: 'Caramel Cavern', synopsis: ''),
  (title: 'Caramel Charm', synopsis: ''),
  (title: 'Caramel Chateau', synopsis: ''),
  (title: 'Caramel Cloud Carousel', synopsis: ''),
  (title: 'Caramel Clouds', synopsis: ''),
  (title: 'Caramel Cove', synopsis: ''),
  (title: 'Caramel Cream', synopsis: ''),
  (title: 'Caramel Crescendo', synopsis: ''),
  (title: 'Caramel Crisp', synopsis: ''),
  (title: 'Caramel Crossroads', synopsis: ''),
  (title: 'Caramel Deluxe', synopsis: ''),
  (title: 'Caramel Dip', synopsis: ''),
  (title: 'Caramel Divine', synopsis: ''),
  (title: 'Caramel Dust', synopsis: ''),
  (title: 'Caramel Frost', synopsis: ''),
  (title: 'Caramel Glaze', synopsis: ''),
  (title: 'Caramel Haven', synopsis: ''),
  (title: 'Caramel Lush', synopsis: ''),
  (title: 'Caramel Paradise', synopsis: ''),
  (title: 'Caramel Swirl', synopsis: ''),
  (title: 'Caramel Swirls', synopsis: ''),
  (title: 'Caramel Treat', synopsis: ''),
  (title: 'Caramel Zing', synopsis: ''),
  (title: 'Caramel Zoom', synopsis: ''),
  (title: 'Cherry Cheeks', synopsis: ''),
  (title: 'Choco Charisma Bakes', synopsis: ''),
  (title: 'Choco Charm', synopsis: ''),
  (title: 'Choco Charm Bakes', synopsis: ''),
  (title: 'Choco Chateau', synopsis: ''),
  (title: 'Choco Delight', synopsis: ''),
  (title: 'Choco Delight Bakes', synopsis: ''),
  (title: 'Choco Delish', synopsis: ''),
  (title: 'Choco Haven Bakes', synopsis: ''),
  (title: 'Chocolate Castle', synopsis: ''),
  (title: 'Chocolate Chateau', synopsis: ''),
  (title: 'Chocolate Conclave', synopsis: ''),
  (title: 'Choux Chic', synopsis: ''),
  (title: 'Cinnamon Dreams', synopsis: ''),
  (title: 'Cinnamon Sugar Dreams', synopsis: ''),
  (title: 'Cinnamon Sugar Swirls', synopsis: ''),
  (title: 'Cinnamon Swirls', synopsis: ''),
  (title: 'Cinnamon Swirls Sensations', synopsis: ''),
  (title: 'Cinnamon Symphony', synopsis: ''),
  (title: 'Citrus Sensations', synopsis: ''),
  (title: 'Cocoa Cabana', synopsis: ''),
  (title: 'Cocoa Cakewalk', synopsis: ''),
  (title: 'Cocoa Canyon', synopsis: ''),
  (title: 'Cocoa Clouds', synopsis: ''),
  (title: 'Confection Confessions', synopsis: ''),
  (title: 'Confection Perfection', synopsis: ''),
  (title: 'Confectionery', synopsis: ''),
  (title: 'Confectionery Castle', synopsis: ''),
  (title: 'Confectionery Charms', synopsis: ''),
  (title: 'Confectionery Confidants', synopsis: ''),
  (title: 'Confectionery Corner', synopsis: ''),
  (title: 'Confectionery Creations', synopsis: ''),
  (title: 'Cookie', synopsis: ''),
  (title: 'Cookie Cabana', synopsis: ''),
  (title: 'Cookie Cabin', synopsis: ''),
  (title: 'Cookie Caboose', synopsis: ''),
  (title: 'Cookie Caper', synopsis: ''),
  (title: 'Cookie Carousel', synopsis: ''),
  (title: 'Cookie Carousel Cruise', synopsis: ''),
  (title: 'Cookie Castle', synopsis: ''),
  (title: 'Cookie Chaos', synopsis: ''),
  (title: 'Cookie Charm', synopsis: ''),
  (title: 'Cookie Coda', synopsis: ''),
  (title: 'Cookie Concoctions', synopsis: ''),
  (title: 'Cookie Confections', synopsis: ''),
  (title: 'Cookie Constellation', synopsis: ''),
  (title: 'Cookie Coop', synopsis: ''),
  (title: 'Cookie Corner', synopsis: ''),
  (title: 'Cookie Cornerstone', synopsis: ''),
  (title: 'Cookie Cottage', synopsis: ''),
  (title: 'Cookie Couture', synopsis: ''),
  (title: 'Cookie Cove', synopsis: ''),
  (title: 'Cookie Cove Creations', synopsis: ''),
  (title: 'Cookie Cozy', synopsis: ''),
  (title: 'Cookie Cozy Corner', synopsis: ''),
  (title: 'Cookie Craving', synopsis: ''),
  (title: 'Cookie Cravings', synopsis: ''),
  (title: 'Cookie Craze', synopsis: ''),
  (title: 'Cookie Creations', synopsis: ''),
  (title: 'Cookie Creations Confectioners', synopsis: ''),
  (title: 'Cookie Crumble', synopsis: ''),
  (title: 'Cookie Crumbs', synopsis: ''),
  (title: 'Cookie Crush', synopsis: ''),
  (title: 'Cookie Emporium', synopsis: ''),
  (title: 'Cookie Glee', synopsis: ''),
  (title: 'Cookie Glow', synopsis: ''),
  (title: 'Cookie Harmony', synopsis: ''),
  (title: 'Cookie Harvest', synopsis: ''),
  (title: 'Cookie Hug', synopsis: ''),
  (title: 'Cookie Jar', synopsis: ''),
  (title: 'Cookie Joy', synopsis: ''),
  (title: 'Cookie Jubilee', synopsis: ''),
  (title: 'Cookie Kingdom', synopsis: ''),
  (title: 'Cookie Lush', synopsis: ''),
  (title: 'Cookie Luxe', synopsis: ''),
  (title: 'Cookie Marvel', synopsis: ''),
  (title: 'Cookie Meadow', synopsis: ''),
  (title: 'Cookie Nest', synopsis: ''),
  (title: 'Cookie Paradise', synopsis: ''),
  (title: 'Cookie Pleasure', synopsis: ''),
  (title: 'Cookie Rhapsody', synopsis: ''),
  (title: 'Craveolicious Bakes', synopsis: ''),
  (title: 'Craveworthy Confections', synopsis: ''),
  (title: 'Cream and Sugar', synopsis: ''),
  (title: 'Creamy Concoctions', synopsis: ''),
  (title: 'Creamy Couture', synopsis: ''),
  (title: 'Creamy Creations', synopsis: ''),
  (title: 'Creamy Delights', synopsis: ''),
  (title: 'Creamy Dream', synopsis: ''),
  (title: 'Crispy Confections', synopsis: ''),
  (title: 'Crispy Cravings', synopsis: ''),
  (title: 'Crispy Crust', synopsis: ''),
  (title: 'Crispy Crusts', synopsis: ''),
  (title: 'Croissant', synopsis: ''),
  (title: 'Croissant Cabins', synopsis: ''),
  (title: 'Croissant Classics', synopsis: ''),
  (title: 'Croissant Corner', synopsis: ''),
  (title: 'Croissant Courtyard', synopsis: ''),
  (title: 'Croissant Cove', synopsis: ''),
  (title: 'Crumb', synopsis: ''),
  (title: 'Crumb and Cozy', synopsis: ''),
  (title: 'Crumble', synopsis: ''),
  (title: 'Crumble Corner', synopsis: ''),
  (title: 'Crumble Cottage', synopsis: ''),
  (title: 'Crumble Craze', synopsis: ''),
  (title: 'Crumbly Confections', synopsis: ''),
  (title: 'Crumbly Creations', synopsis: ''),
  (title: 'Crumbs', synopsis: ''),
  (title: 'Crumbs and Crust', synopsis: ''),
  (title: 'Crunchy Creamery', synopsis: ''),
  (title: 'Crust', synopsis: ''),
  (title: 'Crust and Confections', synopsis: ''),
  (title: 'Crust and Creams', synopsis: ''),
  (title: 'Crust and Crumb', synopsis: ''),
  (title: 'Crust and Crumbs', synopsis: ''),
  (title: 'Crust Nook', synopsis: ''),
  (title: 'Crustal Clear', synopsis: ''),
  (title: 'Crustal Creations', synopsis: ''),
  (title: 'Crusty Cakes', synopsis: ''),
  (title: 'Crusty Comfort', synopsis: ''),
  (title: 'Crusty Comforts', synopsis: ''),
  (title: 'Crusty Confections', synopsis: ''),
  (title: 'Crusty Corner', synopsis: ''),
  (title: 'Crusty Cove', synopsis: ''),
  (title: 'Crusty Cravings', synopsis: ''),
  (title: 'Crusty Creations', synopsis: ''),
  (title: 'Crusty Crumbs', synopsis: ''),
  (title: 'Crusty Loaf', synopsis: ''),
  (title: 'Cupcake Cabana', synopsis: ''),
  (title: 'Cupcake Cabaret', synopsis: ''),
  (title: 'Cupcake Carnival', synopsis: ''),
  (title: 'Cupcake Carousel', synopsis: ''),
  (title: 'Cupcake Castle', synopsis: ''),
  (title: 'Cupcake Cavern', synopsis: ''),
  (title: 'Cupcake Chateau', synopsis: ''),
  (title: 'Cupcake Circus', synopsis: ''),
  (title: 'Cupcake Coop', synopsis: ''),
  (title: 'Cupcake Corner', synopsis: ''),
  (title: 'Cupcake Cottage', synopsis: ''),
  (title: 'Cupcake Cozy', synopsis: ''),
  (title: 'Cupcake Craze', synopsis: ''),
  (title: 'Cupcake Crown', synopsis: ''),
  (title: 'Cupcake Emporium', synopsis: ''),
  (title: 'Cupcake Factory', synopsis: ''),
  (title: 'Cupcake Haven', synopsis: ''),
  (title: 'Cupcake Lane', synopsis: ''),
  (title: 'Cupcakery', synopsis: ''),
  (title: 'Custard Carousel', synopsis: ''),
  (title: 'Danish Delight', synopsis: ''),
  (title: 'Decadence Deli', synopsis: ''),
  (title: 'Decadence Diner', synopsis: ''),
  (title: 'Decadent Delights', synopsis: ''),
  (title: 'Decadent Delights Deli', synopsis: ''),
  (title: 'Decadent Dreams', synopsis: ''),
  (title: 'Delicate Crust', synopsis: ''),
  (title: 'Delicate Dainties', synopsis: ''),
  (title: 'Delicate Decadence', synopsis: ''),
  (title: 'Delicate Delights', synopsis: ''),
  (title: 'Delicate Desserts', synopsis: ''),
  (title: 'Delicate Desserts Delights', synopsis: ''),
  (title: 'Delicate Dough Delights', synopsis: ''),
  (title: 'Delightful Desserts', synopsis: ''),
  (title: 'Delightful Desserts Diner', synopsis: ''),
  (title: 'Delightful Dough', synopsis: ''),
  (title: 'Delightful Dough Delights', synopsis: ''),
  (title: 'Delightful Drops', synopsis: ''),
  (title: 'Dessert Dazzle', synopsis: ''),
  (title: 'Dessert Delights', synopsis: ''),
  (title: 'Dessert Delights Diner', synopsis: ''),
  (title: 'Dessert Delirium', synopsis: ''),
  (title: 'Dessert Desire', synopsis: ''),
  (title: 'Dessert Divinity', synopsis: ''),
  (title: 'Dessert Dreamland', synopsis: ''),
  (title: 'Dessert Dreams Bake', synopsis: ''),
  (title: 'Dessert Oasis', synopsis: ''),
  (title: 'Divine Desserts', synopsis: ''),
  (title: 'Donut Delight', synopsis: ''),
  (title: 'Donut Hole', synopsis: ''),
  (title: 'Dough Darling', synopsis: ''),
  (title: 'Dough Delight', synopsis: ''),
  (title: 'Dough Delights', synopsis: ''),
  (title: 'Dough Delirium', synopsis: ''),
  (title: 'Dough Depot', synopsis: ''),
  (title: 'Doughlicious', synopsis: ''),
  (title: 'Doughlicious Delights', synopsis: ''),
  (title: 'Doughnut Daze', synopsis: ''),
  (title: 'Doughnut Delicacies', synopsis: ''),
  (title: 'Doughnut Delight', synopsis: ''),
  (title: 'Doughnut Delights', synopsis: ''),
  (title: 'Doughnut Den', synopsis: ''),
  (title: 'Doughnut Diva', synopsis: ''),
  (title: 'Doughnut Divinity', synopsis: ''),
  (title: 'Doughnut Dream', synopsis: ''),
  (title: 'Doughnut Dreams', synopsis: ''),
  (title: 'Doughnut Dynasty', synopsis: ''),
  (title: 'Doughnut Hole', synopsis: ''),
  (title: 'Doughnuts of Delight', synopsis: ''),
  (title: 'Doughy Delights', synopsis: ''),
  (title: 'Dreamland Delicacies', synopsis: ''),
  (title: 'Dreamland Delights', synopsis: ''),
  (title: 'Dreamland Desserts', synopsis: ''),
  (title: 'Dreamy Bake', synopsis: ''),
  (title: 'Dreamy Bakes', synopsis: ''),
  (title: 'Dreamy Bites', synopsis: ''),
  (title: 'Dreamy Charm', synopsis: ''),
  (title: 'Dreamy Confections', synopsis: ''),
  (title: 'Dreamy Crisp', synopsis: ''),
  (title: 'Dreamy Crust', synopsis: ''),
  (title: 'Dreamy Cup', synopsis: ''),
  (title: 'Dreamy Cupcake', synopsis: ''),
  (title: 'Dreamy Delicacies', synopsis: ''),
  (title: 'Dreamy Delight', synopsis: ''),
  (title: 'Dreamy Delights', synopsis: ''),
  (title: 'Dreamy Deluxe', synopsis: ''),
  (title: 'Dreamy Dessert', synopsis: ''),
  (title: 'Dreamy Desserts', synopsis: ''),
  (title: 'Dreamy Desserts Diner', synopsis: ''),
  (title: 'Dreamy Dip', synopsis: ''),
  (title: 'Dreamy Dough', synopsis: ''),
  (title: 'Dreamy Doughnuts', synopsis: ''),
  (title: 'Dreamy Eclairs', synopsis: ''),
  (title: 'Dreamy Flair', synopsis: ''),
  (title: 'Dreamy Glimmer', synopsis: ''),
  (title: 'Dreamy Glow', synopsis: ''),
  (title: 'Dreamy Gourmet', synopsis: ''),
  (title: 'Dreamy Harvest', synopsis: ''),
  (title: 'Dreamy Joy', synopsis: ''),
  (title: 'Dreamy Treats', synopsis: ''),
  (title: 'Eat and Go', synopsis: ''),
  (title: 'Eclair Ecstasy', synopsis: ''),
  (title: 'Eclair Elegance', synopsis: ''),
  (title: 'Eclair Embrace', synopsis: ''),
  (title: 'Eclair Enchantment', synopsis: ''),
  (title: 'Eclair Euphoria', synopsis: ''),
  (title: 'Eclair Exquisites', synopsis: ''),
  (title: 'Enchanted Eats', synopsis: ''),
  (title: 'Enchanted Embers', synopsis: ''),
  (title: 'Enchanted Emporium', synopsis: ''),
  (title: 'Enchanted Epicure', synopsis: ''),
  (title: 'Enchanted Oven', synopsis: ''),
  (title: 'Enchanting Eclairs', synopsis: ''),
  (title: 'Enchanting Elixirs', synopsis: ''),
  (title: 'Enchanting Euphoria', synopsis: ''),
  (title: 'Ever After Bakes', synopsis: ''),
  (title: 'Ever After Delights', synopsis: ''),
  (title: 'Ever After Eclairs', synopsis: ''),
  (title: 'Ever After Treats', synopsis: ''),
  (title: 'Everlasting Delights', synopsis: ''),
  (title: 'Everlasting Eats', synopsis: ''),
  (title: 'Everlasting Eclairs', synopsis: ''),
  (title: 'Everlasting Edibles', synopsis: ''),
  (title: 'Fable Fancies', synopsis: ''),
  (title: 'Fabled Fancies', synopsis: ''),
  (title: 'Fabled Flavors', synopsis: ''),
  (title: 'Fabled Frostings', synopsis: ''),
  (title: 'Fableland Fancies', synopsis: ''),
  (title: 'Fairyland Fusions', synopsis: ''),
  (title: 'Fairytale Flavors', synopsis: ''),
  (title: 'Fairytale Fusions', synopsis: ''),
  (title: 'Fanciful Flavors', synopsis: ''),
  (title: 'Fanciful Frosting', synopsis: ''),
  (title: 'Fanciful Frostings', synopsis: ''),
  (title: 'Fanciful Fusions', synopsis: ''),
  (title: 'Fancy French Pastries', synopsis: ''),
  (title: 'Fantasia Frosting', synopsis: ''),
  (title: 'Fantasy Flavors', synopsis: ''),
  (title: 'Fantasy Frosting', synopsis: ''),
  (title: 'Flaky Bakes', synopsis: ''),
  (title: 'Flaky Delights', synopsis: ''),
  (title: 'Flaky Fancies', synopsis: ''),
  (title: 'Flaky Fantasia', synopsis: ''),
  (title: 'Flaky Fantasies', synopsis: ''),
  (title: 'Flaky Feasts', synopsis: ''),
  (title: 'Flaky Finesse', synopsis: ''),
  (title: 'Flaky Pastries', synopsis: ''),
  (title: 'Flour Fantasy', synopsis: ''),
  (title: 'Flour Finesse', synopsis: ''),
  (title: 'Flour Fusion', synopsis: ''),
  (title: 'Flour Power', synopsis: ''),
  (title: 'Flour Power Delights', synopsis: ''),
  (title: 'Flourish', synopsis: ''),
  (title: 'Flourish and Frost', synopsis: ''),
  (title: 'Flourish and Frost Delights', synopsis: ''),
  (title: 'Flourish and Frost Diner', synopsis: ''),
  (title: 'Flourish and Frost Junction', synopsis: ''),
  (title: 'Flourish and Frosting', synopsis: ''),
  (title: 'Fondant Fairytale', synopsis: ''),
  (title: 'Fondant Fancies', synopsis: ''),
  (title: 'Fondant Fantasia', synopsis: ''),
  (title: 'Fondant Fantasy', synopsis: ''),
  (title: 'French Oven', synopsis: ''),
  (title: 'Fresh Baked', synopsis: ''),
  (title: 'Freshly Baked', synopsis: ''),
  (title: 'Freshly Baked Bliss', synopsis: ''),
  (title: 'Frosted Charm', synopsis: ''),
  (title: 'Frosted Delight', synopsis: ''),
  (title: 'Frosted Fable', synopsis: ''),
  (title: 'Frosted Fantasy', synopsis: ''),
  (title: 'Frosted Flick', synopsis: ''),
  (title: 'Frosted Glaze', synopsis: ''),
  (title: 'Frosted Gleam', synopsis: ''),
  (title: 'Frosted Glitz', synopsis: ''),
  (title: 'Frosted Glow', synopsis: ''),
  (title: 'Frosted Marvel', synopsis: ''),
  (title: 'Frosted Meadow', synopsis: ''),
  (title: 'Frosted Nook', synopsis: ''),
  (title: 'Frosted Savory', synopsis: ''),
  (title: 'Frosted Swirl', synopsis: ''),
  (title: 'Frosted Whiff', synopsis: ''),
  (title: 'Frosted Whirl', synopsis: ''),
  (title: 'Frosted Whisk', synopsis: ''),
  (title: 'Frosted Wink', synopsis: ''),
  (title: 'Frosting Fairy', synopsis: ''),
  (title: 'Fruity Fiesta', synopsis: ''),
  (title: 'Fudge Fantasy', synopsis: ''),
  (title: 'Gingerbread House', synopsis: ''),
  (title: 'Gingerbread Joy', synopsis: ''),
  (title: 'Glazed Delicacies', synopsis: ''),
  (title: 'Glazed Goodness', synopsis: ''),
  (title: 'Gourmet', synopsis: ''),
  (title: 'Gourmet Gateau Galore', synopsis: ''),
  (title: 'Gourmet Gateau Garden', synopsis: ''),
  (title: 'Gourmet Gateaux', synopsis: ''),
  (title: 'Gourmet Goodies', synopsis: ''),
  (title: 'Gourmet Goodies Galore', synopsis: ''),
  (title: 'Heavenly Bites', synopsis: ''),
  (title: 'Heavenly Breadsticks', synopsis: ''),
  (title: 'Heavenly Confections', synopsis: ''),
  (title: 'Heavenly Creations', synopsis: ''),
  (title: 'Heavenly Crumbs', synopsis: ''),
  (title: 'Heavenly Delicacies', synopsis: ''),
  (title: 'Heavenly Delights', synopsis: ''),
  (title: 'Heavenly Havens', synopsis: ''),
  (title: 'Heavenly Pieholes', synopsis: ''),
  (title: 'Heavenly Pies', synopsis: ''),
  (title: 'Heavenly Scones', synopsis: ''),
  (title: 'Heavenly Slices', synopsis: ''),
  (title: 'Heavenly Sweets Haven', synopsis: ''),
  (title: 'Heavenly Treats', synopsis: ''),
  (title: 'Honey Bake', synopsis: ''),
  (title: 'Honey Bloom', synopsis: ''),
  (title: 'Honey Burst', synopsis: ''),
  (title: 'Honey Crest', synopsis: ''),
  (title: 'Honey Dazzle', synopsis: ''),
  (title: 'Honey Dew', synopsis: ''),
  (title: 'Honey Glaze', synopsis: ''),
  (title: 'Honey Glitz', synopsis: ''),
  (title: 'Honey Grove', synopsis: ''),
  (title: 'Honey Hug', synopsis: ''),
  (title: 'Honey Meadow', synopsis: ''),
  (title: 'Honey Nibble', synopsis: ''),
  (title: 'Honey Rhapsody', synopsis: ''),
  (title: 'Honey Savor', synopsis: ''),
  (title: 'Honey Sparkle', synopsis: ''),
  (title: 'Honey Sprout', synopsis: ''),
  (title: 'Honey Twinkle', synopsis: ''),
  (title: 'Honey Twirl', synopsis: ''),
  (title: 'Honey Whirl', synopsis: ''),
  (title: 'Honey Zest', synopsis: ''),
  (title: 'Icing Illusions', synopsis: ''),
  (title: 'Jelly Roll Junction', synopsis: ''),
  (title: 'Lemon Lagoon', synopsis: ''),
  (title: 'Lemon Lane', synopsis: ''),
  (title: 'Lemon Lane Bakes', synopsis: ''),
  (title: 'Lemon Love', synopsis: ''),
  (title: 'Lemon Love Bakes', synopsis: ''),
  (title: 'Lemon Lullaby', synopsis: ''),
  (title: 'Lemon Luscious', synopsis: ''),
  (title: 'Lemon Zest Lane', synopsis: ''),
  (title: 'Lemonade Lane', synopsis: ''),
  (title: 'Lemonade Lounge', synopsis: ''),
  (title: 'Lemonade Luxuries', synopsis: ''),
  (title: 'Macaron Melody', synopsis: ''),
  (title: 'Magical Macarons', synopsis: ''),
  (title: 'Magical Macaroons', synopsis: ''),
  (title: 'Magical Muffinry', synopsis: ''),
  (title: 'Magical Muffins', synopsis: ''),
  (title: 'Marshmallow Maison', synopsis: ''),
  (title: 'Marshmallow Manor', synopsis: ''),
  (title: 'Marshmallow Meadows', synopsis: ''),
  (title: 'Marshmallow Mingle', synopsis: ''),
  (title: 'Marshmallow Mirage', synopsis: ''),
  (title: 'Marshmallow Muse', synopsis: ''),
  (title: 'Meltin Your Mouth', synopsis: ''),
  (title: 'Meringue Marvels', synopsis: ''),
  (title: 'Meringue Mirage', synopsis: ''),
  (title: 'Meringue Mirage Bake', synopsis: ''),
  (title: 'Meringue Moments Bake', synopsis: ''),
  (title: 'Molten Marvels', synopsis: ''),
  (title: 'Muffin', synopsis: ''),
  (title: 'Muffin Madness', synopsis: ''),
  (title: 'Muffin Magic', synopsis: ''),
  (title: 'Muffin Magic Maison', synopsis: ''),
  (title: 'Muffin Magic Meadow', synopsis: ''),
  (title: 'Muffin Man', synopsis: ''),
  (title: 'Muffin Mania', synopsis: ''),
  (title: 'Muffin Manor', synopsis: ''),
  (title: 'Muffin Meadows', synopsis: ''),
  (title: 'Muffin Medley', synopsis: ''),
  (title: 'Muffin Medleys', synopsis: ''),
  (title: 'Muffin MElange', synopsis: ''),
  (title: 'Muffin Merriment', synopsis: ''),
  (title: 'Muffin Merrymakers', synopsis: ''),
  (title: 'Muffin Mingle', synopsis: ''),
  (title: 'Muffin Muse', synopsis: ''),
  (title: 'Muffin Top', synopsis: ''),
  (title: 'Mystical Macaroons', synopsis: ''),
  (title: 'Mystical Muffins', synopsis: ''),
  (title: 'Mythic Medleys', synopsis: ''),
  (title: 'Mythic Morsels', synopsis: ''),
  (title: 'Mythic Muffinry', synopsis: ''),
  (title: 'Mythic Muffins', synopsis: ''),
  (title: 'Mythical Macaroons', synopsis: ''),
  (title: 'Mythical Medley', synopsis: ''),
  (title: 'Mythical Morsels', synopsis: ''),
  (title: 'Mythical Muffins', synopsis: ''),
  (title: 'Mythical Munchies', synopsis: ''),
  (title: 'Mythical Munchkins', synopsis: ''),
  (title: 'Nutella Nirvana', synopsis: ''),
  (title: 'Nutella Nook', synopsis: ''),
  (title: 'Nutty Nirvana', synopsis: ''),
  (title: 'Nutty Nook', synopsis: ''),
  (title: 'Once Upon a Bake', synopsis: ''),
  (title: 'Once Upon a Caramel', synopsis: ''),
  (title: 'Once Upon a Confection', synopsis: ''),
  (title: 'Once Upon a Crisp', synopsis: ''),
  (title: 'Once Upon a Crumb', synopsis: ''),
  (title: 'Once Upon a Crust', synopsis: ''),
  (title: 'Oven Fresh', synopsis: ''),
  (title: 'Oven Fresh Delights', synopsis: ''),
  (title: 'Oven Overture', synopsis: ''),
  (title: 'Pastry Palace', synopsis: ''),
  (title: 'Pastry Palette', synopsis: ''),
  (title: 'Pastry Pantry', synopsis: ''),
  (title: 'Pastry Parade', synopsis: ''),
  (title: 'Pastry Paradise', synopsis: ''),
  (title: 'Pastry Parlor', synopsis: ''),
  (title: 'Pastry Patisserie', synopsis: ''),
  (title: 'Pastry Pavilion', synopsis: ''),
  (title: 'Pastry Pavilion Diner', synopsis: ''),
  (title: 'Pastry Pavillion', synopsis: ''),
  (title: 'Pastry Pedestal', synopsis: ''),
  (title: 'Pastry Perfection', synopsis: ''),
  (title: 'Pastry Piazza', synopsis: ''),
  (title: 'Pastry Pillar', synopsis: ''),
  (title: 'Pastry Plaza', synopsis: ''),
  (title: 'Pastry Pleasantries', synopsis: ''),
  (title: 'Pastry Pleasures', synopsis: ''),
  (title: 'Pastry Post', synopsis: ''),
  (title: 'Patisserie', synopsis: ''),
  (title: 'Patisserie Bliss', synopsis: ''),
  (title: 'Patisserie Palazzo', synopsis: ''),
  (title: 'Patisserie Paradiso', synopsis: ''),
  (title: 'Patisserie Paragon', synopsis: ''),
  (title: 'Patisserie Parlor', synopsis: ''),
  (title: 'Patisserie Perfection', synopsis: ''),
  (title: 'Patisserie Playground', synopsis: ''),
  (title: 'Patisserie Pleasures', synopsis: ''),
  (title: 'Patisserie Potpourri', synopsis: ''),
  (title: 'Patty Cakes', synopsis: ''),
  (title: 'Petite Patisserie', synopsis: ''),
  (title: 'Petite Pleasures Patisserie', synopsis: ''),
  (title: 'Pie in Sky', synopsis: ''),
  (title: 'Pie Pantry', synopsis: ''),
  (title: 'Pie Paradise', synopsis: ''),
  (title: 'Pie Parlor', synopsis: ''),
  (title: 'Pie Patch', synopsis: ''),
  (title: 'Pie Patisserie', synopsis: ''),
  (title: 'Pie Perfection', synopsis: ''),
  (title: 'Pie Place', synopsis: ''),
  (title: 'Pieful Pursuits', synopsis: ''),
  (title: 'Pies in Sky', synopsis: ''),
  (title: 'Popcorn Palace', synopsis: ''),
  (title: 'Popcorn Patisserie', synopsis: ''),
  (title: 'Popcorn Patisserie Palace', synopsis: ''),
  (title: 'Popcorn Pleasures', synopsis: ''),
  (title: 'Poppy Seed Palace', synopsis: ''),
  (title: 'Poppy Seed Parade', synopsis: ''),
  (title: 'Poppy Seed Paradise', synopsis: ''),
  (title: 'Puff Passion', synopsis: ''),
  (title: 'Puff Pastry', synopsis: ''),
  (title: 'Puff Pastry Palace', synopsis: ''),
  (title: 'Puff Pastry Panache', synopsis: ''),
  (title: 'Puff Pastry Pantry', synopsis: ''),
  (title: 'Puff Pastry Paradise', synopsis: ''),
  (title: 'Puff Pastry Parlor', synopsis: ''),
  (title: 'Puff Pastry Perfection', synopsis: ''),
  (title: 'Raisin Rhapsody', synopsis: ''),
  (title: 'Raisin Royale', synopsis: ''),
  (title: 'Raspberry Revelry', synopsis: ''),
  (title: 'Raspberry Rhapsody', synopsis: ''),
  (title: 'Red Velvet Rendezvous', synopsis: ''),
  (title: 'Rise and Bake', synopsis: ''),
  (title: 'Rise and Shine', synopsis: ''),
  (title: 'Rolling Dough', synopsis: ''),
  (title: 'Rolling Pin', synopsis: ''),
  (title: 'Satisfying Sweets', synopsis: ''),
  (title: 'Scone', synopsis: ''),
  (title: 'Scone Central', synopsis: ''),
  (title: 'Scone Pe', synopsis: ''),
  (title: 'Scone Sanctuary', synopsis: ''),
  (title: 'Scone Sensation', synopsis: ''),
  (title: 'Scone Sensations', synopsis: ''),
  (title: 'Scone Serenade', synopsis: ''),
  (title: 'Scone Solace', synopsis: ''),
  (title: 'Scone Zone', synopsis: ''),
  (title: 'Slice of Heaven', synopsis: ''),
  (title: 'Sourdough Delicacies', synopsis: ''),
  (title: 'Sourdough Delights', synopsis: ''),
  (title: 'Sourdough Heaven', synopsis: ''),
  (title: 'Sourdough Sanctuary', synopsis: ''),
  (title: 'Sourdough Sensations', synopsis: ''),
  (title: 'Sourdough Serenity', synopsis: ''),
  (title: 'Sourdough Specials', synopsis: ''),
  (title: 'Sprinkle and Spark', synopsis: ''),
  (title: 'Sprinkle Haven', synopsis: ''),
  (title: 'Sprinkle Magic', synopsis: ''),
  (title: 'Sprinkle Spectacle', synopsis: ''),
  (title: 'Sprinkle Spectra', synopsis: ''),
  (title: 'Sprinkle Station', synopsis: ''),
  (title: 'Sprinkled Sensations', synopsis: ''),
  (title: 'Sprouted Sweetness', synopsis: ''),
  (title: 'Sticky Buns', synopsis: ''),
  (title: 'Storybook Scones', synopsis: ''),
  (title: 'Storybook Sparkles', synopsis: ''),
  (title: 'Storybook Sugar', synopsis: ''),
  (title: 'Storybook Sweets', synopsis: ''),
  (title: 'Storybook Swirls', synopsis: ''),
  (title: 'Storytime Scones', synopsis: ''),
  (title: 'Storytime Sweets', synopsis: ''),
  (title: 'Suga Grove', synopsis: ''),
  (title: 'Suga Rain', synopsis: ''),
  (title: 'Sugar and Flour', synopsis: ''),
  (title: 'Sugar and Spice', synopsis: ''),
  (title: 'Sugar Blossom', synopsis: ''),
  (title: 'Sugar Bud', synopsis: ''),
  (title: 'Sugar Coated', synopsis: ''),
  (title: 'Sugar Coated Confections', synopsis: ''),
  (title: 'Sugar Coated Dreams', synopsis: ''),
  (title: 'Sugar Coated Oven', synopsis: ''),
  (title: 'Sugar Craft', synopsis: ''),
  (title: 'Sugar Drop', synopsis: ''),
  (title: 'Sugar Dust', synopsis: ''),
  (title: 'Sugar Euphoria', synopsis: ''),
  (title: 'Sugar Fairy', synopsis: ''),
  (title: 'Sugar Fiesta', synopsis: ''),
  (title: 'Sugar Glimmer', synopsis: ''),
  (title: 'Sugar Glow', synopsis: ''),
  (title: 'Sugar Grove', synopsis: ''),
  (title: 'Sugar Grove Delights', synopsis: ''),
  (title: 'Sugar Grove Diner', synopsis: ''),
  (title: 'Sugar Harvest', synopsis: ''),
  (title: 'Sugar Haze', synopsis: ''),
  (title: 'Sugar Heaven', synopsis: ''),
  (title: 'Sugar Heavenly', synopsis: ''),
  (title: 'Sugar High', synopsis: ''),
  (title: 'Sugar Nest', synopsis: ''),
  (title: 'Sugar Nook', synopsis: ''),
  (title: 'Sugar Plum', synopsis: ''),
  (title: 'Sugar Pop', synopsis: ''),
  (title: 'Sugar Rush', synopsis: ''),
  (title: 'Sugar Rush Pastries', synopsis: ''),
  (title: 'Sugar Sails', synopsis: ''),
  (title: 'Sugar Savory', synopsis: ''),
  (title: 'Sugar Scape', synopsis: ''),
  (title: 'Sugar Scoop', synopsis: ''),
  (title: 'Sugar Sensation', synopsis: ''),
  (title: 'Sugar Serenade', synopsis: ''),
  (title: 'Sugar Shack', synopsis: ''),
  (title: 'Sugar Spell', synopsis: ''),
  (title: 'Sugar Spellbinders', synopsis: ''),
  (title: 'Sugar Spellcrafters', synopsis: ''),
  (title: 'Sugar Sprinkle', synopsis: ''),
  (title: 'Sugar Sprinkles', synopsis: ''),
  (title: 'Sugar Storm', synopsis: ''),
  (title: 'Sugar Sweetscape', synopsis: ''),
  (title: 'Sugar Sweetsphere', synopsis: ''),
  (title: 'Sugar Symphony', synopsis: ''),
  (title: 'Sugar Temptation', synopsis: ''),
  (title: 'Sugarbelle', synopsis: ''),
  (title: 'Sugarbliss', synopsis: ''),
  (title: 'Sugarburst', synopsis: ''),
  (title: 'Sugared Dreams', synopsis: ''),
  (title: 'Sugared Euphoria', synopsis: ''),
  (title: 'Sugarnook', synopsis: ''),
  (title: 'Sugarnook Sweets', synopsis: ''),
  (title: 'Sugarplum Delights', synopsis: ''),
  (title: 'Sugarplum Heaven', synopsis: ''),
  (title: 'Sugarplum Pavilion', synopsis: ''),
  (title: 'Sugarstorm', synopsis: ''),
  (title: 'Sugarstrokes', synopsis: ''),
  (title: 'Sugary Crumb', synopsis: ''),
  (title: 'Sugary Heaven', synopsis: ''),
  (title: 'Sugary Seaside', synopsis: ''),
  (title: 'Sugary Seduction', synopsis: ''),
  (title: 'Sugary Serenity', synopsis: ''),
  (title: 'Sugary Spice', synopsis: ''),
  (title: 'Sugary Sunsets', synopsis: ''),
  (title: 'Sugary Sweearts', synopsis: ''),
  (title: 'Sugary Swirls', synopsis: ''),
  (title: 'Sugary Whiff', synopsis: ''),
  (title: 'Sugary Whiskers', synopsis: ''),
  (title: 'Sugary Wisp', synopsis: ''),
  (title: 'Sugary Wonders', synopsis: ''),
  (title: 'Sugary Woo', synopsis: ''),
  (title: 'Sugary Yum', synopsis: ''),
  (title: 'Sugary Zest', synopsis: ''),
  (title: 'Sugary Zing', synopsis: ''),
  (title: 'Sugary Zoom', synopsis: ''),
  (title: 'Sweet Candy', synopsis: ''),
  (title: 'Sweet Cravings', synopsis: ''),
  (title: 'Sweet Craze', synopsis: ''),
  (title: 'Sweet Crumb', synopsis: ''),
  (title: 'Sweet Crust', synopsis: ''),
  (title: 'Sweet Dazzle', synopsis: ''),
  (title: 'Sweet Delights', synopsis: ''),
  (title: 'Sweet Delights Junction', synopsis: ''),
  (title: 'Sweet Delish', synopsis: ''),
  (title: 'Sweet Enchantment', synopsis: ''),
  (title: 'Sweet Escape', synopsis: ''),
  (title: 'Sweet Escapes', synopsis: ''),
  (title: 'Sweet Fable', synopsis: ''),
  (title: 'Sweet Flick', synopsis: ''),
  (title: 'Sweet Frost', synopsis: ''),
  (title: 'Sweet Gleam', synopsis: ''),
  (title: 'Sweet Glimmer', synopsis: ''),
  (title: 'Sweet Glimpse', synopsis: ''),
  (title: 'Sweet Gusto', synopsis: ''),
  (title: 'Sweet Indulgence', synopsis: ''),
  (title: 'Sweet Nectar', synopsis: ''),
  (title: 'Sweet Nibble', synopsis: ''),
  (title: 'Sweet Nook', synopsis: ''),
  (title: 'Sweet Palette', synopsis: ''),
  (title: 'Sweet Paradise', synopsis: ''),
  (title: 'Sweet Peaks', synopsis: ''),
  (title: 'Sweet Pleasure', synopsis: ''),
  (title: 'Sweet Savor', synopsis: ''),
  (title: 'Sweet Scape', synopsis: ''),
  (title: 'Sweet Scents', synopsis: ''),
  (title: 'Sweet Sensations', synopsis: ''),
  (title: 'Sweet Serenade', synopsis: ''),
  (title: 'Sweet Serene', synopsis: ''),
  (title: 'Sweet Serenity', synopsis: ''),
  (title: 'Sweet Serenity Delights', synopsis: ''),
  (title: 'Sweet Serenity Sweets', synopsis: ''),
  (title: 'Sweet Sizzle', synopsis: ''),
  (title: 'Sweet Slices', synopsis: ''),
  (title: 'Sweet Snap', synopsis: ''),
  (title: 'Sweet Sparkle', synopsis: ''),
  (title: 'Sweet Spirit', synopsis: ''),
  (title: 'Sweet Spirits', synopsis: ''),
  (title: 'Sweet Splendor', synopsis: ''),
  (title: 'Sweet Spot', synopsis: ''),
  (title: 'Sweet Squeeze', synopsis: ''),
  (title: 'Sweet Station', synopsis: ''),
  (title: 'Sweet Stop', synopsis: ''),
  (title: 'Sweet Stroll', synopsis: ''),
  (title: 'Sweet Surrender', synopsis: ''),
  (title: 'Sweet Surrender Sanctuary', synopsis: ''),
  (title: 'Sweet Surrender Sweets', synopsis: ''),
  (title: 'Sweet Symphony', synopsis: ''),
  (title: 'Sweet Symphony Sweets', synopsis: ''),
  (title: 'Sweet Tart', synopsis: ''),
  (title: 'Sweet Tempt', synopsis: ''),
  (title: 'Sweet Tingle', synopsis: ''),
  (title: 'Sweet Tooth', synopsis: ''),
  (title: 'Sweet Tooth Delights', synopsis: ''),
  (title: 'Sweet Treats', synopsis: ''),
  (title: 'Sweet Twirl', synopsis: ''),
  (title: 'Sweet Vibe', synopsis: ''),
  (title: 'Sweet Vista', synopsis: ''),
  (title: 'Sweet Vivid', synopsis: ''),
  (title: 'Sweet Whimsy', synopsis: ''),
  (title: 'Sweet Whirl', synopsis: ''),
  (title: 'Sweet Zest', synopsis: ''),
  (title: 'Sweetbites', synopsis: ''),
  (title: 'Sweetly Yours Bakes', synopsis: ''),
  (title: 'Swirls and Sweets', synopsis: ''),
  (title: 'Swiss Roll Delights', synopsis: ''),
  (title: 'Swiss Roll Salon', synopsis: ''),
  (title: 'Swiss Roll Sensation', synopsis: ''),
  (title: 'Swiss Roll Sensations', synopsis: ''),
  (title: 'Swiss Roll Suite', synopsis: ''),
  (title: 'Swoonworthy Sweets', synopsis: ''),
  (title: 'Tale of Tarts', synopsis: ''),
  (title: 'Tale Tantalizers', synopsis: ''),
  (title: 'Tale Tiers', synopsis: ''),
  (title: 'Tale Time Tarts', synopsis: ''),
  (title: 'Tale Time Treats', synopsis: ''),
  (title: 'Tale Toppings', synopsis: ''),
  (title: 'Tale Treats', synopsis: ''),
  (title: 'Tale Truffles', synopsis: ''),
  (title: 'Tart', synopsis: ''),
  (title: 'Tart Boutique', synopsis: ''),
  (title: 'Tart Stop', synopsis: ''),
  (title: 'Tart Topia', synopsis: ''),
  (title: 'Tart Trove', synopsis: ''),
  (title: 'Tarteletta Terrace', synopsis: ''),
  (title: 'Tartelette Treasures', synopsis: ''),
  (title: 'Tartelette Triumphs', synopsis: ''),
  (title: 'Tasty Delights', synopsis: ''),
  (title: 'Tasty Tart', synopsis: ''),
  (title: 'Tasty Tarts', synopsis: ''),
  (title: 'Tasty Temptations', synopsis: ''),
  (title: 'Tasty Tidbits', synopsis: ''),
  (title: 'Tasty Tidbits Bakes', synopsis: ''),
  (title: 'Tasty Tiers', synopsis: ''),
  (title: 'Tasty Trails', synopsis: ''),
  (title: 'Tasty Treasures Bakes', synopsis: ''),
  (title: 'Tasty Treats', synopsis: ''),
  (title: 'Tasty Treats Trail', synopsis: ''),
  (title: 'Toffee Tantalizers', synopsis: ''),
  (title: 'Toffee Temptations', synopsis: ''),
  (title: 'Toffee Time', synopsis: ''),
  (title: 'Toffee Town', synopsis: ''),
  (title: 'Toffee Treat', synopsis: ''),
  (title: 'Toffee Treats', synopsis: ''),
  (title: 'Toffee Tryst', synopsis: ''),
  (title: 'Trotilja', synopsis: ''),
  (title: 'Vanilla Valley Bakes', synopsis: ''),
  (title: 'Vanilla Valley Delights', synopsis: ''),
  (title: 'Vanilla Velvet', synopsis: ''),
  (title: 'Vanilla Velvet Delights', synopsis: ''),
  (title: 'Vanilla Verve', synopsis: ''),
  (title: 'Vanilla View', synopsis: ''),
  (title: 'Vanilla Vision Bakes', synopsis: ''),
  (title: 'Vanilla Visions', synopsis: ''),
  (title: 'Vanilla Vista', synopsis: ''),
  (title: 'Vanilla Vixen Bakes', synopsis: ''),
  (title: 'Vanilla Vortex Bakes', synopsis: ''),
  (title: 'Vanilla Voyage', synopsis: ''),
  (title: 'Whimsical Wafers', synopsis: ''),
  (title: 'Whimsical Wheat', synopsis: ''),
  (title: 'Whimsical Whirligigs', synopsis: ''),
  (title: 'Whimsical Whirlwinds', synopsis: ''),
  (title: 'Whimsical Whisk', synopsis: ''),
  (title: 'Whimsical Whiskers', synopsis: ''),
  (title: 'Whimsical Wonders', synopsis: ''),
  (title: 'Whimsy Whirligigs', synopsis: ''),
  (title: 'Whimsy Whirlpools', synopsis: ''),
  (title: 'Whimsy Whirlwinds', synopsis: ''),
  (title: 'Whimsy Whiskers', synopsis: ''),
  (title: 'Whimsy Whisks', synopsis: ''),
  (title: 'Whipped Delights', synopsis: ''),
  (title: 'Whipped Up', synopsis: ''),
  (title: 'Whipped Up Delights', synopsis: ''),
  (title: 'Whipped Wanderlust', synopsis: ''),
  (title: 'Whipped Whimsy', synopsis: ''),
  (title: 'Whipped Whisk', synopsis: ''),
  (title: 'Whipped Whiskers', synopsis: ''),
  (title: 'Whipped Willow', synopsis: ''),
  (title: 'Whipped Wonderers', synopsis: ''),
  (title: 'Whipped Wonderments', synopsis: ''),
  (title: 'Whipped Wondersmiths', synopsis: ''),
  (title: 'Whisk and Bake', synopsis: ''),
  (title: 'Whisk and Waffle', synopsis: ''),
  (title: 'Whisk and Wand', synopsis: ''),
  (title: 'Whisk and Wander Bake', synopsis: ''),
  (title: 'Whisk and Wanderlust', synopsis: ''),
  (title: 'Whisk and Whims', synopsis: ''),
  (title: 'Whisk Away', synopsis: ''),
  (title: 'Whisked Away', synopsis: ''),
  (title: 'Whisked Away Bakes', synopsis: ''),
  (title: 'Whisked Oven', synopsis: ''),
  (title: 'Whisked Way', synopsis: ''),
  (title: 'Whisked Whimsy', synopsis: ''),
  (title: 'Whisked Wonderlands', synopsis: ''),
  (title: 'Whisked Wonders', synopsis: ''),
  (title: 'Whiskful Thinking', synopsis: ''),
  (title: 'Whiskful Whimsy', synopsis: ''),
  (title: 'Whiskful Wonderland', synopsis: ''),
  (title: 'Whiskful Wonders', synopsis: ''),
  (title: 'Whisking Well', synopsis: ''),
  (title: 'Wholesome Bakes', synopsis: ''),
  (title: 'Wonderland Whiskers', synopsis: ''),
  (title: 'Wondrous Whirls', synopsis: ''),
  (title: 'Yummy Treats', synopsis: ''),
  (title: 'Zebi Dorn', synopsis: ''),
  (title: 'Zestful', synopsis: ''),
  (title: 'Zesty Zephyr', synopsis: ''),
  (title: 'Zesty Zest', synopsis: ''),
};
