import '../name_r.dart';

const Set<NameR> en = {
  (name: 'Aether', synopsis: ''),
  (name: 'Aetheria', synopsis: ''),
  (name: 'Aetheria Essence', synopsis: ''),
  (name: 'Aetherial Glow', synopsis: ''),
  (name: 'Aetheris', synopsis: ''),
  (name: 'Alcyone', synopsis: ''),
  (name: 'Alcyone Glow', synopsis: ''),
  (name: 'Altair', synopsis: ''),
  (name: 'Altair Glow', synopsis: ''),
  (name: 'Altara', synopsis: ''),
  (name: 'Altaris', synopsis: ''),
  (name: 'Andromeda', synopsis: ''),
  (name: 'Andromeda Lumina', synopsis: ''),
  (name: 'Andromeda Veil', synopsis: ''),
  (name: 'Aquila', synopsis: ''),
  (name: 'Aquila Bellatrix', synopsis: ''),
  (name: 'Aquila Lyrastra', synopsis: ''),
  (name: 'Aquila Radiance', synopsis: ''),
  (name: 'Aquila Solara', synopsis: ''),
  (name: 'Aquila Solstice', synopsis: ''),
  (name: 'Aquilara', synopsis: ''),
  (name: 'Aquilaris', synopsis: ''),
  (name: 'Aquilian', synopsis: ''),
  (name: 'Aquiluna', synopsis: ''),
  (name: 'Asteria', synopsis: ''),
  (name: 'Asteria Radiance', synopsis: ''),
  (name: 'Astoria', synopsis: ''),
  (name: 'Astoria Ember', synopsis: ''),
  (name: 'Astorion', synopsis: ''),
  (name: 'Astra', synopsis: ''),
  (name: 'Astra Bellatrix', synopsis: ''),
  (name: 'Astra Lumina', synopsis: ''),
  (name: 'Astra Luminara', synopsis: ''),
  (name: 'Astra Zenithria', synopsis: ''),
  (name: 'Astradian', synopsis: ''),
  (name: 'Astradon', synopsis: ''),
  (name: 'Astradra', synopsis: ''),
  (name: 'Astraea', synopsis: ''),
  (name: 'Astraea Whisper', synopsis: ''),
  (name: 'Astraeus', synopsis: ''),
  (name: 'Astraeus Aquila', synopsis: ''),
  (name: 'Astraeus Essence', synopsis: ''),
  (name: 'Astraeus Nebularis', synopsis: ''),
  (name: 'Astraeus Phoenix', synopsis: ''),
  (name: 'Astraeus Pyranis', synopsis: ''),
  (name: 'Astraeus Solstice', synopsis: ''),
  (name: 'Astraeus Solvenna', synopsis: ''),
  (name: 'Astraeus Zephyrus', synopsis: ''),
  (name: 'Astral Alchemy', synopsis: ''),
  (name: 'Astral Belladris', synopsis: ''),
  (name: 'Astral Blossom', synopsis: ''),
  (name: 'Astral Borealis', synopsis: ''),
  (name: 'Astral Breeze', synopsis: ''),
  (name: 'Astral Cascade', synopsis: ''),
  (name: 'Astral Cascades', synopsis: ''),
  (name: 'Astral Celestia', synopsis: ''),
  (name: 'Astral Cosmos', synopsis: ''),
  (name: 'Astral Dreamer', synopsis: ''),
  (name: 'Astral Dreamscape', synopsis: ''),
  (name: 'Astral Echo', synopsis: ''),
  (name: 'Astral Echoes', synopsis: ''),
  (name: 'Astral Eclipse', synopsis: ''),
  (name: 'Astral Elixir', synopsis: ''),
  (name: 'Astral Ember', synopsis: ''),
  (name: 'Astral Enchantment', synopsis: ''),
  (name: 'Astral Enigma', synopsis: ''),
  (name: 'Astral Equinox', synopsis: ''),
  (name: 'Astral Essence', synopsis: ''),
  (name: 'Astral Guardian', synopsis: ''),
  (name: 'Astral Harmonia', synopsis: ''),
  (name: 'Astral Harmony', synopsis: ''),
  (name: 'Astral Haven', synopsis: ''),
  (name: 'Astral Horizon', synopsis: ''),
  (name: 'Astral Journey', synopsis: ''),
  (name: 'Astral Lullaby', synopsis: ''),
  (name: 'Astral Luminary', synopsis: ''),
  (name: 'Astral Lyric', synopsis: ''),
  (name: 'Astral Mirage', synopsis: ''),
  (name: 'Astral Nebulous', synopsis: ''),
  (name: 'Astral Nexus', synopsis: ''),
  (name: 'Astral Nova', synopsis: ''),
  (name: 'Astral Prism', synopsis: ''),
  (name: 'Astral Pyronova', synopsis: ''),
  (name: 'Astral Radiance', synopsis: ''),
  (name: 'Astral Reverie', synopsis: ''),
  (name: 'Astral Rhapsody', synopsis: ''),
  (name: 'Astral Seraph', synopsis: ''),
  (name: 'Astral Serenade', synopsis: ''),
  (name: 'Astral Serenity', synopsis: ''),
  (name: 'Astral Solace', synopsis: ''),
  (name: 'Astral Solstice', synopsis: ''),
  (name: 'Astral Sonata', synopsis: ''),
  (name: 'Astral Stardust', synopsis: ''),
  (name: 'Astral Symphony', synopsis: ''),
  (name: 'Astral Veil', synopsis: ''),
  (name: 'Astral Whisper', synopsis: ''),
  (name: 'Astral Zephyr', synopsis: ''),
  (name: 'Astrala', synopsis: ''),
  (name: 'Astralia', synopsis: ''),
  (name: 'Astraline', synopsis: ''),
  (name: 'Astralis', synopsis: ''),
  (name: 'Astralis Bellatrix', synopsis: ''),
  (name: 'Astralis Celestial', synopsis: ''),
  (name: 'Astralis Essence', synopsis: ''),
  (name: 'Astralis Halo', synopsis: ''),
  (name: 'Astralis Seraph', synopsis: ''),
  (name: 'Astralis Serenade', synopsis: ''),
  (name: 'Astralis Solarastra', synopsis: ''),
  (name: 'Astralis Stellarion', synopsis: ''),
  (name: 'Astralis Stellaris', synopsis: ''),
  (name: 'Astralis Zephyrana', synopsis: ''),
  (name: 'Astralyn', synopsis: ''),
  (name: 'Astralyn Luster', synopsis: ''),
  (name: 'Astranis', synopsis: ''),
  (name: 'Astrellis', synopsis: ''),
  (name: 'Astreluna', synopsis: ''),
  (name: 'Astrid', synopsis: ''),
  (name: 'Astrid Halo', synopsis: ''),
  (name: 'Astrid Luster', synopsis: ''),
  (name: 'Astridora', synopsis: ''),
  (name: 'Astrila', synopsis: ''),
  (name: 'Astriluna', synopsis: ''),
  (name: 'Astronea', synopsis: ''),
  (name: 'Astronix', synopsis: ''),
  (name: 'Astronova', synopsis: ''),
  (name: 'Auranova', synopsis: ''),
  (name: 'Aurelia', synopsis: ''),
  (name: 'Aurelia Lunaris', synopsis: ''),
  (name: 'Aurelia Nebularis', synopsis: ''),
  (name: 'Aurelia Spark', synopsis: ''),
  (name: 'Aurelian Blaze', synopsis: ''),
  (name: 'Aurelian Breeze', synopsis: ''),
  (name: 'Aurelian Cascade', synopsis: ''),
  (name: 'Aurelian Nova', synopsis: ''),
  (name: 'Aurelian Radiance', synopsis: ''),
  (name: 'Aurelian Symphony', synopsis: ''),
  (name: 'Auriel', synopsis: ''),
  (name: 'Auriel Grace', synopsis: ''),
  (name: 'Aurius', synopsis: ''),
  (name: 'Aurius Radiance', synopsis: ''),
  (name: 'Aurora', synopsis: ''),
  (name: 'Aurora Astraeus', synopsis: ''),
  (name: 'Aurora Borealis', synopsis: ''),
  (name: 'Aurora Breath', synopsis: ''),
  (name: 'Aurora Celestial', synopsis: ''),
  (name: 'Aurora Equinox', synopsis: ''),
  (name: 'Aurora Flare', synopsis: ''),
  (name: 'Aurora Harmonies', synopsis: ''),
  (name: 'Aurora Lunaris', synopsis: ''),
  (name: 'Aurora Nimbus', synopsis: ''),
  (name: 'Aurora Nova', synopsis: ''),
  (name: 'Aurora Seraphim', synopsis: ''),
  (name: 'Aurora Serenade', synopsis: ''),
  (name: 'Aurora Veil', synopsis: ''),
  (name: 'Aurora Whispers', synopsis: ''),
  (name: 'Aurorae Seraphim', synopsis: ''),
  (name: 'Auroras', synopsis: ''),
  (name: 'Auroria', synopsis: ''),
  (name: 'Auroria Vesperia', synopsis: ''),
  (name: 'Auroriana', synopsis: ''),
  (name: 'Aurorion', synopsis: ''),
  (name: 'Avalaris', synopsis: ''),
  (name: 'Avalon', synopsis: ''),
  (name: 'Avalon Aurora', synopsis: ''),
  (name: 'Avalon Celestia', synopsis: ''),
  (name: 'Avalon Horizon', synopsis: ''),
  (name: 'Avalon Whispers', synopsis: ''),
  (name: 'Avalonia', synopsis: ''),
  (name: 'Avalora', synopsis: ''),
  (name: 'Avaloria', synopsis: ''),
  (name: 'Belladra', synopsis: ''),
  (name: 'Belladris', synopsis: ''),
  (name: 'Belladris Solarastra', synopsis: ''),
  (name: 'Bellara', synopsis: ''),
  (name: 'Bellarian', synopsis: ''),
  (name: 'Bellatrix', synopsis: ''),
  (name: 'Bellatrix Aquilaris', synopsis: ''),
  (name: 'Bellatrix Gleam', synopsis: ''),
  (name: 'Bellatrix Halo', synopsis: ''),
  (name: 'Bellatrix Lunaris', synopsis: ''),
  (name: 'Bellatrixis', synopsis: ''),
  (name: 'Bellavara', synopsis: ''),
  (name: 'Bellaven', synopsis: ''),
  (name: 'Bellavox', synopsis: ''),
  (name: 'Caelum', synopsis: ''),
  (name: 'Caelum Glow', synopsis: ''),
  (name: 'Caelum Radiance', synopsis: ''),
  (name: 'Capella', synopsis: ''),
  (name: 'Capella Glow', synopsis: ''),
  (name: 'Cassarian', synopsis: ''),
  (name: 'Cassariana', synopsis: ''),
  (name: 'Cassiel', synopsis: ''),
  (name: 'Cassiel Whisper', synopsis: ''),
  (name: 'Cassiopae', synopsis: ''),
  (name: 'Cassiopeia', synopsis: ''),
  (name: 'Cassiopeia Lunarastra', synopsis: ''),
  (name: 'Cassiopeia Lyrastra', synopsis: ''),
  (name: 'Cassiopeia Veil', synopsis: ''),
  (name: 'Cassiopella', synopsis: ''),
  (name: 'Cassiopia', synopsis: ''),
  (name: 'Cassiopra', synopsis: ''),
  (name: 'Celestara', synopsis: ''),
  (name: 'Celestia', synopsis: ''),
  (name: 'Celestia Blaze', synopsis: ''),
  (name: 'Celestia Bliss', synopsis: ''),
  (name: 'Celestia Cascade', synopsis: ''),
  (name: 'Celestia Echo', synopsis: ''),
  (name: 'Celestia Eclipse', synopsis: ''),
  (name: 'Celestia Ember', synopsis: ''),
  (name: 'Celestia Equinox', synopsis: ''),
  (name: 'Celestia Luminary', synopsis: ''),
  (name: 'Celestia Lyricora', synopsis: ''),
  (name: 'Celestia Mirage', synopsis: ''),
  (name: 'Celestia Mist', synopsis: ''),
  (name: 'Celestia Nimbus', synopsis: ''),
  (name: 'Celestia Nova', synopsis: ''),
  (name: 'Celestia Prism', synopsis: ''),
  (name: 'Celestia Radiance', synopsis: ''),
  (name: 'Celestia Serenity', synopsis: ''),
  (name: 'Celestia Solstice', synopsis: ''),
  (name: 'Celestia Sylph', synopsis: ''),
  (name: 'Celestia Veil', synopsis: ''),
  (name: 'Celestia Zephyr', synopsis: ''),
  (name: 'Celestia Zephyrus', synopsis: ''),
  (name: 'Celestial Alchemy', synopsis: ''),
  (name: 'Celestial Aquila', synopsis: ''),
  (name: 'Celestial Breeze', synopsis: ''),
  (name: 'Celestial Brilliance', synopsis: ''),
  (name: 'Celestial Cascade', synopsis: ''),
  (name: 'Celestial Cosmos', synopsis: ''),
  (name: 'Celestial Dream', synopsis: ''),
  (name: 'Celestial Dreamer', synopsis: ''),
  (name: 'Celestial Echo', synopsis: ''),
  (name: 'Celestial Ember', synopsis: ''),
  (name: 'Celestial Embrace', synopsis: ''),
  (name: 'Celestial Euphoria', synopsis: ''),
  (name: 'Celestial Glow', synopsis: ''),
  (name: 'Celestial Guardian', synopsis: ''),
  (name: 'Celestial Halo', synopsis: ''),
  (name: 'Celestial Harmonia', synopsis: ''),
  (name: 'Celestial Harmony', synopsis: ''),
  (name: 'Celestial Haze', synopsis: ''),
  (name: 'Celestial Hydra', synopsis: ''),
  (name: 'Celestial Hymn', synopsis: ''),
  (name: 'Celestial Journey', synopsis: ''),
  (name: 'Celestial Lullaby', synopsis: ''),
  (name: 'Celestial Lumina', synopsis: ''),
  (name: 'Celestial Luminary', synopsis: ''),
  (name: 'Celestial Mirage', synopsis: ''),
  (name: 'Celestial Nebula', synopsis: ''),
  (name: 'Celestial Nexus', synopsis: ''),
  (name: 'Celestial Nova', synopsis: ''),
  (name: 'Celestial Pyxis', synopsis: ''),
  (name: 'Celestial Radiance', synopsis: ''),
  (name: 'Celestial Reverie', synopsis: ''),
  (name: 'Celestial Serenade', synopsis: ''),
  (name: 'Celestial Serenity', synopsis: ''),
  (name: 'Celestial Shimmer', synopsis: ''),
  (name: 'Celestial Solstice', synopsis: ''),
  (name: 'Celestial Sparkle', synopsis: ''),
  (name: 'Celestial Symphony', synopsis: ''),
  (name: 'Celestial Twilight', synopsis: ''),
  (name: 'Celestial Vortex', synopsis: ''),
  (name: 'Celestial Whisper', synopsis: ''),
  (name: 'Celestial Whispers', synopsis: ''),
  (name: 'Celestial Zephyr', synopsis: ''),
  (name: 'Celestine', synopsis: ''),
  (name: 'Celestine Astradra', synopsis: ''),
  (name: 'Celestine Astral', synopsis: ''),
  (name: 'Celestine Glow', synopsis: ''),
  (name: 'Celestine Halo', synopsis: ''),
  (name: 'Celestine Orion', synopsis: ''),
  (name: 'Celestine Orionis', synopsis: ''),
  (name: 'Celestine Pyrastra', synopsis: ''),
  (name: 'Celestine Radiance', synopsis: ''),
  (name: 'Celestine Veil', synopsis: ''),
  (name: 'Celestius', synopsis: ''),
  (name: 'Celestria', synopsis: ''),
  (name: 'Celestria Nebulia', synopsis: ''),
  (name: 'Celestrix', synopsis: ''),
  (name: 'Comet', synopsis: ''),
  (name: 'Comet Trail', synopsis: ''),
  (name: 'Cosmic Breeze', synopsis: ''),
  (name: 'Cosmic Cascade', synopsis: ''),
  (name: 'Cosmic Delight', synopsis: ''),
  (name: 'Cosmic Dream', synopsis: ''),
  (name: 'Cosmic Ember', synopsis: ''),
  (name: 'Cosmic Embrace', synopsis: ''),
  (name: 'Cosmic Harmony', synopsis: ''),
  (name: 'Cosmic Illusion', synopsis: ''),
  (name: 'Cosmic Mirage', synopsis: ''),
  (name: 'Cosmic Nova', synopsis: ''),
  (name: 'Cosmic Radiance', synopsis: ''),
  (name: 'Cosmic Serenade', synopsis: ''),
  (name: 'Cosmic Serenity', synopsis: ''),
  (name: 'Cosmic Solace', synopsis: ''),
  (name: 'Cosmic Sonnet', synopsis: ''),
  (name: 'Cosmic Symphony', synopsis: ''),
  (name: 'Cosmic Twilight', synopsis: ''),
  (name: 'Cosmic Whisper', synopsis: ''),
  (name: 'Cosmic Whispers', synopsis: ''),
  (name: 'Cosmic Zephyr', synopsis: ''),
  (name: 'Cosmo Cascade', synopsis: ''),
  (name: 'Cosmos', synopsis: ''),
  (name: 'Crystal Nebula', synopsis: ''),
  (name: 'Crystal Veil', synopsis: ''),
  (name: 'Cygnus', synopsis: ''),
  (name: 'Delphinus', synopsis: ''),
  (name: 'Delphinus Lumina', synopsis: ''),
  (name: 'Delphinus Veil', synopsis: ''),
  (name: 'Dracaris', synopsis: ''),
  (name: 'Draco', synopsis: ''),
  (name: 'Draco Astralis', synopsis: ''),
  (name: 'Draco Embrace', synopsis: ''),
  (name: 'Draco Lumina', synopsis: ''),
  (name: 'Draco Solara', synopsis: ''),
  (name: 'Dracoria', synopsis: ''),
  (name: 'Dracoria Solarastra', synopsis: ''),
  (name: 'Dracoria Solvenna', synopsis: ''),
  (name: 'Dracoria Zephyrella', synopsis: ''),
  (name: 'Dracorian', synopsis: ''),
  (name: 'Dracostra', synopsis: ''),
  (name: 'Elysara', synopsis: ''),
  (name: 'Elysaria', synopsis: ''),
  (name: 'Elysian Cascade', synopsis: ''),
  (name: 'Elysian Cosmos', synopsis: ''),
  (name: 'Elysian Ember', synopsis: ''),
  (name: 'Elysian Equinox', synopsis: ''),
  (name: 'Elysian Flare', synopsis: ''),
  (name: 'Elysian Harmony', synopsis: ''),
  (name: 'Elysian Lullaby', synopsis: ''),
  (name: 'Elysian Nebula', synopsis: ''),
  (name: 'Elysian Nebulon', synopsis: ''),
  (name: 'Elysian Nova', synopsis: ''),
  (name: 'Elysian Seraphim', synopsis: ''),
  (name: 'Elysian Serenade', synopsis: ''),
  (name: 'Elysian Solstice', synopsis: ''),
  (name: 'Elysian Stardust', synopsis: ''),
  (name: 'Elysian Symphony', synopsis: ''),
  (name: 'Elysian Twilight', synopsis: ''),
  (name: 'Elysian Whisper', synopsis: ''),
  (name: 'Elysian Whispers', synopsis: ''),
  (name: 'Elysian Zephyr', synopsis: ''),
  (name: 'Elysium', synopsis: ''),
  (name: 'Elysium Astradra', synopsis: ''),
  (name: 'Elysium Lunarastra', synopsis: ''),
  (name: 'Elysium Novastra', synopsis: ''),
  (name: 'Ember', synopsis: ''),
  (name: 'Ember Astralis', synopsis: ''),
  (name: 'Ember Blaze', synopsis: ''),
  (name: 'Ember Orionis', synopsis: ''),
  (name: 'Emberis', synopsis: ''),
  (name: 'Enchanted Harmonies', synopsis: ''),
  (name: 'Enchanted Harmony', synopsis: ''),
  (name: 'Enchanted Horizon', synopsis: ''),
  (name: 'Enchanted Nebula', synopsis: ''),
  (name: 'Enchanted Nebulosity', synopsis: ''),
  (name: 'Enchanted Nexus', synopsis: ''),
  (name: 'Enchanted Serenade', synopsis: ''),
  (name: 'Enchanted Solace', synopsis: ''),
  (name: 'Enchanted Solstice', synopsis: ''),
  (name: 'Enchanted Twilight', synopsis: ''),
  (name: 'Epsilon', synopsis: ''),
  (name: 'Epsilon Halo', synopsis: ''),
  (name: 'Epsilon Lumina', synopsis: ''),
  (name: 'Equilonis', synopsis: ''),
  (name: 'Equinova', synopsis: ''),
  (name: 'Equinox', synopsis: ''),
  (name: 'Equinox Aquilian', synopsis: ''),
  (name: 'Equinox Dracaris', synopsis: ''),
  (name: 'Equinox Pyronis', synopsis: ''),
  (name: 'Equinox Radiance', synopsis: ''),
  (name: 'Equinoxia', synopsis: ''),
  (name: 'Equinoxis', synopsis: ''),
  (name: 'Eridanis', synopsis: ''),
  (name: 'Eridanus', synopsis: ''),
  (name: 'Ethereal Cascade', synopsis: ''),
  (name: 'Ethereal Dreamer', synopsis: ''),
  (name: 'Ethereal Eclipse', synopsis: ''),
  (name: 'Ethereal Glow', synopsis: ''),
  (name: 'Ethereal Harmony', synopsis: ''),
  (name: 'Ethereal Mirage', synopsis: ''),
  (name: 'Ethereal Nebula', synopsis: ''),
  (name: 'Ethereal Nova', synopsis: ''),
  (name: 'Ethereal Radiance', synopsis: ''),
  (name: 'Ethereal Serenade', synopsis: ''),
  (name: 'Ethereal Solstice', synopsis: ''),
  (name: 'Ethereal Twilight', synopsis: ''),
  (name: 'Ethereal Whisper', synopsis: ''),
  (name: 'Ethereal Zephyr', synopsis: ''),
  (name: 'Everlight Cascade', synopsis: ''),
  (name: 'Everlight Harmony', synopsis: ''),
  (name: 'Everlight Nebulus', synopsis: ''),
  (name: 'Everlight Seraph', synopsis: ''),
  (name: 'Everlight Solara', synopsis: ''),
  (name: 'Everlight Sylph', synopsis: ''),
  (name: 'Galaxia', synopsis: ''),
  (name: 'Galaxia Breath', synopsis: ''),
  (name: 'Galaxia Enigma', synopsis: ''),
  (name: 'Galaxia Gleam', synopsis: ''),
  (name: 'Galaxia Lullaby', synopsis: ''),
  (name: 'Galaxia Song', synopsis: ''),
  (name: 'Galaxia Veil', synopsis: ''),
  (name: 'Galaxy Breeze', synopsis: ''),
  (name: 'Galaxy Cascade', synopsis: ''),
  (name: 'Galaxy Dream', synopsis: ''),
  (name: 'Galaxy Harmony', synopsis: ''),
  (name: 'Galaxy Serenade', synopsis: ''),
  (name: 'Galaxy Whisper', synopsis: ''),
  (name: 'Galaxy Zephyr', synopsis: ''),
  (name: 'Gemini', synopsis: ''),
  (name: 'Gemini Embrace', synopsis: ''),
  (name: 'Halcyon', synopsis: ''),
  (name: 'Halcyon Radiance', synopsis: ''),
  (name: 'Halcyria', synopsis: ''),
  (name: 'Helios', synopsis: ''),
  (name: 'Helios Radiant', synopsis: ''),
  (name: 'Horizon', synopsis: ''),
  (name: 'Horizon Embrace', synopsis: ''),
  (name: 'Horizonis', synopsis: ''),
  (name: 'Hydra', synopsis: ''),
  (name: 'Hydra Breath', synopsis: ''),
  (name: 'Luminara', synopsis: ''),
  (name: 'Luminara Equinox', synopsis: ''),
  (name: 'Luminara Halo', synopsis: ''),
  (name: 'Luminara Lyra', synopsis: ''),
  (name: 'Luminary Aether', synopsis: ''),
  (name: 'Luminary Aurora', synopsis: ''),
  (name: 'Luminary Cascade', synopsis: ''),
  (name: 'Luminary Dreamscape', synopsis: ''),
  (name: 'Luminary Ember', synopsis: ''),
  (name: 'Luminary Harmonies', synopsis: ''),
  (name: 'Luminary Lullaby', synopsis: ''),
  (name: 'Luminary Nexus', synopsis: ''),
  (name: 'Luminary Nova', synopsis: ''),
  (name: 'Luminary Reverie', synopsis: ''),
  (name: 'Luminary Serenade', synopsis: ''),
  (name: 'Luminary Serenity', synopsis: ''),
  (name: 'Luminary Solara', synopsis: ''),
  (name: 'Luminary Solstice', synopsis: ''),
  (name: 'Luminary Sonata', synopsis: ''),
  (name: 'Luminary Sparkle', synopsis: ''),
  (name: 'Luminary Stardust', synopsis: ''),
  (name: 'Luminary Sylph', synopsis: ''),
  (name: 'Luminary Veil', synopsis: ''),
  (name: 'Luminary Zephyrus', synopsis: ''),
  (name: 'Luminescent Cascade', synopsis: ''),
  (name: 'Luminescent Journey', synopsis: ''),
  (name: 'Luminous Dreamer', synopsis: ''),
  (name: 'Luminous Ember', synopsis: ''),
  (name: 'Luminous Glow', synopsis: ''),
  (name: 'Luminous Mirage', synopsis: ''),
  (name: 'Luminous Nebula', synopsis: ''),
  (name: 'Luminous Seraph', synopsis: ''),
  (name: 'Luminous Serenity', synopsis: ''),
  (name: 'Luminous Stardust', synopsis: ''),
  (name: 'Luminous Symphony', synopsis: ''),
  (name: 'Luminous Twilight', synopsis: ''),
  (name: 'Luminous Veil', synopsis: ''),
  (name: 'Luminous Zephyr', synopsis: ''),
  (name: 'Lumos Seraph', synopsis: ''),
  (name: 'Lumos Zephyr', synopsis: ''),
  (name: 'Luna', synopsis: ''),
  (name: 'Luna Astralis', synopsis: ''),
  (name: 'Luna Aurora', synopsis: ''),
  (name: 'Luna Cascade', synopsis: ''),
  (name: 'Luna Draco', synopsis: ''),
  (name: 'Luna Embrace', synopsis: ''),
  (name: 'Luna Equinoxis', synopsis: ''),
  (name: 'Luna Glow', synopsis: ''),
  (name: 'Luna Lumina', synopsis: ''),
  (name: 'Luna Mirage', synopsis: ''),
  (name: 'Luna Pyranis', synopsis: ''),
  (name: 'Luna Radiance', synopsis: ''),
  (name: 'Luna Serenade', synopsis: ''),
  (name: 'Luna Serenity', synopsis: ''),
  (name: 'Luna Solace', synopsis: ''),
  (name: 'Luna Solara', synopsis: ''),
  (name: 'Luna Solarastra', synopsis: ''),
  (name: 'Luna Solstice', synopsis: ''),
  (name: 'Luna Symphony', synopsis: ''),
  (name: 'Luna Veil', synopsis: ''),
  (name: 'Luna Vesperia', synopsis: ''),
  (name: 'Luna Whisper', synopsis: ''),
  (name: 'Luna Zephyr', synopsis: ''),
  (name: 'Lunar Aether', synopsis: ''),
  (name: 'Lunar Aurora', synopsis: ''),
  (name: 'Lunar Blaze', synopsis: ''),
  (name: 'Lunar Cascade', synopsis: ''),
  (name: 'Lunar Dream', synopsis: ''),
  (name: 'Lunar Elixir', synopsis: ''),
  (name: 'Lunar Ember', synopsis: ''),
  (name: 'Lunar Glimmer', synopsis: ''),
  (name: 'Lunar Harmony', synopsis: ''),
  (name: 'Lunar Ignis', synopsis: ''),
  (name: 'Lunar Mirage', synopsis: ''),
  (name: 'Lunar Nebula', synopsis: ''),
  (name: 'Lunar Nova', synopsis: ''),
  (name: 'Lunar Radiance', synopsis: ''),
  (name: 'Lunar Seraph', synopsis: ''),
  (name: 'Lunar Serenade', synopsis: ''),
  (name: 'Lunar Solstice', synopsis: ''),
  (name: 'Lunar Symphony', synopsis: ''),
  (name: 'Lunar Twilight', synopsis: ''),
  (name: 'Lunar Veil', synopsis: ''),
  (name: 'Lunar Whisper', synopsis: ''),
  (name: 'Lunar Whispers', synopsis: ''),
  (name: 'Lunar Zephyr', synopsis: ''),
  (name: 'Lunara', synopsis: ''),
  (name: 'Lunarastra', synopsis: ''),
  (name: 'Lunaria', synopsis: ''),
  (name: 'Lunaris', synopsis: ''),
  (name: 'Lunaris Alchemy', synopsis: ''),
  (name: 'Lunaris Cascade', synopsis: ''),
  (name: 'Lunaris Celestine', synopsis: ''),
  (name: 'Lunaris Ember', synopsis: ''),
  (name: 'Lunaris Harmonia', synopsis: ''),
  (name: 'Lunaris Nova', synopsis: ''),
  (name: 'Lunaris Seraph', synopsis: ''),
  (name: 'Lunaris Serenade', synopsis: ''),
  (name: 'Lunaris Symphony', synopsis: ''),
  (name: 'Lunaris Veil', synopsis: ''),
  (name: 'Luneth', synopsis: ''),
  (name: 'Lunova', synopsis: ''),
  (name: 'Lyra', synopsis: ''),
  (name: 'Lyra Altair', synopsis: ''),
  (name: 'Lyra Belladra', synopsis: ''),
  (name: 'Lyra Celestialis', synopsis: ''),
  (name: 'Lyra Equinox', synopsis: ''),
  (name: 'Lyra Halo', synopsis: ''),
  (name: 'Lyra Melody', synopsis: ''),
  (name: 'Lyra Nebula', synopsis: ''),
  (name: 'Lyra Nova', synopsis: ''),
  (name: 'Lyra Novastra', synopsis: ''),
  (name: 'Lyra Prism', synopsis: ''),
  (name: 'Lyra Solara', synopsis: ''),
  (name: 'Lyra Solstice', synopsis: ''),
  (name: 'Lyra Solsticea', synopsis: ''),
  (name: 'Lyra Stellastra', synopsis: ''),
  (name: 'Lyra Zephyrella', synopsis: ''),
  (name: 'Lyraelis', synopsis: ''),
  (name: 'Lyrastra', synopsis: ''),
  (name: 'Lyriastra', synopsis: ''),
  (name: 'Lyric', synopsis: ''),
  (name: 'Lyric Equinox', synopsis: ''),
  (name: 'Lyric Melody', synopsis: ''),
  (name: 'Lyric Nova', synopsis: ''),
  (name: 'Lyric Solara', synopsis: ''),
  (name: 'Lyric Solstice', synopsis: ''),
  (name: 'Lyricora', synopsis: ''),
  (name: 'Lyricora Astralia', synopsis: ''),
  (name: 'Lyricus', synopsis: ''),
  (name: 'Lyrielle', synopsis: ''),
  (name: 'Lyristar', synopsis: ''),
  (name: 'Lyristella', synopsis: ''),
  (name: 'Lyrius', synopsis: ''),
  (name: 'Lyroth', synopsis: ''),
  (name: 'Moonbeam Embrace', synopsis: ''),
  (name: 'Moonbeam Serenade', synopsis: ''),
  (name: 'Moonbeam Symphony', synopsis: ''),
  (name: 'Moonfire Cascade', synopsis: ''),
  (name: 'Moonfire Glimmer', synopsis: ''),
  (name: 'Moonfire Vortex', synopsis: ''),
  (name: 'Moonfire Whisper', synopsis: ''),
  (name: 'Moonlit Dreamscape', synopsis: ''),
  (name: 'Moonlit Ember', synopsis: ''),
  (name: 'Moonlit Enigma', synopsis: ''),
  (name: 'Moonlit Mirage', synopsis: ''),
  (name: 'Moonlit Nova', synopsis: ''),
  (name: 'Moonlit Prism', synopsis: ''),
  (name: 'Moonlit Radiance', synopsis: ''),
  (name: 'Moonlit Rhapsody', synopsis: ''),
  (name: 'Moonlit Serenade', synopsis: ''),
  (name: 'Moonlit Stardust', synopsis: ''),
  (name: 'Moonlit Symphony', synopsis: ''),
  (name: 'Moonlit Whisper', synopsis: ''),
  (name: 'Nebula Illusion', synopsis: ''),
  (name: 'Nebula Lumina', synopsis: ''),
  (name: 'Nebula Mist', synopsis: ''),
  (name: 'Nebula Nova', synopsis: ''),
  (name: 'Nebula Radiance', synopsis: ''),
  (name: 'Nebula Seraph', synopsis: ''),
  (name: 'Nebula Seraphim', synopsis: ''),
  (name: 'Nebula Serenity', synopsis: ''),
  (name: 'Nebula Solace', synopsis: ''),
  (name: 'Nebula Solara', synopsis: ''),
  (name: 'Nebula Solstice', synopsis: ''),
  (name: 'Nebula Solvenna', synopsis: ''),
  (name: 'Nebula Song', synopsis: ''),
  (name: 'Nebula Sparkle', synopsis: ''),
  (name: 'Nebula Stardust', synopsis: ''),
  (name: 'Nebula Symphony', synopsis: ''),
  (name: 'Nebula Twilight', synopsis: ''),
  (name: 'Nebula Veil', synopsis: ''),
  (name: 'Nebula Whisperer', synopsis: ''),
  (name: 'Nebula Whispers', synopsis: ''),
  (name: 'Nebulaic Radiance', synopsis: ''),
  (name: 'Nebulaic Realm', synopsis: ''),
  (name: 'Nebularis', synopsis: ''),
  (name: 'Nebulia', synopsis: ''),
  (name: 'Nebulon', synopsis: ''),
  (name: 'Nebulon Luster', synopsis: ''),
  (name: 'Nimbus', synopsis: ''),
  (name: 'Nimbus Radiance', synopsis: ''),
  (name: 'Nocturna', synopsis: ''),
  (name: 'Nocturna Lumina', synopsis: ''),
  (name: 'Novastra', synopsis: ''),
  (name: 'Novastris', synopsis: ''),
  (name: 'Ophelia', synopsis: ''),
  (name: 'Ophelia Veil', synopsis: ''),
  (name: 'Orinthia', synopsis: ''),
  (name: 'Orion', synopsis: ''),
  (name: 'Orion Glow', synopsis: ''),
  (name: 'Orion Halo', synopsis: ''),
  (name: 'Orion Luminary', synopsis: ''),
  (name: 'Orion Lunastra', synopsis: ''),
  (name: 'Orion Lyra', synopsis: ''),
  (name: 'Orion Path', synopsis: ''),
  (name: 'Orion Serenade', synopsis: ''),
  (name: 'Orion Solstice', synopsis: ''),
  (name: 'Orion Vesperia', synopsis: ''),
  (name: 'Orionia', synopsis: ''),
  (name: 'Orionis', synopsis: ''),
  (name: 'Orionis Nebula', synopsis: ''),
  (name: 'Phoenixia', synopsis: ''),
  (name: 'Phoenixia Flame', synopsis: ''),
  (name: 'Pyranis', synopsis: ''),
  (name: 'Pyranova', synopsis: ''),
  (name: 'Pyranova Stellaris', synopsis: ''),
  (name: 'Pyraphina', synopsis: ''),
  (name: 'Pyrastra', synopsis: ''),
  (name: 'Pyrastra Lunaria', synopsis: ''),
  (name: 'Pyrenis', synopsis: ''),
  (name: 'Pyro Nebula', synopsis: ''),
  (name: 'Pyro Novastra', synopsis: ''),
  (name: 'Pyronis', synopsis: ''),
  (name: 'Pyronis Avalaris', synopsis: ''),
  (name: 'Pyronis Lunarastra', synopsis: ''),
  (name: 'Pyronis Solsticea', synopsis: ''),
  (name: 'Pyronova', synopsis: ''),
  (name: 'Pyrora', synopsis: ''),
  (name: 'Pyrovia', synopsis: ''),
  (name: 'Pyrrus', synopsis: ''),
  (name: 'Pyxis', synopsis: ''),
  (name: 'Pyxis Aurora', synopsis: ''),
  (name: 'Pyxis Lumina', synopsis: ''),
  (name: 'Pyxis Nebulae', synopsis: ''),
  (name: 'Pyxis Twilight', synopsis: ''),
  (name: 'Radiant Aurora', synopsis: ''),
  (name: 'Radiant Borealis', synopsis: ''),
  (name: 'Radiant Cascade', synopsis: ''),
  (name: 'Radiant Dream', synopsis: ''),
  (name: 'Radiant Dreamer', synopsis: ''),
  (name: 'Radiant Dreams', synopsis: ''),
  (name: 'Radiant Dreamscape', synopsis: ''),
  (name: 'Radiant Echo', synopsis: ''),
  (name: 'Radiant Eclipse', synopsis: ''),
  (name: 'Radiant Ember', synopsis: ''),
  (name: 'Radiant Enigma', synopsis: ''),
  (name: 'Radiant Flare', synopsis: ''),
  (name: 'Radiant Harmony', synopsis: ''),
  (name: 'Radiant Horizon', synopsis: ''),
  (name: 'Radiant Lunar', synopsis: ''),
  (name: 'Radiant Nebula', synopsis: ''),
  (name: 'Radiant Nexus', synopsis: ''),
  (name: 'Radiant Nimbus', synopsis: ''),
  (name: 'Radiant Nova', synopsis: ''),
  (name: 'Radiant Prism', synopsis: ''),
  (name: 'Radiant Radiance', synopsis: ''),
  (name: 'Radiant Serenade', synopsis: ''),
  (name: 'Radiant Solara', synopsis: ''),
  (name: 'Radiant Solstice', synopsis: ''),
  (name: 'Radiant Stardust', synopsis: ''),
  (name: 'Radiant Symphony', synopsis: ''),
  (name: 'Radiant Twilight', synopsis: ''),
  (name: 'Radiant Whisper', synopsis: ''),
  (name: 'Radiant Zephyr', synopsis: ''),
  (name: 'Selene', synopsis: ''),
  (name: 'Selene Glow', synopsis: ''),
  (name: 'Selene Vesperis', synopsis: ''),
  (name: 'Seluna', synopsis: ''),
  (name: 'Selunara', synopsis: ''),
  (name: 'Selunaris', synopsis: ''),
  (name: 'Seranis', synopsis: ''),
  (name: 'Seraph', synopsis: ''),
  (name: 'Seraph Avaloria', synopsis: ''),
  (name: 'Seraph Novastra', synopsis: ''),
  (name: 'Seraph Orionis', synopsis: ''),
  (name: 'Serapheus', synopsis: ''),
  (name: 'Seraphic Alchemy', synopsis: ''),
  (name: 'Seraphic Blaze', synopsis: ''),
  (name: 'Seraphic Breeze', synopsis: ''),
  (name: 'Seraphic Cascade', synopsis: ''),
  (name: 'Seraphic Celestia', synopsis: ''),
  (name: 'Seraphic Echo', synopsis: ''),
  (name: 'Seraphic Eclipse', synopsis: ''),
  (name: 'Seraphic Ember', synopsis: ''),
  (name: 'Seraphic Harmonies', synopsis: ''),
  (name: 'Seraphic Luminara', synopsis: ''),
  (name: 'Seraphic Lyra', synopsis: ''),
  (name: 'Seraphic Nova', synopsis: ''),
  (name: 'Seraphic Radiance', synopsis: ''),
  (name: 'Seraphic Serenade', synopsis: ''),
  (name: 'Seraphic Solstice', synopsis: ''),
  (name: 'Seraphic Symphony', synopsis: ''),
  (name: 'Seraphic Twilight', synopsis: ''),
  (name: 'Seraphic Zephyrus', synopsis: ''),
  (name: 'Seraphina', synopsis: ''),
  (name: 'Seraphina Grace', synopsis: ''),
  (name: 'Seraphira', synopsis: ''),
  (name: 'Seraphis', synopsis: ''),
  (name: 'Serenara', synopsis: ''),
  (name: 'Serenaris', synopsis: ''),
  (name: 'Serene Aether', synopsis: ''),
  (name: 'Serene Bellatrix', synopsis: ''),
  (name: 'Serene Lyra', synopsis: ''),
  (name: 'Serene Seraphim', synopsis: ''),
  (name: 'Serene Solara', synopsis: ''),
  (name: 'Serene Solstice', synopsis: ''),
  (name: 'Serenith', synopsis: ''),
  (name: 'Serenity', synopsis: ''),
  (name: 'Serenity Astrala', synopsis: ''),
  (name: 'Serenity Aurora', synopsis: ''),
  (name: 'Serenity Grace', synopsis: ''),
  (name: 'Serenity Lunastra', synopsis: ''),
  (name: 'Serenity Lyra', synopsis: ''),
  (name: 'Serenity Nebulae', synopsis: ''),
  (name: 'Serenity Nebulon', synopsis: ''),
  (name: 'Sirius', synopsis: ''),
  (name: 'Sirius Lumina', synopsis: ''),
  (name: 'Solar Eclipse', synopsis: ''),
  (name: 'Solar Enchantment', synopsis: ''),
  (name: 'Solar Flame', synopsis: ''),
  (name: 'Solar Flare', synopsis: ''),
  (name: 'Solar Radiance', synopsis: ''),
  (name: 'Solar Sylph', synopsis: ''),
  (name: 'Solar Whisper', synopsis: ''),
  (name: 'Solara', synopsis: ''),
  (name: 'Solara Aether', synopsis: ''),
  (name: 'Solara Astralia', synopsis: ''),
  (name: 'Solara Aurora', synopsis: ''),
  (name: 'Solara Cascade', synopsis: ''),
  (name: 'Solara Celestria', synopsis: ''),
  (name: 'Solara Embrace', synopsis: ''),
  (name: 'Solara Enigma', synopsis: ''),
  (name: 'Solara Equinoxis', synopsis: ''),
  (name: 'Solara Halo', synopsis: ''),
  (name: 'Solara Harmonia', synopsis: ''),
  (name: 'Solara Light', synopsis: ''),
  (name: 'Solara Nebulae', synopsis: ''),
  (name: 'Solara Nebulon', synopsis: ''),
  (name: 'Solara Nova', synopsis: ''),
  (name: 'Solara Serenity', synopsis: ''),
  (name: 'Solara Stardust', synopsis: ''),
  (name: 'Solara Vortex', synopsis: ''),
  (name: 'Solara Whisper', synopsis: ''),
  (name: 'Solarastra', synopsis: ''),
  (name: 'Solariel', synopsis: ''),
  (name: 'Solarion', synopsis: ''),
  (name: 'Solaris', synopsis: ''),
  (name: 'Solaris Aether', synopsis: ''),
  (name: 'Solaris Blaze', synopsis: ''),
  (name: 'Solaris Borealis', synopsis: ''),
  (name: 'Solaris Breeze', synopsis: ''),
  (name: 'Solaris Dreamer', synopsis: ''),
  (name: 'Solaris Embrace', synopsis: ''),
  (name: 'Solaris Enigma', synopsis: ''),
  (name: 'Solaris Flame', synopsis: ''),
  (name: 'Solaris Harmonies', synopsis: ''),
  (name: 'Solaris Harmony', synopsis: ''),
  (name: 'Solaris Ignis', synopsis: ''),
  (name: 'Solaris Mirage', synopsis: ''),
  (name: 'Solaris Nebulous', synopsis: ''),
  (name: 'Solaris Nova', synopsis: ''),
  (name: 'Solaris Seraphim', synopsis: ''),
  (name: 'Solaris Serenade', synopsis: ''),
  (name: 'Solaris Solstice', synopsis: ''),
  (name: 'Solaris Symphony', synopsis: ''),
  (name: 'Solaris Twilight', synopsis: ''),
  (name: 'Solaris Veil', synopsis: ''),
  (name: 'Solaris Whisper', synopsis: ''),
  (name: 'Solarius', synopsis: ''),
  (name: 'Solarnova', synopsis: ''),
  (name: 'Solstaria', synopsis: ''),
  (name: 'Solstice', synopsis: ''),
  (name: 'Solstice Aria', synopsis: ''),
  (name: 'Solstice Aurora', synopsis: ''),
  (name: 'Solstice Blaze', synopsis: ''),
  (name: 'Solstice Cassiopra', synopsis: ''),
  (name: 'Solstice Celestia', synopsis: ''),
  (name: 'Solstice Echo', synopsis: ''),
  (name: 'Solstice Ember', synopsis: ''),
  (name: 'Solstice Luminary', synopsis: ''),
  (name: 'Solstice Luna', synopsis: ''),
  (name: 'Solstice Lunar', synopsis: ''),
  (name: 'Solstice Nova', synopsis: ''),
  (name: 'Solstice Phoenix', synopsis: ''),
  (name: 'Solstice Radiance', synopsis: ''),
  (name: 'Solstice Seraph', synopsis: ''),
  (name: 'Solstice Seraphim', synopsis: ''),
  (name: 'Solstice Serenade', synopsis: ''),
  (name: 'Solstice Sylph', synopsis: ''),
  (name: 'Solstice Zephyr', synopsis: ''),
  (name: 'Solsticea', synopsis: ''),
  (name: 'Solvenna', synopsis: ''),
  (name: 'Starborn Enchantment', synopsis: ''),
  (name: 'Starborn Flame', synopsis: ''),
  (name: 'Starborn Radiance', synopsis: ''),
  (name: 'Stardance', synopsis: ''),
  (name: 'Stardust', synopsis: ''),
  (name: 'Stardust Alchemy', synopsis: ''),
  (name: 'Stardust Aurora', synopsis: ''),
  (name: 'Stardust Blaze', synopsis: ''),
  (name: 'Stardust Breeze', synopsis: ''),
  (name: 'Stardust Cascade', synopsis: ''),
  (name: 'Stardust Celestia', synopsis: ''),
  (name: 'Stardust Dreamer', synopsis: ''),
  (name: 'Stardust Echo', synopsis: ''),
  (name: 'Stardust Ember', synopsis: ''),
  (name: 'Stardust Glow', synopsis: ''),
  (name: 'Stardust Harmonies', synopsis: ''),
  (name: 'Stardust Harmony', synopsis: ''),
  (name: 'Stardust Hydra', synopsis: ''),
  (name: 'Stardust Labyrinth', synopsis: ''),
  (name: 'Stardust Lullaby', synopsis: ''),
  (name: 'Stardust Luminary', synopsis: ''),
  (name: 'Stardust Lunar', synopsis: ''),
  (name: 'Stardust Lyrastra', synopsis: ''),
  (name: 'Stardust Mirage', synopsis: ''),
  (name: 'Stardust Nebulon', synopsis: ''),
  (name: 'Stardust Nebulus', synopsis: ''),
  (name: 'Stardust Nimbus', synopsis: ''),
  (name: 'Stardust Prism', synopsis: ''),
  (name: 'Stardust Radiance', synopsis: ''),
  (name: 'Stardust Reverie', synopsis: ''),
  (name: 'Stardust Seraph', synopsis: ''),
  (name: 'Stardust Seraphim', synopsis: ''),
  (name: 'Stardust Serenade', synopsis: ''),
  (name: 'Stardust Serenith', synopsis: ''),
  (name: 'Stardust Solstice', synopsis: ''),
  (name: 'Stardust Sonnet', synopsis: ''),
  (name: 'Stardust Stellaris', synopsis: ''),
  (name: 'Stardust Symphony', synopsis: ''),
  (name: 'Stardust Twilight', synopsis: ''),
  (name: 'Stardust Veil', synopsis: ''),
  (name: 'Stardust Whisper', synopsis: ''),
  (name: 'Stardust Whispers', synopsis: ''),
  (name: 'Stardust Zephyr', synopsis: ''),
  (name: 'Starfire Nova', synopsis: ''),
  (name: 'Starfire Symphony', synopsis: ''),
  (name: 'Starforge', synopsis: ''),
  (name: 'Stargazer Bliss', synopsis: ''),
  (name: 'Stargazer Breeze', synopsis: ''),
  (name: 'Stargazer Chorus', synopsis: ''),
  (name: 'Stargazer Dream', synopsis: ''),
  (name: 'Stargazer Serenade', synopsis: ''),
  (name: 'Stargazer Symphony', synopsis: ''),
  (name: 'Starlight Cascade', synopsis: ''),
  (name: 'Starlight Dreamscape', synopsis: ''),
  (name: 'Starlight Elixir', synopsis: ''),
  (name: 'Starlight Illusion', synopsis: ''),
  (name: 'Starlight Sonata', synopsis: ''),
  (name: 'Starlit Mirage', synopsis: ''),
  (name: 'Starlit Radiance', synopsis: ''),
  (name: 'Starlit Shimmer', synopsis: ''),
  (name: 'Starlit Symphony', synopsis: ''),
  (name: 'Stellar Aurora', synopsis: ''),
  (name: 'Stellar Blossom', synopsis: ''),
  (name: 'Stellar Breeze', synopsis: ''),
  (name: 'Stellar Cascade', synopsis: ''),
  (name: 'Stellar Dream', synopsis: ''),
  (name: 'Stellar Dreamer', synopsis: ''),
  (name: 'Stellar Dreamscape', synopsis: ''),
  (name: 'Stellar Eclipse', synopsis: ''),
  (name: 'Stellar Ember', synopsis: ''),
  (name: 'Stellar Enigma', synopsis: ''),
  (name: 'Stellar Essence', synopsis: ''),
  (name: 'Stellar Flare', synopsis: ''),
  (name: 'Stellar Glow', synopsis: ''),
  (name: 'Stellar Harmonies', synopsis: ''),
  (name: 'Stellar Harmony', synopsis: ''),
  (name: 'Stellar Lullaby', synopsis: ''),
  (name: 'Stellar Luminary', synopsis: ''),
  (name: 'Stellar Melody', synopsis: ''),
  (name: 'Stellar Nexus', synopsis: ''),
  (name: 'Stellar Nova', synopsis: ''),
  (name: 'Stellar Rhapsody', synopsis: ''),
  (name: 'Stellar Seraph', synopsis: ''),
  (name: 'Stellar Serenade', synopsis: ''),
  (name: 'Stellar Serenity', synopsis: ''),
  (name: 'Stellar Solstice', synopsis: ''),
  (name: 'Stellar Sylph', synopsis: ''),
  (name: 'Stellar Symphony', synopsis: ''),
  (name: 'Stellar Twilight', synopsis: ''),
  (name: 'Stellar Veil', synopsis: ''),
  (name: 'Stellar Whisper', synopsis: ''),
  (name: 'Stellar Zephyr', synopsis: ''),
  (name: 'Stellara Astralis', synopsis: ''),
  (name: 'Stellara Mist', synopsis: ''),
  (name: 'Stellara Solara', synopsis: ''),
  (name: 'Stellara Solstice', synopsis: ''),
  (name: 'Stellara Stardust', synopsis: ''),
  (name: 'Stellarion', synopsis: ''),
  (name: 'Stellaris', synopsis: ''),
  (name: 'Stellaris Nebulia', synopsis: ''),
  (name: 'Stellastra', synopsis: ''),
  (name: 'Stellastra Aquilaris', synopsis: ''),
  (name: 'Sylph', synopsis: ''),
  (name: 'Sylphic Mist', synopsis: ''),
  (name: 'Twilight', synopsis: ''),
  (name: 'Twilight Aurora', synopsis: ''),
  (name: 'Twilight Borealis', synopsis: ''),
  (name: 'Twilight Breeze', synopsis: ''),
  (name: 'Twilight Cascade', synopsis: ''),
  (name: 'Twilight Dream', synopsis: ''),
  (name: 'Twilight Ember', synopsis: ''),
  (name: 'Twilight Enigma', synopsis: ''),
  (name: 'Twilight Equinox', synopsis: ''),
  (name: 'Twilight Eternity', synopsis: ''),
  (name: 'Twilight Euphoria', synopsis: ''),
  (name: 'Twilight Flare', synopsis: ''),
  (name: 'Twilight Harmony', synopsis: ''),
  (name: 'Twilight Haven', synopsis: ''),
  (name: 'Twilight Haze', synopsis: ''),
  (name: 'Twilight Luminary', synopsis: ''),
  (name: 'Twilight Lyric', synopsis: ''),
  (name: 'Twilight Melody', synopsis: ''),
  (name: 'Twilight Mirage', synopsis: ''),
  (name: 'Twilight Mist', synopsis: ''),
  (name: 'Twilight Nebula', synopsis: ''),
  (name: 'Twilight Nebulae', synopsis: ''),
  (name: 'Twilight Nebulosity', synopsis: ''),
  (name: 'Twilight Nova', synopsis: ''),
  (name: 'Twilight Prism', synopsis: ''),
  (name: 'Twilight Radiance', synopsis: ''),
  (name: 'Twilight Reverie', synopsis: ''),
  (name: 'Twilight Seraph', synopsis: ''),
  (name: 'Twilight Serenade', synopsis: ''),
  (name: 'Twilight Shimmer', synopsis: ''),
  (name: 'Twilight Solara', synopsis: ''),
  (name: 'Twilight Solstice', synopsis: ''),
  (name: 'Twilight Sonata', synopsis: ''),
  (name: 'Twilight Sparkle', synopsis: ''),
  (name: 'Twilight Stardust', synopsis: ''),
  (name: 'Twilight Sylph', synopsis: ''),
  (name: 'Twilight Symphony', synopsis: ''),
  (name: 'Twilight Veil', synopsis: ''),
  (name: 'Twilight Whisper', synopsis: ''),
  (name: 'Twilight Zephyr', synopsis: ''),
  (name: 'Vega', synopsis: ''),
  (name: 'Vega Luster', synopsis: ''),
  (name: 'Vega Sparkle', synopsis: ''),
  (name: 'Vesper', synopsis: ''),
  (name: 'Vesperia', synopsis: ''),
  (name: 'Vesperion', synopsis: ''),
  (name: 'Vesperis', synopsis: ''),
  (name: 'Vesperis Serenith', synopsis: ''),
  (name: 'Zenith', synopsis: ''),
  (name: 'Zenith Glow', synopsis: ''),
  (name: 'Zenithra', synopsis: ''),
  (name: 'Zenithria', synopsis: ''),
  (name: 'Zephyr', synopsis: ''),
  (name: 'Zephyr Avaloria', synopsis: ''),
  (name: 'Zephyr Breath', synopsis: ''),
  (name: 'Zephyr Cascade', synopsis: ''),
  (name: 'Zephyr Dreamscape', synopsis: ''),
  (name: 'Zephyr Embrace', synopsis: ''),
  (name: 'Zephyr Harmony', synopsis: ''),
  (name: 'Zephyr Luminary', synopsis: ''),
  (name: 'Zephyr Nebula', synopsis: ''),
  (name: 'Zephyr Nebulae', synopsis: ''),
  (name: 'Zephyr Nova', synopsis: ''),
  (name: 'Zephyr Orionis', synopsis: ''),
  (name: 'Zephyr Pyrastra', synopsis: ''),
  (name: 'Zephyr Radiance', synopsis: ''),
  (name: 'Zephyr Seraph', synopsis: ''),
  (name: 'Zephyr Serenade', synopsis: ''),
  (name: 'Zephyr Solara', synopsis: ''),
  (name: 'Zephyr Song', synopsis: ''),
  (name: 'Zephyra', synopsis: ''),
  (name: 'Zephyrana', synopsis: ''),
  (name: 'Zephyrella', synopsis: ''),
  (name: 'Zephyrella Nebulia', synopsis: ''),
  (name: 'Zephyrena', synopsis: ''),
  (name: 'Zephyria', synopsis: ''),
  (name: 'Zephyria Whispers', synopsis: ''),
  (name: 'Zephyrian', synopsis: ''),
  (name: 'Zephyris', synopsis: ''),
  (name: 'Zephyrith', synopsis: ''),
  (name: 'Zephyrus', synopsis: ''),
  (name: 'Zephyrus Aurora', synopsis: ''),
  (name: 'Zephyrus Auroria', synopsis: ''),
  (name: 'Zephyrus Prism', synopsis: ''),
  (name: 'Zephyrus Solsticea', synopsis: ''),
  (name: 'Zephyrus Whirl', synopsis: ''),
  (name: 'Zodiac Hydra', synopsis: ''),
  (name: 'Zodiac Serenity', synopsis: ''),
  (name: 'Zodiac Solstice', synopsis: ''),
  (name: 'Zodiac Stardust', synopsis: ''),
  (name: 'Zodiac Zephyr', synopsis: ''),
};
