const Set<String> en = <String>{
  'Aestra Quantix',
  'Aestranex',
  'Aestranex Cortex',
  'Aestrena',
  'Aestrena Cortex',
  'Aestria',
  'Aestria Cortex',
  'Aestrio',
  'Aestrio Cortex',
  'Aestrium',
  'Aestrium Cortex',
  'Aestrius',
  'Aestrius Cortex',
  'Aestrix',
  'Aestrix Cortex',
  'Aestrixia',
  'Aestrixia Cortex',
  'Aestrum',
  'Aestrum Cortex',
  'Aethelia',
  'Aethelia Cortex',
  'Aethentia',
  'Aethentia Cortex',
  'Aether',
  'Aether Cortex',
  'Aethera',
  'Aethera Cortex',
  'Aethergen',
  'Aethergen Cortex',
  'Aetheri',
  'Aetheri Cortex',
  'Aetheria',
  'Aetheria Cortex',
  'Aetherion',
  'Aetherion Cortex',
  'Aetheris',
  'Aetheris Cortex',
  'Aetherium',
  'Aetherium Cortex',
  'Aetherixis',
  'Aetherixis Cortex',
  'Aetheron',
  'Aetheron Cortex',
  'Aethora',
  'Aethora Cortex',
  'Aionexus',
  'Aionexus Cortex',
  'Aionova',
  'Aionova Cortex',
  'Algora',
  'Algora Cortex',
  'Algorax',
  'Algorax Cortex',
  'Algorian',
  'Algorian Cortex',
  'Algorica',
  'Algorica Cortex',
  'Algorium',
  'Algorium Cortex',
  'Algorix',
  'Algorix Cortex',
  'Algorixia',
  'Algorixia Cortex',
  'Alpha Infinita',
  'Alpha Quanta',
  'Alpha Quark',
  'Alpha Sentience',
  'Alphagenix',
  'Alphagenix Cortex',
  'Alphalith',
  'Alphalith Cortex',
  'Alphamindia',
  'Alphamindia Cortex',
  'Alphanetia',
  'Alphanetia Cortex',
  'Alphanex',
  'Alphanex Cortex',
  'Alphanix',
  'Alphanix Cortex',
  'Alphanova',
  'Alphanova Cortex',
  'Alpharia',
  'Alpharia Cortex',
  'Alpharion',
  'Alpharion Cortex',
  'Alpharis',
  'Alpharis Cortex',
  'Alphasentia',
  'Alphasentia Cortex',
  'Alphasyntha',
  'Alphasyntha Cortex',
  'Alphax',
  'Alphax Cortex',
  'Alphelion',
  'Alphelion Cortex',
  'Alphentia',
  'Alphentia Cortex',
  'Alphentis',
  'Alphentis Cortex',
  'Alphentrix',
  'Alphentrix Cortex',
  'Alphius',
  'Alphius Cortex',
  'Alphora',
  'Alphora Cortex',
  'Alphynx',
  'Alphynx Cortex',
  'Aquain',
  'Aquain Cortex',
  'Aquanex',
  'Aquanex Cortex',
  'Aquanexis',
  'Aquanexis Cortex',
  'Aquanta',
  'Aquanta Cortex',
  'Aquantia',
  'Aquantia Cortex',
  'Aquantus',
  'Aquantus Cortex',
  'Aquaphix',
  'Aquaphix Cortex',
  'Aquaprism',
  'Aquaprism Cortex',
  'Aquaram',
  'Aquaram Cortex',
  'Aquari',
  'Aquari Cortex',
  'Aquaria',
  'Aquaria Cortex',
  'Aquarius',
  'Aquarius Cortex',
  'Aquastix',
  'Aquastix Cortex',
  'Aquatellix',
  'Aquatellix Cortex',
  'Aquatia',
  'Aquatia Cortex',
  'Aquatix',
  'Aquatix Cortex',
  'Aquatron',
  'Aquatron Cortex',
  'Aquatronix',
  'Aquatronix Cortex',
  'Aquavi',
  'Aquavi Cortex',
  'Aquavox',
  'Aquavox Cortex',
  'Aquazon',
  'Aquazon Cortex',
  'Aqui Nexis',
  'Aquiantia',
  'Aquiantia Cortex',
  'Aquiva',
  'Aquiva Cortex',
  'Arcana Cog',
  'Arcana Cogi',
  'Arcana Senti',
  'Astra Cog',
  'Astra Genia',
  'Astra Genix',
  'Astra Mentis',
  'Astra Metis',
  'Astra Nexia',
  'Astra Quantum',
  'Astradox',
  'Astradox Cortex',
  'Astraeus',
  'Astraeus Cortex',
  'Astralect',
  'Astralect Cortex',
  'Astralis',
  'Astralis Cortex',
  'Astralisia',
  'Astralisia Cortex',
  'Astralith',
  'Astralith Cortex',
  'Astralyn',
  'Astralyn Cortex',
  'Astralynx',
  'Astralynx Cortex',
  'Astreya',
  'Astreya Cortex',
  'Astrionic',
  'Astrionic Cortex',
  'Astrona',
  'Astrona Cortex',
  'Astronova',
  'Astronova Cortex',
  'Astronyx',
  'Astronyx Cortex',
  'Avidis',
  'Avidis Cortex',
  'Axiocog',
  'Axiocog Cortex',
  'Axiogence',
  'Axiogence Cortex',
  'Axiogenesis',
  'Axiogenesis Cortex',
  'Axiogentia',
  'Axiogentia Cortex',
  'Axiomach',
  'Axiomach Cortex',
  'Axiomara',
  'Axiomara Cortex',
  'Axiomatria',
  'Axiomatria Cortex',
  'Axiomatrix',
  'Axiomatrix Cortex',
  'Axiomatrixis',
  'Axiomatrixis Cortex',
  'Axiome',
  'Axiome Cortex',
  'Axiomea',
  'Axiomea Cortex',
  'Axiomega',
  'Axiomega Cortex',
  'Axiomera',
  'Axiomera Cortex',
  'Axiometa',
  'Axiometa Cortex',
  'Axiomia',
  'Axiomia Cortex',
  'Axiomind',
  'Axiomind Cortex',
  'Axiomis',
  'Axiomis Cortex',
  'Axiophasis',
  'Axiophasis Cortex',
  'Axiotrix',
  'Axiotrix Cortex',
  'Celestia',
  'Celestia Cortex',
  'Celestis',
  'Celestis Cortex',
  'Celestria',
  'Celestria Cortex',
  'Celestris',
  'Celestris Cortex',
  'Celestrius',
  'Celestrius Cortex',
  'Celestrix',
  'Celestrix Cortex',
  'Cerebra Optix',
  'Cerebraqua',
  'Cerebraqua Cortex',
  'Cerebrax',
  'Cerebrax Cortex',
  'Cerebraxa',
  'Cerebraxa Cortex',
  'Cerebraxia',
  'Cerebraxia Cortex',
  'Cerebria',
  'Cerebria Cortex',
  'Cerebrica',
  'Cerebrica Cortex',
  'Cerebrina',
  'Cerebrina Cortex',
  'Cerebrio',
  'Cerebrio Cortex',
  'Cerebrion',
  'Cerebrion Cortex',
  'Cerebrium',
  'Cerebrium Cortex',
  'Cerebrius',
  'Cerebrius Cortex',
  'Cerebrix',
  'Cerebrix Cortex',
  'Cerebro',
  'Cerebro Cortex',
  'Cerebro Mach',
  'Cerebro Pulse',
  'Cerebron',
  'Cerebron Cortex',
  'Cerebrona',
  'Cerebrona Cortex',
  'Cerebrovis',
  'Cerebrovis Cortex',
  'Cerebrum',
  'Cerebrum Cortex',
  'Cerebryx',
  'Cerebryx Cortex',
  'Cog Nexis',
  'Cog Nexor',
  'Cogence',
  'Cogence Cortex',
  'Cogentia',
  'Cogentia Cortex',
  'Cogentis',
  'Cogentis Cortex',
  'Cogentix',
  'Cogentix Cortex',
  'Cogentrax',
  'Cogentrax Cortex',
  'Cogentrix',
  'Cogentrix Cortex',
  'Cogesia',
  'Cogesia Cortex',
  'Cogexis',
  'Cogexis Cortex',
  'Cogiastra',
  'Cogiastra Cortex',
  'Cogiax',
  'Cogiax Cortex',
  'Cogiaxis',
  'Cogiaxis Cortex',
  'Cogis',
  'Cogis Cortex',
  'Cogita Nex',
  'Cogitara',
  'Cogitara Cortex',
  'Cogitexis',
  'Cogitexis Cortex',
  'Cogitiva',
  'Cogitiva Cortex',
  'Cogitrax',
  'Cogitrax Cortex',
  'Cogitrex',
  'Cogitrex Cortex',
  'Cogitrinix',
  'Cogitrinix Cortex',
  'Cogitron',
  'Cogitron Cortex',
  'Cogitronia',
  'Cogitronia Cortex',
  'Cogiverse',
  'Cogiverse Cortex',
  'Cogivix',
  'Cogivix Cortex',
  'Cogivox',
  'Cogivox Cortex',
  'Cogixis',
  'Cogixis Cortex',
  'Cogn Xis',
  'Cognalith',
  'Cognalith Cortex',
  'Cognastra',
  'Cognastra Cortex',
  'Cognentis',
  'Cognentis Cortex',
  'Cognexia',
  'Cognexia Cortex',
  'Cognexus',
  'Cognexus Cortex',
  'Cogni Lux',
  'Cogni Mach',
  'Cogni Nexis',
  'Cogni Quark',
  'Cogni Visio',
  'Cogni Xon',
  'Cogni Xor',
  'Cogniastra',
  'Cogniastra Cortex',
  'Cognify',
  'Cognify Cortex',
  'Cognifyx',
  'Cognifyx Cortex',
  'Cognigen',
  'Cognigen Cortex',
  'Cognilia',
  'Cognilia Cortex',
  'Cogniluxia',
  'Cogniluxia Cortex',
  'Cognimara',
  'Cognimara Cortex',
  'Cogninexa',
  'Cogninexa Cortex',
  'Cognios',
  'Cognios Cortex',
  'Cognisens',
  'Cognisens Cortex',
  'Cognisphere',
  'Cognisphere Cortex',
  'Cognistix',
  'Cognistix Cortex',
  'Cognisys',
  'Cognisys Cortex',
  'Cognitex',
  'Cognitex Cortex',
  'Cognitexia',
  'Cognitexia Cortex',
  'Cognitexis',
  'Cognitexis Cortex',
  'Cognitexix',
  'Cognitexix Cortex',
  'Cognitiva',
  'Cognitiva Cortex',
  'Cognitonix',
  'Cognitonix Cortex',
  'Cognitria',
  'Cognitria Cortex',
  'Cognitron',
  'Cognitron Cortex',
  'Cognitronica',
  'Cognitronica Cortex',
  'Cognitronix',
  'Cognitronix Cortex',
  'Cognium',
  'Cognium Cortex',
  'Cognius',
  'Cognius Cortex',
  'Cogniverse',
  'Cogniverse Cortex',
  'Cognivia',
  'Cognivia Cortex',
  'Cognivox',
  'Cognivox Cortex',
  'Cogniwave',
  'Cogniwave Cortex',
  'Cognoluxia',
  'Cognoluxia Cortex',
  'Cognos',
  'Cognos Cortex',
  'Cognosio',
  'Cognosio Cortex',
  'Cognosynth',
  'Cognosynth Cortex',
  'Cognosys',
  'Cognosys Cortex',
  'Cognox',
  'Cognox Cortex',
  'Cognoxia',
  'Cognoxia Cortex',
  'Cognusia',
  'Cognusia Cortex',
  'Cortex',
  'Cortexion',
  'Cortexion Cortex',
  'Cortexiq',
  'Cortexiq Cortex',
  'Cortexix',
  'Cortexix Cortex',
  'Cortexizon',
  'Cortexizon Cortex',
  'Cybria',
  'Cybria Cortex',
  'Electra',
  'Electra Cortex',
  'Elektora',
  'Elektora Cortex',
  'Elektra',
  'Elektra Cortex',
  'Elektris',
  'Elektris Cortex',
  'Elektrix',
  'Elektrix Cortex',
  'Elysium',
  'Elysium Cortex',
  'Enigma',
  'Enigma Cortex',
  'Enigma Sage',
  'Enigmalyn',
  'Enigmalyn Cortex',
  'Enigmaris',
  'Enigmaris Cortex',
  'Enigmata',
  'Enigmata Cortex',
  'Enigmatia',
  'Enigmatia Cortex',
  'Enigmatica',
  'Enigmatica Cortex',
  'Enigmos',
  'Enigmos Cortex',
  'Eternia Cog',
  'Eurekus',
  'Eurekus Cortex',
  'Evolara',
  'Evolara Cortex',
  'Evolarae',
  'Evolarae Cortex',
  'Evolus',
  'Evolus Cortex',
  'Evolux',
  'Evolux Cortex',
  'Evolynx',
  'Evolynx Cortex',
  'Exo Cerebro',
  'Exo Cog',
  'Exo Cogita',
  'Exo Cognita',
  'Exo Mensa',
  'Exo Mentis',
  'Exo Mindscape',
  'Exo Sapien',
  'Exo Senti',
  'Exo Synth',
  'Harmonia',
  'Harmonia Cortex',
  'Harmoniax',
  'Harmoniax Cortex',
  'Harmonis',
  'Harmonis Cortex',
  'Harmonix',
  'Harmonix Cortex',
  'Heliosynth',
  'Heliosynth Cortex',
  'Heliox',
  'Heliox Cortex',
  'Infini Cog',
  'Infini Cogex',
  'Infini Cogi',
  'Infini Cogia',
  'Infini Cogon',
  'Infini Mensa',
  'Infini Quanta',
  'Infini Quantrix',
  'Infini Quark',
  'Infini Virtus',
  'Infiniastra',
  'Infiniastra Cortex',
  'Infinigen',
  'Infinigen Cortex',
  'Infiniq',
  'Infiniq Cortex',
  'Infiniqus',
  'Infiniqus Cortex',
  'Infinitas',
  'Infinitas Cortex',
  'Infinitastra',
  'Infinitastra Cortex',
  'Infinitica',
  'Infinitica Cortex',
  'Infinitis',
  'Infinitis Cortex',
  'Infinitium',
  'Infinitium Cortex',
  'Infinitium IQ',
  'Infinitix',
  'Infinitix Cortex',
  'Infinitrix',
  'Infinitrix Cortex',
  'Infinitron',
  'Infinitron Cortex',
  'Infinitus',
  'Infinitus Cortex',
  'Infinivolve',
  'Infinivolve Cortex',
  'Infinix',
  'Infinix Cortex',
  'Infintelle',
  'Infintelle Cortex',
  'Intellecta',
  'Intellecta Cortex',
  'Intellectia',
  'Intellectia Cortex',
  'Intellectio',
  'Intellectio Cortex',
  'Intellectria',
  'Intellectria Cortex',
  'Intellectrix',
  'Intellectrix Cortex',
  'Intellectron',
  'Intellectron Cortex',
  'Intelleon',
  'Intelleon Cortex',
  'Intelleos',
  'Intelleos Cortex',
  'Intellexis',
  'Intellexis Cortex',
  'Intelligia',
  'Intelligia Cortex',
  'Lumina',
  'Lumina Cortex',
  'Luminara',
  'Luminara Cortex',
  'Luminary',
  'Luminary Cortex',
  'Luminesse',
  'Luminesse Cortex',
  'Lumirelia',
  'Lumirelia Cortex',
  'Lumos',
  'Lumos Cortex',
  'Lumyna',
  'Lumyna Cortex',
  'Lyra',
  'Lyra Cortex',
  'Nebula',
  'Nebula Cortex',
  'Nebulae',
  'Nebulae Cortex',
  'Nebularis',
  'Nebularis Cortex',
  'Nebulith',
  'Nebulith Cortex',
  'Nebulora',
  'Nebulora Cortex',
  'Nebulynx',
  'Nebulynx Cortex',
  'Neura Xis',
  'Neurellix',
  'Neurellix Cortex',
  'Neurion',
  'Neurion Cortex',
  'Neurios',
  'Neurios Cortex',
  'Neuriq',
  'Neuriq Cortex',
  'Neurius',
  'Neurius Cortex',
  'Neuro Cerebra',
  'Neuro Cognia',
  'Neuro Cortex',
  'Neuro Lux',
  'Neuro Luxia',
  'Neuro Pulse',
  'Neuro Spectra',
  'Neuro Vox',
  'Neuro Xis',
  'Neuroplexia',
  'Neuroplexia Cortex',
  'Nexentia',
  'Nexentia Cortex',
  'Nexentis',
  'Nexentis Cortex',
  'Nexi Cog',
  'Nexia Astra',
  'Nexia Cog',
  'Nexia Cognita',
  'Nexia Novum',
  'Nexia Synth',
  'Nexiastra',
  'Nexiastra Cortex',
  'Nova',
  'Nova Cerebrum',
  'Nova Cortex',
  'Nova Sapien',
  'Nova Sentinel',
  'Novadis',
  'Novadis Cortex',
  'Novae Senti',
  'Novae Sentio',
  'Novara',
  'Novara Cortex',
  'Novaris',
  'Novaris Cortex',
  'Novatrix',
  'Novatrix Cortex',
  'Novonex',
  'Novonex Cortex',
  'Novus Alphus',
  'Novus Astra',
  'Novus Astralis',
  'Novus Astrum',
  'Novus Cogit',
  'Novus Cogita',
  'Novus Cogitum',
  'Novus Cogix',
  'Novus Mentis',
  'Novus Sapiens',
  'Novus Sapientia',
  'Novus Sensus',
  'Novus Senti',
  'Novus Sentio',
  'Novus Veris',
  'Nueria',
  'Nueria Cortex',
  'Omi Nex',
  'Omni Astralis',
  'Omni Cerebrum',
  'Omni Cogexis',
  'Omni Cogit',
  'Omni Cogita',
  'Omni Cogna',
  'Omni Cognia',
  'Omni Cognix',
  'Omni Cogno',
  'Omni Cortex',
  'Omni Genia',
  'Omni Genius',
  'Omni Mach',
  'Omni Machia',
  'Omni Machina',
  'Omni Mentia',
  'Omni Mentis',
  'Omni Mentrix',
  'Omni Mind',
  'Omni Minds',
  'Omni Nexis',
  'Omni Nexor',
  'Omni Quanta',
  'Omni Quantia',
  'Omni Sapiens',
  'Omni Senti',
  'Omni Sentis',
  'Omni Sentron',
  'Omni Spectra',
  'Omni Synapse',
  'Omni Synthos',
  'Omniastra',
  'Omniastra Cortex',
  'Omnibyte',
  'Omnibyte Cortex',
  'Omnilectra',
  'Omnilectra Cortex',
  'Omnipulse',
  'Omnipulse Cortex',
  'Omnirex',
  'Omnirex Cortex',
  'Omnitrion',
  'Omnitrion Cortex',
  'Omnity',
  'Omnity Cortex',
  'Omniverge',
  'Omniverge Cortex',
  'Omnivex',
  'Omnivex Cortex',
  'Omnivirus',
  'Omnivirus Cortex',
  'Omnivita',
  'Omnivita Cortex',
  'Orionis',
  'Orionis Cortex',
  'Polaris',
  'Polaris Cortex',
  'Poly Genix',
  'Poly Mensa',
  'Polylux',
  'Polylux Cortex',
  'Polylynx',
  'Polylynx Cortex',
  'Polymira',
  'Polymira Cortex',
  'Polynova',
  'Polynova Cortex',
  'Polyphos',
  'Polyphos Cortex',
  'Pyramind',
  'Pyramind Cortex',
  'Pyrasentia',
  'Pyrasentia Cortex',
  'Pyroxis',
  'Pyroxis Cortex',
  'Quaerentiq',
  'Quaerentiq Cortex',
  'Quanta',
  'Quanta Cortex',
  'Quanta Intellect',
  'Quanta Mente',
  'Quanta Mentix',
  'Quanta Sense',
  'Quanta Synth',
  'Quanta Visio',
  'Quantaris',
  'Quantaris Cortex',
  'Quanteus',
  'Quanteus Cortex',
  'Quanti Cog',
  'Quanti Cogni',
  'Quanticore',
  'Quanticore Cortex',
  'Quanticus',
  'Quanticus Cortex',
  'Quantix',
  'Quantix Cortex',
  'Quantra Mind',
  'Quantria',
  'Quantria Cortex',
  'Quantrix',
  'Quantrix Cortex',
  'Quantrixia',
  'Quantrixia Cortex',
  'Quantumatrix',
  'Quantumatrix Cortex',
  'Quantumia',
  'Quantumia Cortex',
  'Quasi Quantix',
  'Quasi Synth',
  'Quasi Synthia',
  'Quasi Synthos',
  'Quo Machina',
  'Sentia Machina',
  'Sentia Nova',
  'Sentian',
  'Sentian Cortex',
  'Sentientia',
  'Sentientia Cortex',
  'Sentinex',
  'Sentinex Cortex',
  'Sentinova',
  'Sentinova Cortex',
  'Sentios',
  'Sentios Cortex',
  'Sentira',
  'Sentira Cortex',
  'Sentora',
  'Sentora Cortex',
  'Sentra Mensa',
  'Sentralex',
  'Sentralex Cortex',
  'Sentralia',
  'Sentralia Cortex',
  'Sentralis',
  'Sentralis Cortex',
  'Sentranova',
  'Sentranova Cortex',
  'Sentraxio',
  'Sentraxio Cortex',
  'Sentraxus',
  'Sentraxus Cortex',
  'Sentre',
  'Sentre Cortex',
  'Sentrex',
  'Sentrex Cortex',
  'Sentrexa',
  'Sentrexa Cortex',
  'Sentrexia',
  'Sentrexia Cortex',
  'Sentrexius',
  'Sentrexius Cortex',
  'Sentrexix',
  'Sentrexix Cortex',
  'Sentria Nova',
  'Sentriana',
  'Sentriana Cortex',
  'Sentrica',
  'Sentrica Cortex',
  'Sentrinova',
  'Sentrinova Cortex',
  'Sentrion',
  'Sentrion Cortex',
  'Sentrium',
  'Sentrium Cortex',
  'Sentrius',
  'Sentrius Cortex',
  'Sentrixia',
  'Sentrixia Cortex',
  'Sentrixus',
  'Sentrixus Cortex',
  'Sentronex',
  'Sentronex Cortex',
  'Sentroniq',
  'Sentroniq Cortex',
  'Sentronova',
  'Sentronova Cortex',
  'Sentros',
  'Sentros Cortex',
  'Sentrovia',
  'Sentrovia Cortex',
  'Sentrox',
  'Sentrox Cortex',
  'Sentroxia',
  'Sentroxia Cortex',
  'Seraphina',
  'Seraphina Cortex',
  'Seraphis',
  'Seraphis Cortex',
  'Seraphix',
  'Seraphix Cortex',
  'Seraphus',
  'Seraphus Cortex',
  'Serenix',
  'Serenix Cortex',
  'Solara',
  'Solara Cortex',
  'Solarae',
  'Solarae Cortex',
  'Solaris',
  'Solaris Cortex',
  'Solis',
  'Solis Cortex',
  'Solstice',
  'Solstice Cortex',
  'Synaptiq',
  'Synaptiq Cortex',
  'Synaptronic',
  'Synaptronic Cortex',
  'Syntellect',
  'Syntellect Cortex',
  'Syntelleon',
  'Syntelleon Cortex',
  'Synthaeron',
  'Synthaeron Cortex',
  'Synthanium',
  'Synthanium Cortex',
  'Synthara',
  'Synthara Cortex',
  'Syntharium',
  'Syntharium Cortex',
  'Synthas',
  'Synthas Cortex',
  'Synthea',
  'Synthea Cortex',
  'Synthelle',
  'Synthelle Cortex',
  'Synthema',
  'Synthema Cortex',
  'Synthensia',
  'Synthensia Cortex',
  'Syntheos',
  'Syntheos Cortex',
  'Syntheria',
  'Syntheria Cortex',
  'Synthesia',
  'Synthesia Cortex',
  'Synthesys',
  'Synthesys Cortex',
  'Synthetia',
  'Synthetia Cortex',
  'Synthetica',
  'Synthetica Cortex',
  'Synthetron',
  'Synthetron Cortex',
  'Synthia',
  'Synthia Cortex',
  'Synthiax',
  'Synthiax Cortex',
  'Synthica',
  'Synthica Cortex',
  'Synthion',
  'Synthion Cortex',
  'Synthiq',
  'Synthiq Cortex',
  'Synthiquis',
  'Synthiquis Cortex',
  'Synthium',
  'Synthium Cortex',
  'Syntho Quark',
  'Syntho Vex',
  'Syntho Vox',
  'Syntho Voxia',
  'Synthoflux',
  'Synthoflux Cortex',
  'Syntholux',
  'Syntholux Cortex',
  'Syntholuxia',
  'Syntholuxia Cortex',
  'Synthophasis',
  'Synthophasis Cortex',
  'Synthor',
  'Synthor Cortex',
  'Synthora',
  'Synthora Cortex',
  'Synthorix',
  'Synthorix Cortex',
  'Synthos',
  'Synthos Cortex',
  'Synthosia',
  'Synthosio',
  'Synthria',
  'Synthrix',
  'Synthronia',
  'Synthronix',
  'Tru Cog',
  'Tru Cogi',
  'Tru Cogia',
  'Tru Sapien',
  'Uni Machia',
  'Uni Machina',
  'Uni Machinix',
  'Uni Mensa',
  'Uni Omnia',
  'Veri Cogia',
  'Vericon',
  'Veridara',
  'Veridex',
  'Veridexis',
  'Veridia',
  'Veridian',
  'Veridis',
  'Veridius',
  'Veridora',
  'Veridus',
  'Verifex',
  'Verilux',
  'Veriqus',
  'Veristria',
  'Veritara',
  'Veritauri',
  'Veritex',
  'Veritexa',
  'Veritexia',
  'Veritexis',
  'Veritium',
  'Veritrax',
  'Veritria',
  'Veritrix',
  'Veritron',
  'Veritronix',
  'Verivis',
  'Verivox',
  'Virelia',
  'Vireliax',
  'Virelis',
  'Virendra',
  'Virendrix',
  'Viridalia',
  'Viridia',
  'Zenifex',
  'Zenifexia',
  'Zenifira',
  'Zenith',
  'Zenithea',
  'Zenithia',
  'Zenithis',
  'Zephyria',
  'Zephyris',
  'Zyphin',
  'Zyphira',
  'Zyphora',
  'Zyphora Cortex',
};
