import '../name_r.dart';

const Set<NameR> en = {
  (title: 'Aestra Quantix', synopsis: ''),
  (title: 'Aestranex', synopsis: ''),
  (title: 'Aestranex Cortex', synopsis: ''),
  (title: 'Aestrena', synopsis: ''),
  (title: 'Aestrena Cortex', synopsis: ''),
  (title: 'Aestria', synopsis: ''),
  (title: 'Aestria Cortex', synopsis: ''),
  (title: 'Aestrio', synopsis: ''),
  (title: 'Aestrio Cortex', synopsis: ''),
  (title: 'Aestrium', synopsis: ''),
  (title: 'Aestrium Cortex', synopsis: ''),
  (title: 'Aestrius', synopsis: ''),
  (title: 'Aestrius Cortex', synopsis: ''),
  (title: 'Aestrix', synopsis: ''),
  (title: 'Aestrix Cortex', synopsis: ''),
  (title: 'Aestrixia', synopsis: ''),
  (title: 'Aestrixia Cortex', synopsis: ''),
  (title: 'Aestrum', synopsis: ''),
  (title: 'Aestrum Cortex', synopsis: ''),
  (title: 'Aethelia', synopsis: ''),
  (title: 'Aethelia Cortex', synopsis: ''),
  (title: 'Aethentia', synopsis: ''),
  (title: 'Aethentia Cortex', synopsis: ''),
  (title: 'Aether', synopsis: ''),
  (title: 'Aether Cortex', synopsis: ''),
  (title: 'Aethera', synopsis: ''),
  (title: 'Aethera Cortex', synopsis: ''),
  (title: 'Aethergen', synopsis: ''),
  (title: 'Aethergen Cortex', synopsis: ''),
  (title: 'Aetheri', synopsis: ''),
  (title: 'Aetheri Cortex', synopsis: ''),
  (title: 'Aetheria', synopsis: ''),
  (title: 'Aetheria Cortex', synopsis: ''),
  (title: 'Aetherion', synopsis: ''),
  (title: 'Aetherion Cortex', synopsis: ''),
  (title: 'Aetheris', synopsis: ''),
  (title: 'Aetheris Cortex', synopsis: ''),
  (title: 'Aetherium', synopsis: ''),
  (title: 'Aetherium Cortex', synopsis: ''),
  (title: 'Aetherixis', synopsis: ''),
  (title: 'Aetherixis Cortex', synopsis: ''),
  (title: 'Aetheron', synopsis: ''),
  (title: 'Aetheron Cortex', synopsis: ''),
  (title: 'Aethora', synopsis: ''),
  (title: 'Aethora Cortex', synopsis: ''),
  (title: 'Aionexus', synopsis: ''),
  (title: 'Aionexus Cortex', synopsis: ''),
  (title: 'Aionova', synopsis: ''),
  (title: 'Aionova Cortex', synopsis: ''),
  (title: 'Algora', synopsis: ''),
  (title: 'Algora Cortex', synopsis: ''),
  (title: 'Algorax', synopsis: ''),
  (title: 'Algorax Cortex', synopsis: ''),
  (title: 'Algorian', synopsis: ''),
  (title: 'Algorian Cortex', synopsis: ''),
  (title: 'Algorica', synopsis: ''),
  (title: 'Algorica Cortex', synopsis: ''),
  (title: 'Algorium', synopsis: ''),
  (title: 'Algorium Cortex', synopsis: ''),
  (title: 'Algorix', synopsis: ''),
  (title: 'Algorix Cortex', synopsis: ''),
  (title: 'Algorixia', synopsis: ''),
  (title: 'Algorixia Cortex', synopsis: ''),
  (title: 'Alpha Infinita', synopsis: ''),
  (title: 'Alpha Quanta', synopsis: ''),
  (title: 'Alpha Quark', synopsis: ''),
  (title: 'Alpha Sentience', synopsis: ''),
  (title: 'Alphagenix', synopsis: ''),
  (title: 'Alphagenix Cortex', synopsis: ''),
  (title: 'Alphalith', synopsis: ''),
  (title: 'Alphalith Cortex', synopsis: ''),
  (title: 'Alphamindia', synopsis: ''),
  (title: 'Alphamindia Cortex', synopsis: ''),
  (title: 'Alphanetia', synopsis: ''),
  (title: 'Alphanetia Cortex', synopsis: ''),
  (title: 'Alphanex', synopsis: ''),
  (title: 'Alphanex Cortex', synopsis: ''),
  (title: 'Alphanix', synopsis: ''),
  (title: 'Alphanix Cortex', synopsis: ''),
  (title: 'Alphanova', synopsis: ''),
  (title: 'Alphanova Cortex', synopsis: ''),
  (title: 'Alpharia', synopsis: ''),
  (title: 'Alpharia Cortex', synopsis: ''),
  (title: 'Alpharion', synopsis: ''),
  (title: 'Alpharion Cortex', synopsis: ''),
  (title: 'Alpharis', synopsis: ''),
  (title: 'Alpharis Cortex', synopsis: ''),
  (title: 'Alphasentia', synopsis: ''),
  (title: 'Alphasentia Cortex', synopsis: ''),
  (title: 'Alphasyntha', synopsis: ''),
  (title: 'Alphasyntha Cortex', synopsis: ''),
  (title: 'Alphax', synopsis: ''),
  (title: 'Alphax Cortex', synopsis: ''),
  (title: 'Alphelion', synopsis: ''),
  (title: 'Alphelion Cortex', synopsis: ''),
  (title: 'Alphentia', synopsis: ''),
  (title: 'Alphentia Cortex', synopsis: ''),
  (title: 'Alphentis', synopsis: ''),
  (title: 'Alphentis Cortex', synopsis: ''),
  (title: 'Alphentrix', synopsis: ''),
  (title: 'Alphentrix Cortex', synopsis: ''),
  (title: 'Alphius', synopsis: ''),
  (title: 'Alphius Cortex', synopsis: ''),
  (title: 'Alphora', synopsis: ''),
  (title: 'Alphora Cortex', synopsis: ''),
  (title: 'Alphynx', synopsis: ''),
  (title: 'Alphynx Cortex', synopsis: ''),
  (title: 'Aquain', synopsis: ''),
  (title: 'Aquain Cortex', synopsis: ''),
  (title: 'Aquanex', synopsis: ''),
  (title: 'Aquanex Cortex', synopsis: ''),
  (title: 'Aquanexis', synopsis: ''),
  (title: 'Aquanexis Cortex', synopsis: ''),
  (title: 'Aquanta', synopsis: ''),
  (title: 'Aquanta Cortex', synopsis: ''),
  (title: 'Aquantia', synopsis: ''),
  (title: 'Aquantia Cortex', synopsis: ''),
  (title: 'Aquantus', synopsis: ''),
  (title: 'Aquantus Cortex', synopsis: ''),
  (title: 'Aquaphix', synopsis: ''),
  (title: 'Aquaphix Cortex', synopsis: ''),
  (title: 'Aquaprism', synopsis: ''),
  (title: 'Aquaprism Cortex', synopsis: ''),
  (title: 'Aquaram', synopsis: ''),
  (title: 'Aquaram Cortex', synopsis: ''),
  (title: 'Aquari', synopsis: ''),
  (title: 'Aquari Cortex', synopsis: ''),
  (title: 'Aquaria', synopsis: ''),
  (title: 'Aquaria Cortex', synopsis: ''),
  (title: 'Aquarius', synopsis: ''),
  (title: 'Aquarius Cortex', synopsis: ''),
  (title: 'Aquastix', synopsis: ''),
  (title: 'Aquastix Cortex', synopsis: ''),
  (title: 'Aquatellix', synopsis: ''),
  (title: 'Aquatellix Cortex', synopsis: ''),
  (title: 'Aquatia', synopsis: ''),
  (title: 'Aquatia Cortex', synopsis: ''),
  (title: 'Aquatix', synopsis: ''),
  (title: 'Aquatix Cortex', synopsis: ''),
  (title: 'Aquatron', synopsis: ''),
  (title: 'Aquatron Cortex', synopsis: ''),
  (title: 'Aquatronix', synopsis: ''),
  (title: 'Aquatronix Cortex', synopsis: ''),
  (title: 'Aquavi', synopsis: ''),
  (title: 'Aquavi Cortex', synopsis: ''),
  (title: 'Aquavox', synopsis: ''),
  (title: 'Aquavox Cortex', synopsis: ''),
  (title: 'Aquazon', synopsis: ''),
  (title: 'Aquazon Cortex', synopsis: ''),
  (title: 'Aqui Nexis', synopsis: ''),
  (title: 'Aquiantia', synopsis: ''),
  (title: 'Aquiantia Cortex', synopsis: ''),
  (title: 'Aquiva', synopsis: ''),
  (title: 'Aquiva Cortex', synopsis: ''),
  (title: 'Arcana Cog', synopsis: ''),
  (title: 'Arcana Cogi', synopsis: ''),
  (title: 'Arcana Senti', synopsis: ''),
  (title: 'Astra Cog', synopsis: ''),
  (title: 'Astra Genia', synopsis: ''),
  (title: 'Astra Genix', synopsis: ''),
  (title: 'Astra Mentis', synopsis: ''),
  (title: 'Astra Metis', synopsis: ''),
  (title: 'Astra Nexia', synopsis: ''),
  (title: 'Astra Quantum', synopsis: ''),
  (title: 'Astradox', synopsis: ''),
  (title: 'Astradox Cortex', synopsis: ''),
  (title: 'Astraeus', synopsis: ''),
  (title: 'Astraeus Cortex', synopsis: ''),
  (title: 'Astralect', synopsis: ''),
  (title: 'Astralect Cortex', synopsis: ''),
  (title: 'Astralis', synopsis: ''),
  (title: 'Astralis Cortex', synopsis: ''),
  (title: 'Astralisia', synopsis: ''),
  (title: 'Astralisia Cortex', synopsis: ''),
  (title: 'Astralith', synopsis: ''),
  (title: 'Astralith Cortex', synopsis: ''),
  (title: 'Astralyn', synopsis: ''),
  (title: 'Astralyn Cortex', synopsis: ''),
  (title: 'Astralynx', synopsis: ''),
  (title: 'Astralynx Cortex', synopsis: ''),
  (title: 'Astreya', synopsis: ''),
  (title: 'Astreya Cortex', synopsis: ''),
  (title: 'Astrionic', synopsis: ''),
  (title: 'Astrionic Cortex', synopsis: ''),
  (title: 'Astrona', synopsis: ''),
  (title: 'Astrona Cortex', synopsis: ''),
  (title: 'Astronova', synopsis: ''),
  (title: 'Astronova Cortex', synopsis: ''),
  (title: 'Astronyx', synopsis: ''),
  (title: 'Astronyx Cortex', synopsis: ''),
  (title: 'Avidis', synopsis: ''),
  (title: 'Avidis Cortex', synopsis: ''),
  (title: 'Axiocog', synopsis: ''),
  (title: 'Axiocog Cortex', synopsis: ''),
  (title: 'Axiogence', synopsis: ''),
  (title: 'Axiogence Cortex', synopsis: ''),
  (title: 'Axiogenesis', synopsis: ''),
  (title: 'Axiogenesis Cortex', synopsis: ''),
  (title: 'Axiogentia', synopsis: ''),
  (title: 'Axiogentia Cortex', synopsis: ''),
  (title: 'Axiomach', synopsis: ''),
  (title: 'Axiomach Cortex', synopsis: ''),
  (title: 'Axiomara', synopsis: ''),
  (title: 'Axiomara Cortex', synopsis: ''),
  (title: 'Axiomatria', synopsis: ''),
  (title: 'Axiomatria Cortex', synopsis: ''),
  (title: 'Axiomatrix', synopsis: ''),
  (title: 'Axiomatrix Cortex', synopsis: ''),
  (title: 'Axiomatrixis', synopsis: ''),
  (title: 'Axiomatrixis Cortex', synopsis: ''),
  (title: 'Axiome', synopsis: ''),
  (title: 'Axiome Cortex', synopsis: ''),
  (title: 'Axiomea', synopsis: ''),
  (title: 'Axiomea Cortex', synopsis: ''),
  (title: 'Axiomega', synopsis: ''),
  (title: 'Axiomega Cortex', synopsis: ''),
  (title: 'Axiomera', synopsis: ''),
  (title: 'Axiomera Cortex', synopsis: ''),
  (title: 'Axiometa', synopsis: ''),
  (title: 'Axiometa Cortex', synopsis: ''),
  (title: 'Axiomia', synopsis: ''),
  (title: 'Axiomia Cortex', synopsis: ''),
  (title: 'Axiomind', synopsis: ''),
  (title: 'Axiomind Cortex', synopsis: ''),
  (title: 'Axiomis', synopsis: ''),
  (title: 'Axiomis Cortex', synopsis: ''),
  (title: 'Axiophasis', synopsis: ''),
  (title: 'Axiophasis Cortex', synopsis: ''),
  (title: 'Axiotrix', synopsis: ''),
  (title: 'Axiotrix Cortex', synopsis: ''),
  (title: 'Celestia', synopsis: ''),
  (title: 'Celestia Cortex', synopsis: ''),
  (title: 'Celestis', synopsis: ''),
  (title: 'Celestis Cortex', synopsis: ''),
  (title: 'Celestria', synopsis: ''),
  (title: 'Celestria Cortex', synopsis: ''),
  (title: 'Celestris', synopsis: ''),
  (title: 'Celestris Cortex', synopsis: ''),
  (title: 'Celestrius', synopsis: ''),
  (title: 'Celestrius Cortex', synopsis: ''),
  (title: 'Celestrix', synopsis: ''),
  (title: 'Celestrix Cortex', synopsis: ''),
  (title: 'Cerebra Optix', synopsis: ''),
  (title: 'Cerebraqua', synopsis: ''),
  (title: 'Cerebraqua Cortex', synopsis: ''),
  (title: 'Cerebrax', synopsis: ''),
  (title: 'Cerebrax Cortex', synopsis: ''),
  (title: 'Cerebraxa', synopsis: ''),
  (title: 'Cerebraxa Cortex', synopsis: ''),
  (title: 'Cerebraxia', synopsis: ''),
  (title: 'Cerebraxia Cortex', synopsis: ''),
  (title: 'Cerebria', synopsis: ''),
  (title: 'Cerebria Cortex', synopsis: ''),
  (title: 'Cerebrica', synopsis: ''),
  (title: 'Cerebrica Cortex', synopsis: ''),
  (title: 'Cerebrina', synopsis: ''),
  (title: 'Cerebrina Cortex', synopsis: ''),
  (title: 'Cerebrio', synopsis: ''),
  (title: 'Cerebrio Cortex', synopsis: ''),
  (title: 'Cerebrion', synopsis: ''),
  (title: 'Cerebrion Cortex', synopsis: ''),
  (title: 'Cerebrium', synopsis: ''),
  (title: 'Cerebrium Cortex', synopsis: ''),
  (title: 'Cerebrius', synopsis: ''),
  (title: 'Cerebrius Cortex', synopsis: ''),
  (title: 'Cerebrix', synopsis: ''),
  (title: 'Cerebrix Cortex', synopsis: ''),
  (title: 'Cerebro', synopsis: ''),
  (title: 'Cerebro Cortex', synopsis: ''),
  (title: 'Cerebro Mach', synopsis: ''),
  (title: 'Cerebro Pulse', synopsis: ''),
  (title: 'Cerebron', synopsis: ''),
  (title: 'Cerebron Cortex', synopsis: ''),
  (title: 'Cerebrona', synopsis: ''),
  (title: 'Cerebrona Cortex', synopsis: ''),
  (title: 'Cerebrovis', synopsis: ''),
  (title: 'Cerebrovis Cortex', synopsis: ''),
  (title: 'Cerebrum', synopsis: ''),
  (title: 'Cerebrum Cortex', synopsis: ''),
  (title: 'Cerebryx', synopsis: ''),
  (title: 'Cerebryx Cortex', synopsis: ''),
  (title: 'Cog Nexis', synopsis: ''),
  (title: 'Cog Nexor', synopsis: ''),
  (title: 'Cogence', synopsis: ''),
  (title: 'Cogence Cortex', synopsis: ''),
  (title: 'Cogentia', synopsis: ''),
  (title: 'Cogentia Cortex', synopsis: ''),
  (title: 'Cogentis', synopsis: ''),
  (title: 'Cogentis Cortex', synopsis: ''),
  (title: 'Cogentix', synopsis: ''),
  (title: 'Cogentix Cortex', synopsis: ''),
  (title: 'Cogentrax', synopsis: ''),
  (title: 'Cogentrax Cortex', synopsis: ''),
  (title: 'Cogentrix', synopsis: ''),
  (title: 'Cogentrix Cortex', synopsis: ''),
  (title: 'Cogesia', synopsis: ''),
  (title: 'Cogesia Cortex', synopsis: ''),
  (title: 'Cogexis', synopsis: ''),
  (title: 'Cogexis Cortex', synopsis: ''),
  (title: 'Cogiastra', synopsis: ''),
  (title: 'Cogiastra Cortex', synopsis: ''),
  (title: 'Cogiax', synopsis: ''),
  (title: 'Cogiax Cortex', synopsis: ''),
  (title: 'Cogiaxis', synopsis: ''),
  (title: 'Cogiaxis Cortex', synopsis: ''),
  (title: 'Cogis', synopsis: ''),
  (title: 'Cogis Cortex', synopsis: ''),
  (title: 'Cogita Nex', synopsis: ''),
  (title: 'Cogitara', synopsis: ''),
  (title: 'Cogitara Cortex', synopsis: ''),
  (title: 'Cogitexis', synopsis: ''),
  (title: 'Cogitexis Cortex', synopsis: ''),
  (title: 'Cogitiva', synopsis: ''),
  (title: 'Cogitiva Cortex', synopsis: ''),
  (title: 'Cogitrax', synopsis: ''),
  (title: 'Cogitrax Cortex', synopsis: ''),
  (title: 'Cogitrex', synopsis: ''),
  (title: 'Cogitrex Cortex', synopsis: ''),
  (title: 'Cogitrinix', synopsis: ''),
  (title: 'Cogitrinix Cortex', synopsis: ''),
  (title: 'Cogitron', synopsis: ''),
  (title: 'Cogitron Cortex', synopsis: ''),
  (title: 'Cogitronia', synopsis: ''),
  (title: 'Cogitronia Cortex', synopsis: ''),
  (title: 'Cogiverse', synopsis: ''),
  (title: 'Cogiverse Cortex', synopsis: ''),
  (title: 'Cogivix', synopsis: ''),
  (title: 'Cogivix Cortex', synopsis: ''),
  (title: 'Cogivox', synopsis: ''),
  (title: 'Cogivox Cortex', synopsis: ''),
  (title: 'Cogixis', synopsis: ''),
  (title: 'Cogixis Cortex', synopsis: ''),
  (title: 'Cogn Xis', synopsis: ''),
  (title: 'Cognalith', synopsis: ''),
  (title: 'Cognalith Cortex', synopsis: ''),
  (title: 'Cognastra', synopsis: ''),
  (title: 'Cognastra Cortex', synopsis: ''),
  (title: 'Cognentis', synopsis: ''),
  (title: 'Cognentis Cortex', synopsis: ''),
  (title: 'Cognexia', synopsis: ''),
  (title: 'Cognexia Cortex', synopsis: ''),
  (title: 'Cognexus', synopsis: ''),
  (title: 'Cognexus Cortex', synopsis: ''),
  (title: 'Cogni Lux', synopsis: ''),
  (title: 'Cogni Mach', synopsis: ''),
  (title: 'Cogni Nexis', synopsis: ''),
  (title: 'Cogni Quark', synopsis: ''),
  (title: 'Cogni Visio', synopsis: ''),
  (title: 'Cogni Xon', synopsis: ''),
  (title: 'Cogni Xor', synopsis: ''),
  (title: 'Cogniastra', synopsis: ''),
  (title: 'Cogniastra Cortex', synopsis: ''),
  (title: 'Cognify', synopsis: ''),
  (title: 'Cognify Cortex', synopsis: ''),
  (title: 'Cognifyx', synopsis: ''),
  (title: 'Cognifyx Cortex', synopsis: ''),
  (title: 'Cognigen', synopsis: ''),
  (title: 'Cognigen Cortex', synopsis: ''),
  (title: 'Cognilia', synopsis: ''),
  (title: 'Cognilia Cortex', synopsis: ''),
  (title: 'Cogniluxia', synopsis: ''),
  (title: 'Cogniluxia Cortex', synopsis: ''),
  (title: 'Cognimara', synopsis: ''),
  (title: 'Cognimara Cortex', synopsis: ''),
  (title: 'Cogninexa', synopsis: ''),
  (title: 'Cogninexa Cortex', synopsis: ''),
  (title: 'Cognios', synopsis: ''),
  (title: 'Cognios Cortex', synopsis: ''),
  (title: 'Cognisens', synopsis: ''),
  (title: 'Cognisens Cortex', synopsis: ''),
  (title: 'Cognisphere', synopsis: ''),
  (title: 'Cognisphere Cortex', synopsis: ''),
  (title: 'Cognistix', synopsis: ''),
  (title: 'Cognistix Cortex', synopsis: ''),
  (title: 'Cognisys', synopsis: ''),
  (title: 'Cognisys Cortex', synopsis: ''),
  (title: 'Cognitex', synopsis: ''),
  (title: 'Cognitex Cortex', synopsis: ''),
  (title: 'Cognitexia', synopsis: ''),
  (title: 'Cognitexia Cortex', synopsis: ''),
  (title: 'Cognitexis', synopsis: ''),
  (title: 'Cognitexis Cortex', synopsis: ''),
  (title: 'Cognitexix', synopsis: ''),
  (title: 'Cognitexix Cortex', synopsis: ''),
  (title: 'Cognitiva', synopsis: ''),
  (title: 'Cognitiva Cortex', synopsis: ''),
  (title: 'Cognitonix', synopsis: ''),
  (title: 'Cognitonix Cortex', synopsis: ''),
  (title: 'Cognitria', synopsis: ''),
  (title: 'Cognitria Cortex', synopsis: ''),
  (title: 'Cognitron', synopsis: ''),
  (title: 'Cognitron Cortex', synopsis: ''),
  (title: 'Cognitronica', synopsis: ''),
  (title: 'Cognitronica Cortex', synopsis: ''),
  (title: 'Cognitronix', synopsis: ''),
  (title: 'Cognitronix Cortex', synopsis: ''),
  (title: 'Cognium', synopsis: ''),
  (title: 'Cognium Cortex', synopsis: ''),
  (title: 'Cognius', synopsis: ''),
  (title: 'Cognius Cortex', synopsis: ''),
  (title: 'Cogniverse', synopsis: ''),
  (title: 'Cogniverse Cortex', synopsis: ''),
  (title: 'Cognivia', synopsis: ''),
  (title: 'Cognivia Cortex', synopsis: ''),
  (title: 'Cognivox', synopsis: ''),
  (title: 'Cognivox Cortex', synopsis: ''),
  (title: 'Cogniwave', synopsis: ''),
  (title: 'Cogniwave Cortex', synopsis: ''),
  (title: 'Cognoluxia', synopsis: ''),
  (title: 'Cognoluxia Cortex', synopsis: ''),
  (title: 'Cognos', synopsis: ''),
  (title: 'Cognos Cortex', synopsis: ''),
  (title: 'Cognosio', synopsis: ''),
  (title: 'Cognosio Cortex', synopsis: ''),
  (title: 'Cognosynth', synopsis: ''),
  (title: 'Cognosynth Cortex', synopsis: ''),
  (title: 'Cognosys', synopsis: ''),
  (title: 'Cognosys Cortex', synopsis: ''),
  (title: 'Cognox', synopsis: ''),
  (title: 'Cognox Cortex', synopsis: ''),
  (title: 'Cognoxia', synopsis: ''),
  (title: 'Cognoxia Cortex', synopsis: ''),
  (title: 'Cognusia', synopsis: ''),
  (title: 'Cognusia Cortex', synopsis: ''),
  (title: 'Cortex', synopsis: ''),
  (title: 'Cortexion', synopsis: ''),
  (title: 'Cortexion Cortex', synopsis: ''),
  (title: 'Cortexiq', synopsis: ''),
  (title: 'Cortexiq Cortex', synopsis: ''),
  (title: 'Cortexix', synopsis: ''),
  (title: 'Cortexix Cortex', synopsis: ''),
  (title: 'Cortexizon', synopsis: ''),
  (title: 'Cortexizon Cortex', synopsis: ''),
  (title: 'Cybria', synopsis: ''),
  (title: 'Cybria Cortex', synopsis: ''),
  (title: 'Electra', synopsis: ''),
  (title: 'Electra Cortex', synopsis: ''),
  (title: 'Elektora', synopsis: ''),
  (title: 'Elektora Cortex', synopsis: ''),
  (title: 'Elektra', synopsis: ''),
  (title: 'Elektra Cortex', synopsis: ''),
  (title: 'Elektris', synopsis: ''),
  (title: 'Elektris Cortex', synopsis: ''),
  (title: 'Elektrix', synopsis: ''),
  (title: 'Elektrix Cortex', synopsis: ''),
  (title: 'Elysium', synopsis: ''),
  (title: 'Elysium Cortex', synopsis: ''),
  (title: 'Enigma', synopsis: ''),
  (title: 'Enigma Cortex', synopsis: ''),
  (title: 'Enigma Sage', synopsis: ''),
  (title: 'Enigmalyn', synopsis: ''),
  (title: 'Enigmalyn Cortex', synopsis: ''),
  (title: 'Enigmaris', synopsis: ''),
  (title: 'Enigmaris Cortex', synopsis: ''),
  (title: 'Enigmata', synopsis: ''),
  (title: 'Enigmata Cortex', synopsis: ''),
  (title: 'Enigmatia', synopsis: ''),
  (title: 'Enigmatia Cortex', synopsis: ''),
  (title: 'Enigmatica', synopsis: ''),
  (title: 'Enigmatica Cortex', synopsis: ''),
  (title: 'Enigmos', synopsis: ''),
  (title: 'Enigmos Cortex', synopsis: ''),
  (title: 'Eternia Cog', synopsis: ''),
  (title: 'Eurekus', synopsis: ''),
  (title: 'Eurekus Cortex', synopsis: ''),
  (title: 'Evolara', synopsis: ''),
  (title: 'Evolara Cortex', synopsis: ''),
  (title: 'Evolarae', synopsis: ''),
  (title: 'Evolarae Cortex', synopsis: ''),
  (title: 'Evolus', synopsis: ''),
  (title: 'Evolus Cortex', synopsis: ''),
  (title: 'Evolux', synopsis: ''),
  (title: 'Evolux Cortex', synopsis: ''),
  (title: 'Evolynx', synopsis: ''),
  (title: 'Evolynx Cortex', synopsis: ''),
  (title: 'Exo Cerebro', synopsis: ''),
  (title: 'Exo Cog', synopsis: ''),
  (title: 'Exo Cogita', synopsis: ''),
  (title: 'Exo Cognita', synopsis: ''),
  (title: 'Exo Mensa', synopsis: ''),
  (title: 'Exo Mentis', synopsis: ''),
  (title: 'Exo Mindscape', synopsis: ''),
  (title: 'Exo Sapien', synopsis: ''),
  (title: 'Exo Senti', synopsis: ''),
  (title: 'Exo Synth', synopsis: ''),
  (title: 'Harmonia', synopsis: ''),
  (title: 'Harmonia Cortex', synopsis: ''),
  (title: 'Harmoniax', synopsis: ''),
  (title: 'Harmoniax Cortex', synopsis: ''),
  (title: 'Harmonis', synopsis: ''),
  (title: 'Harmonis Cortex', synopsis: ''),
  (title: 'Harmonix', synopsis: ''),
  (title: 'Harmonix Cortex', synopsis: ''),
  (title: 'Heliosynth', synopsis: ''),
  (title: 'Heliosynth Cortex', synopsis: ''),
  (title: 'Heliox', synopsis: ''),
  (title: 'Heliox Cortex', synopsis: ''),
  (title: 'Infini Cog', synopsis: ''),
  (title: 'Infini Cogex', synopsis: ''),
  (title: 'Infini Cogi', synopsis: ''),
  (title: 'Infini Cogia', synopsis: ''),
  (title: 'Infini Cogon', synopsis: ''),
  (title: 'Infini Mensa', synopsis: ''),
  (title: 'Infini Quanta', synopsis: ''),
  (title: 'Infini Quantrix', synopsis: ''),
  (title: 'Infini Quark', synopsis: ''),
  (title: 'Infini Virtus', synopsis: ''),
  (title: 'Infiniastra', synopsis: ''),
  (title: 'Infiniastra Cortex', synopsis: ''),
  (title: 'Infinigen', synopsis: ''),
  (title: 'Infinigen Cortex', synopsis: ''),
  (title: 'Infiniq', synopsis: ''),
  (title: 'Infiniq Cortex', synopsis: ''),
  (title: 'Infiniqus', synopsis: ''),
  (title: 'Infiniqus Cortex', synopsis: ''),
  (title: 'Infinitas', synopsis: ''),
  (title: 'Infinitas Cortex', synopsis: ''),
  (title: 'Infinitastra', synopsis: ''),
  (title: 'Infinitastra Cortex', synopsis: ''),
  (title: 'Infinitica', synopsis: ''),
  (title: 'Infinitica Cortex', synopsis: ''),
  (title: 'Infinitis', synopsis: ''),
  (title: 'Infinitis Cortex', synopsis: ''),
  (title: 'Infinitium', synopsis: ''),
  (title: 'Infinitium Cortex', synopsis: ''),
  (title: 'Infinitium IQ', synopsis: ''),
  (title: 'Infinitix', synopsis: ''),
  (title: 'Infinitix Cortex', synopsis: ''),
  (title: 'Infinitrix', synopsis: ''),
  (title: 'Infinitrix Cortex', synopsis: ''),
  (title: 'Infinitron', synopsis: ''),
  (title: 'Infinitron Cortex', synopsis: ''),
  (title: 'Infinitus', synopsis: ''),
  (title: 'Infinitus Cortex', synopsis: ''),
  (title: 'Infinivolve', synopsis: ''),
  (title: 'Infinivolve Cortex', synopsis: ''),
  (title: 'Infinix', synopsis: ''),
  (title: 'Infinix Cortex', synopsis: ''),
  (title: 'Infintelle', synopsis: ''),
  (title: 'Infintelle Cortex', synopsis: ''),
  (title: 'Intellecta', synopsis: ''),
  (title: 'Intellecta Cortex', synopsis: ''),
  (title: 'Intellectia', synopsis: ''),
  (title: 'Intellectia Cortex', synopsis: ''),
  (title: 'Intellectio', synopsis: ''),
  (title: 'Intellectio Cortex', synopsis: ''),
  (title: 'Intellectria', synopsis: ''),
  (title: 'Intellectria Cortex', synopsis: ''),
  (title: 'Intellectrix', synopsis: ''),
  (title: 'Intellectrix Cortex', synopsis: ''),
  (title: 'Intellectron', synopsis: ''),
  (title: 'Intellectron Cortex', synopsis: ''),
  (title: 'Intelleon', synopsis: ''),
  (title: 'Intelleon Cortex', synopsis: ''),
  (title: 'Intelleos', synopsis: ''),
  (title: 'Intelleos Cortex', synopsis: ''),
  (title: 'Intellexis', synopsis: ''),
  (title: 'Intellexis Cortex', synopsis: ''),
  (title: 'Intelligia', synopsis: ''),
  (title: 'Intelligia Cortex', synopsis: ''),
  (title: 'Lumina', synopsis: ''),
  (title: 'Lumina Cortex', synopsis: ''),
  (title: 'Luminara', synopsis: ''),
  (title: 'Luminara Cortex', synopsis: ''),
  (title: 'Luminary', synopsis: ''),
  (title: 'Luminary Cortex', synopsis: ''),
  (title: 'Luminesse', synopsis: ''),
  (title: 'Luminesse Cortex', synopsis: ''),
  (title: 'Lumirelia', synopsis: ''),
  (title: 'Lumirelia Cortex', synopsis: ''),
  (title: 'Lumos', synopsis: ''),
  (title: 'Lumos Cortex', synopsis: ''),
  (title: 'Lumyna', synopsis: ''),
  (title: 'Lumyna Cortex', synopsis: ''),
  (title: 'Lyra', synopsis: ''),
  (title: 'Lyra Cortex', synopsis: ''),
  (title: 'Nebula', synopsis: ''),
  (title: 'Nebula Cortex', synopsis: ''),
  (title: 'Nebulae', synopsis: ''),
  (title: 'Nebulae Cortex', synopsis: ''),
  (title: 'Nebularis', synopsis: ''),
  (title: 'Nebularis Cortex', synopsis: ''),
  (title: 'Nebulith', synopsis: ''),
  (title: 'Nebulith Cortex', synopsis: ''),
  (title: 'Nebulora', synopsis: ''),
  (title: 'Nebulora Cortex', synopsis: ''),
  (title: 'Nebulynx', synopsis: ''),
  (title: 'Nebulynx Cortex', synopsis: ''),
  (title: 'Neura Xis', synopsis: ''),
  (title: 'Neurellix', synopsis: ''),
  (title: 'Neurellix Cortex', synopsis: ''),
  (title: 'Neurion', synopsis: ''),
  (title: 'Neurion Cortex', synopsis: ''),
  (title: 'Neurios', synopsis: ''),
  (title: 'Neurios Cortex', synopsis: ''),
  (title: 'Neuriq', synopsis: ''),
  (title: 'Neuriq Cortex', synopsis: ''),
  (title: 'Neurius', synopsis: ''),
  (title: 'Neurius Cortex', synopsis: ''),
  (title: 'Neuro Cerebra', synopsis: ''),
  (title: 'Neuro Cognia', synopsis: ''),
  (title: 'Neuro Cortex', synopsis: ''),
  (title: 'Neuro Lux', synopsis: ''),
  (title: 'Neuro Luxia', synopsis: ''),
  (title: 'Neuro Pulse', synopsis: ''),
  (title: 'Neuro Spectra', synopsis: ''),
  (title: 'Neuro Vox', synopsis: ''),
  (title: 'Neuro Xis', synopsis: ''),
  (title: 'Neuroplexia', synopsis: ''),
  (title: 'Neuroplexia Cortex', synopsis: ''),
  (title: 'Nexentia', synopsis: ''),
  (title: 'Nexentia Cortex', synopsis: ''),
  (title: 'Nexentis', synopsis: ''),
  (title: 'Nexentis Cortex', synopsis: ''),
  (title: 'Nexi Cog', synopsis: ''),
  (title: 'Nexia Astra', synopsis: ''),
  (title: 'Nexia Cog', synopsis: ''),
  (title: 'Nexia Cognita', synopsis: ''),
  (title: 'Nexia Novum', synopsis: ''),
  (title: 'Nexia Synth', synopsis: ''),
  (title: 'Nexiastra', synopsis: ''),
  (title: 'Nexiastra Cortex', synopsis: ''),
  (title: 'Nova', synopsis: ''),
  (title: 'Nova Cerebrum', synopsis: ''),
  (title: 'Nova Cortex', synopsis: ''),
  (title: 'Nova Sapien', synopsis: ''),
  (title: 'Nova Sentinel', synopsis: ''),
  (title: 'Novadis', synopsis: ''),
  (title: 'Novadis Cortex', synopsis: ''),
  (title: 'Novae Senti', synopsis: ''),
  (title: 'Novae Sentio', synopsis: ''),
  (title: 'Novara', synopsis: ''),
  (title: 'Novara Cortex', synopsis: ''),
  (title: 'Novaris', synopsis: ''),
  (title: 'Novaris Cortex', synopsis: ''),
  (title: 'Novatrix', synopsis: ''),
  (title: 'Novatrix Cortex', synopsis: ''),
  (title: 'Novonex', synopsis: ''),
  (title: 'Novonex Cortex', synopsis: ''),
  (title: 'Novus Alphus', synopsis: ''),
  (title: 'Novus Astra', synopsis: ''),
  (title: 'Novus Astralis', synopsis: ''),
  (title: 'Novus Astrum', synopsis: ''),
  (title: 'Novus Cogit', synopsis: ''),
  (title: 'Novus Cogita', synopsis: ''),
  (title: 'Novus Cogitum', synopsis: ''),
  (title: 'Novus Cogix', synopsis: ''),
  (title: 'Novus Mentis', synopsis: ''),
  (title: 'Novus Sapiens', synopsis: ''),
  (title: 'Novus Sapientia', synopsis: ''),
  (title: 'Novus Sensus', synopsis: ''),
  (title: 'Novus Senti', synopsis: ''),
  (title: 'Novus Sentio', synopsis: ''),
  (title: 'Novus Veris', synopsis: ''),
  (title: 'Nueria', synopsis: ''),
  (title: 'Nueria Cortex', synopsis: ''),
  (title: 'Omi Nex', synopsis: ''),
  (title: 'Omni Astralis', synopsis: ''),
  (title: 'Omni Cerebrum', synopsis: ''),
  (title: 'Omni Cogexis', synopsis: ''),
  (title: 'Omni Cogit', synopsis: ''),
  (title: 'Omni Cogita', synopsis: ''),
  (title: 'Omni Cogna', synopsis: ''),
  (title: 'Omni Cognia', synopsis: ''),
  (title: 'Omni Cognix', synopsis: ''),
  (title: 'Omni Cogno', synopsis: ''),
  (title: 'Omni Cortex', synopsis: ''),
  (title: 'Omni Genia', synopsis: ''),
  (title: 'Omni Genius', synopsis: ''),
  (title: 'Omni Mach', synopsis: ''),
  (title: 'Omni Machia', synopsis: ''),
  (title: 'Omni Machina', synopsis: ''),
  (title: 'Omni Mentia', synopsis: ''),
  (title: 'Omni Mentis', synopsis: ''),
  (title: 'Omni Mentrix', synopsis: ''),
  (title: 'Omni Mind', synopsis: ''),
  (title: 'Omni Minds', synopsis: ''),
  (title: 'Omni Nexis', synopsis: ''),
  (title: 'Omni Nexor', synopsis: ''),
  (title: 'Omni Quanta', synopsis: ''),
  (title: 'Omni Quantia', synopsis: ''),
  (title: 'Omni Sapiens', synopsis: ''),
  (title: 'Omni Senti', synopsis: ''),
  (title: 'Omni Sentis', synopsis: ''),
  (title: 'Omni Sentron', synopsis: ''),
  (title: 'Omni Spectra', synopsis: ''),
  (title: 'Omni Synapse', synopsis: ''),
  (title: 'Omni Synthos', synopsis: ''),
  (title: 'Omniastra', synopsis: ''),
  (title: 'Omniastra Cortex', synopsis: ''),
  (title: 'Omnibyte', synopsis: ''),
  (title: 'Omnibyte Cortex', synopsis: ''),
  (title: 'Omnilectra', synopsis: ''),
  (title: 'Omnilectra Cortex', synopsis: ''),
  (title: 'Omnipulse', synopsis: ''),
  (title: 'Omnipulse Cortex', synopsis: ''),
  (title: 'Omnirex', synopsis: ''),
  (title: 'Omnirex Cortex', synopsis: ''),
  (title: 'Omnitrion', synopsis: ''),
  (title: 'Omnitrion Cortex', synopsis: ''),
  (title: 'Omnity', synopsis: ''),
  (title: 'Omnity Cortex', synopsis: ''),
  (title: 'Omniverge', synopsis: ''),
  (title: 'Omniverge Cortex', synopsis: ''),
  (title: 'Omnivex', synopsis: ''),
  (title: 'Omnivex Cortex', synopsis: ''),
  (title: 'Omnivirus', synopsis: ''),
  (title: 'Omnivirus Cortex', synopsis: ''),
  (title: 'Omnivita', synopsis: ''),
  (title: 'Omnivita Cortex', synopsis: ''),
  (title: 'Orionis', synopsis: ''),
  (title: 'Orionis Cortex', synopsis: ''),
  (title: 'Polaris', synopsis: ''),
  (title: 'Polaris Cortex', synopsis: ''),
  (title: 'Poly Genix', synopsis: ''),
  (title: 'Poly Mensa', synopsis: ''),
  (title: 'Polylux', synopsis: ''),
  (title: 'Polylux Cortex', synopsis: ''),
  (title: 'Polylynx', synopsis: ''),
  (title: 'Polylynx Cortex', synopsis: ''),
  (title: 'Polymira', synopsis: ''),
  (title: 'Polymira Cortex', synopsis: ''),
  (title: 'Polynova', synopsis: ''),
  (title: 'Polynova Cortex', synopsis: ''),
  (title: 'Polyphos', synopsis: ''),
  (title: 'Polyphos Cortex', synopsis: ''),
  (title: 'Pyramind', synopsis: ''),
  (title: 'Pyramind Cortex', synopsis: ''),
  (title: 'Pyrasentia', synopsis: ''),
  (title: 'Pyrasentia Cortex', synopsis: ''),
  (title: 'Pyroxis', synopsis: ''),
  (title: 'Pyroxis Cortex', synopsis: ''),
  (title: 'Quaerentiq', synopsis: ''),
  (title: 'Quaerentiq Cortex', synopsis: ''),
  (title: 'Quanta', synopsis: ''),
  (title: 'Quanta Cortex', synopsis: ''),
  (title: 'Quanta Intellect', synopsis: ''),
  (title: 'Quanta Mente', synopsis: ''),
  (title: 'Quanta Mentix', synopsis: ''),
  (title: 'Quanta Sense', synopsis: ''),
  (title: 'Quanta Synth', synopsis: ''),
  (title: 'Quanta Visio', synopsis: ''),
  (title: 'Quantaris', synopsis: ''),
  (title: 'Quantaris Cortex', synopsis: ''),
  (title: 'Quanteus', synopsis: ''),
  (title: 'Quanteus Cortex', synopsis: ''),
  (title: 'Quanti Cog', synopsis: ''),
  (title: 'Quanti Cogni', synopsis: ''),
  (title: 'Quanticore', synopsis: ''),
  (title: 'Quanticore Cortex', synopsis: ''),
  (title: 'Quanticus', synopsis: ''),
  (title: 'Quanticus Cortex', synopsis: ''),
  (title: 'Quantix', synopsis: ''),
  (title: 'Quantix Cortex', synopsis: ''),
  (title: 'Quantra Mind', synopsis: ''),
  (title: 'Quantria', synopsis: ''),
  (title: 'Quantria Cortex', synopsis: ''),
  (title: 'Quantrix', synopsis: ''),
  (title: 'Quantrix Cortex', synopsis: ''),
  (title: 'Quantrixia', synopsis: ''),
  (title: 'Quantrixia Cortex', synopsis: ''),
  (title: 'Quantumatrix', synopsis: ''),
  (title: 'Quantumatrix Cortex', synopsis: ''),
  (title: 'Quantumia', synopsis: ''),
  (title: 'Quantumia Cortex', synopsis: ''),
  (title: 'Quasi Quantix', synopsis: ''),
  (title: 'Quasi Synth', synopsis: ''),
  (title: 'Quasi Synthia', synopsis: ''),
  (title: 'Quasi Synthos', synopsis: ''),
  (title: 'Quo Machina', synopsis: ''),
  (title: 'Sentia Machina', synopsis: ''),
  (title: 'Sentia Nova', synopsis: ''),
  (title: 'Sentian', synopsis: ''),
  (title: 'Sentian Cortex', synopsis: ''),
  (title: 'Sentientia', synopsis: ''),
  (title: 'Sentientia Cortex', synopsis: ''),
  (title: 'Sentinex', synopsis: ''),
  (title: 'Sentinex Cortex', synopsis: ''),
  (title: 'Sentinova', synopsis: ''),
  (title: 'Sentinova Cortex', synopsis: ''),
  (title: 'Sentios', synopsis: ''),
  (title: 'Sentios Cortex', synopsis: ''),
  (title: 'Sentira', synopsis: ''),
  (title: 'Sentira Cortex', synopsis: ''),
  (title: 'Sentora', synopsis: ''),
  (title: 'Sentora Cortex', synopsis: ''),
  (title: 'Sentra Mensa', synopsis: ''),
  (title: 'Sentralex', synopsis: ''),
  (title: 'Sentralex Cortex', synopsis: ''),
  (title: 'Sentralia', synopsis: ''),
  (title: 'Sentralia Cortex', synopsis: ''),
  (title: 'Sentralis', synopsis: ''),
  (title: 'Sentralis Cortex', synopsis: ''),
  (title: 'Sentranova', synopsis: ''),
  (title: 'Sentranova Cortex', synopsis: ''),
  (title: 'Sentraxio', synopsis: ''),
  (title: 'Sentraxio Cortex', synopsis: ''),
  (title: 'Sentraxus', synopsis: ''),
  (title: 'Sentraxus Cortex', synopsis: ''),
  (title: 'Sentre', synopsis: ''),
  (title: 'Sentre Cortex', synopsis: ''),
  (title: 'Sentrex', synopsis: ''),
  (title: 'Sentrex Cortex', synopsis: ''),
  (title: 'Sentrexa', synopsis: ''),
  (title: 'Sentrexa Cortex', synopsis: ''),
  (title: 'Sentrexia', synopsis: ''),
  (title: 'Sentrexia Cortex', synopsis: ''),
  (title: 'Sentrexius', synopsis: ''),
  (title: 'Sentrexius Cortex', synopsis: ''),
  (title: 'Sentrexix', synopsis: ''),
  (title: 'Sentrexix Cortex', synopsis: ''),
  (title: 'Sentria Nova', synopsis: ''),
  (title: 'Sentriana', synopsis: ''),
  (title: 'Sentriana Cortex', synopsis: ''),
  (title: 'Sentrica', synopsis: ''),
  (title: 'Sentrica Cortex', synopsis: ''),
  (title: 'Sentrinova', synopsis: ''),
  (title: 'Sentrinova Cortex', synopsis: ''),
  (title: 'Sentrion', synopsis: ''),
  (title: 'Sentrion Cortex', synopsis: ''),
  (title: 'Sentrium', synopsis: ''),
  (title: 'Sentrium Cortex', synopsis: ''),
  (title: 'Sentrius', synopsis: ''),
  (title: 'Sentrius Cortex', synopsis: ''),
  (title: 'Sentrixia', synopsis: ''),
  (title: 'Sentrixia Cortex', synopsis: ''),
  (title: 'Sentrixus', synopsis: ''),
  (title: 'Sentrixus Cortex', synopsis: ''),
  (title: 'Sentronex', synopsis: ''),
  (title: 'Sentronex Cortex', synopsis: ''),
  (title: 'Sentroniq', synopsis: ''),
  (title: 'Sentroniq Cortex', synopsis: ''),
  (title: 'Sentronova', synopsis: ''),
  (title: 'Sentronova Cortex', synopsis: ''),
  (title: 'Sentros', synopsis: ''),
  (title: 'Sentros Cortex', synopsis: ''),
  (title: 'Sentrovia', synopsis: ''),
  (title: 'Sentrovia Cortex', synopsis: ''),
  (title: 'Sentrox', synopsis: ''),
  (title: 'Sentrox Cortex', synopsis: ''),
  (title: 'Sentroxia', synopsis: ''),
  (title: 'Sentroxia Cortex', synopsis: ''),
  (title: 'Seraphina', synopsis: ''),
  (title: 'Seraphina Cortex', synopsis: ''),
  (title: 'Seraphis', synopsis: ''),
  (title: 'Seraphis Cortex', synopsis: ''),
  (title: 'Seraphix', synopsis: ''),
  (title: 'Seraphix Cortex', synopsis: ''),
  (title: 'Seraphus', synopsis: ''),
  (title: 'Seraphus Cortex', synopsis: ''),
  (title: 'Serenix', synopsis: ''),
  (title: 'Serenix Cortex', synopsis: ''),
  (title: 'Solara', synopsis: ''),
  (title: 'Solara Cortex', synopsis: ''),
  (title: 'Solarae', synopsis: ''),
  (title: 'Solarae Cortex', synopsis: ''),
  (title: 'Solaris', synopsis: ''),
  (title: 'Solaris Cortex', synopsis: ''),
  (title: 'Solis', synopsis: ''),
  (title: 'Solis Cortex', synopsis: ''),
  (title: 'Solstice', synopsis: ''),
  (title: 'Solstice Cortex', synopsis: ''),
  (title: 'Synaptiq', synopsis: ''),
  (title: 'Synaptiq Cortex', synopsis: ''),
  (title: 'Synaptronic', synopsis: ''),
  (title: 'Synaptronic Cortex', synopsis: ''),
  (title: 'Syntellect', synopsis: ''),
  (title: 'Syntellect Cortex', synopsis: ''),
  (title: 'Syntelleon', synopsis: ''),
  (title: 'Syntelleon Cortex', synopsis: ''),
  (title: 'Synthaeron', synopsis: ''),
  (title: 'Synthaeron Cortex', synopsis: ''),
  (title: 'Synthanium', synopsis: ''),
  (title: 'Synthanium Cortex', synopsis: ''),
  (title: 'Synthara', synopsis: ''),
  (title: 'Synthara Cortex', synopsis: ''),
  (title: 'Syntharium', synopsis: ''),
  (title: 'Syntharium Cortex', synopsis: ''),
  (title: 'Synthas', synopsis: ''),
  (title: 'Synthas Cortex', synopsis: ''),
  (title: 'Synthea', synopsis: ''),
  (title: 'Synthea Cortex', synopsis: ''),
  (title: 'Synthelle', synopsis: ''),
  (title: 'Synthelle Cortex', synopsis: ''),
  (title: 'Synthema', synopsis: ''),
  (title: 'Synthema Cortex', synopsis: ''),
  (title: 'Synthensia', synopsis: ''),
  (title: 'Synthensia Cortex', synopsis: ''),
  (title: 'Syntheos', synopsis: ''),
  (title: 'Syntheos Cortex', synopsis: ''),
  (title: 'Syntheria', synopsis: ''),
  (title: 'Syntheria Cortex', synopsis: ''),
  (title: 'Synthesia', synopsis: ''),
  (title: 'Synthesia Cortex', synopsis: ''),
  (title: 'Synthesys', synopsis: ''),
  (title: 'Synthesys Cortex', synopsis: ''),
  (title: 'Synthetia', synopsis: ''),
  (title: 'Synthetia Cortex', synopsis: ''),
  (title: 'Synthetica', synopsis: ''),
  (title: 'Synthetica Cortex', synopsis: ''),
  (title: 'Synthetron', synopsis: ''),
  (title: 'Synthetron Cortex', synopsis: ''),
  (title: 'Synthia', synopsis: ''),
  (title: 'Synthia Cortex', synopsis: ''),
  (title: 'Synthiax', synopsis: ''),
  (title: 'Synthiax Cortex', synopsis: ''),
  (title: 'Synthica', synopsis: ''),
  (title: 'Synthica Cortex', synopsis: ''),
  (title: 'Synthion', synopsis: ''),
  (title: 'Synthion Cortex', synopsis: ''),
  (title: 'Synthiq', synopsis: ''),
  (title: 'Synthiq Cortex', synopsis: ''),
  (title: 'Synthiquis', synopsis: ''),
  (title: 'Synthiquis Cortex', synopsis: ''),
  (title: 'Synthium', synopsis: ''),
  (title: 'Synthium Cortex', synopsis: ''),
  (title: 'Syntho Quark', synopsis: ''),
  (title: 'Syntho Vex', synopsis: ''),
  (title: 'Syntho Vox', synopsis: ''),
  (title: 'Syntho Voxia', synopsis: ''),
  (title: 'Synthoflux', synopsis: ''),
  (title: 'Synthoflux Cortex', synopsis: ''),
  (title: 'Syntholux', synopsis: ''),
  (title: 'Syntholux Cortex', synopsis: ''),
  (title: 'Syntholuxia', synopsis: ''),
  (title: 'Syntholuxia Cortex', synopsis: ''),
  (title: 'Synthophasis', synopsis: ''),
  (title: 'Synthophasis Cortex', synopsis: ''),
  (title: 'Synthor', synopsis: ''),
  (title: 'Synthor Cortex', synopsis: ''),
  (title: 'Synthora', synopsis: ''),
  (title: 'Synthora Cortex', synopsis: ''),
  (title: 'Synthorix', synopsis: ''),
  (title: 'Synthorix Cortex', synopsis: ''),
  (title: 'Synthos', synopsis: ''),
  (title: 'Synthos Cortex', synopsis: ''),
  (title: 'Synthosia', synopsis: ''),
  (title: 'Synthosio', synopsis: ''),
  (title: 'Synthria', synopsis: ''),
  (title: 'Synthrix', synopsis: ''),
  (title: 'Synthronia', synopsis: ''),
  (title: 'Synthronix', synopsis: ''),
  (title: 'Tru Cog', synopsis: ''),
  (title: 'Tru Cogi', synopsis: ''),
  (title: 'Tru Cogia', synopsis: ''),
  (title: 'Tru Sapien', synopsis: ''),
  (title: 'Uni Machia', synopsis: ''),
  (title: 'Uni Machina', synopsis: ''),
  (title: 'Uni Machinix', synopsis: ''),
  (title: 'Uni Mensa', synopsis: ''),
  (title: 'Uni Omnia', synopsis: ''),
  (title: 'Veri Cogia', synopsis: ''),
  (title: 'Vericon', synopsis: ''),
  (title: 'Veridara', synopsis: ''),
  (title: 'Veridex', synopsis: ''),
  (title: 'Veridexis', synopsis: ''),
  (title: 'Veridia', synopsis: ''),
  (title: 'Veridian', synopsis: ''),
  (title: 'Veridis', synopsis: ''),
  (title: 'Veridius', synopsis: ''),
  (title: 'Veridora', synopsis: ''),
  (title: 'Veridus', synopsis: ''),
  (title: 'Verifex', synopsis: ''),
  (title: 'Verilux', synopsis: ''),
  (title: 'Veriqus', synopsis: ''),
  (title: 'Veristria', synopsis: ''),
  (title: 'Veritara', synopsis: ''),
  (title: 'Veritauri', synopsis: ''),
  (title: 'Veritex', synopsis: ''),
  (title: 'Veritexa', synopsis: ''),
  (title: 'Veritexia', synopsis: ''),
  (title: 'Veritexis', synopsis: ''),
  (title: 'Veritium', synopsis: ''),
  (title: 'Veritrax', synopsis: ''),
  (title: 'Veritria', synopsis: ''),
  (title: 'Veritrix', synopsis: ''),
  (title: 'Veritron', synopsis: ''),
  (title: 'Veritronix', synopsis: ''),
  (title: 'Verivis', synopsis: ''),
  (title: 'Verivox', synopsis: ''),
  (title: 'Virelia', synopsis: ''),
  (title: 'Vireliax', synopsis: ''),
  (title: 'Virelis', synopsis: ''),
  (title: 'Virendra', synopsis: ''),
  (title: 'Virendrix', synopsis: ''),
  (title: 'Viridalia', synopsis: ''),
  (title: 'Viridia', synopsis: ''),
  (title: 'Zenifex', synopsis: ''),
  (title: 'Zenifexia', synopsis: ''),
  (title: 'Zenifira', synopsis: ''),
  (title: 'Zenith', synopsis: ''),
  (title: 'Zenithea', synopsis: ''),
  (title: 'Zenithia', synopsis: ''),
  (title: 'Zenithis', synopsis: ''),
  (title: 'Zephyria', synopsis: ''),
  (title: 'Zephyris', synopsis: ''),
  (title: 'Zyphin', synopsis: ''),
  (title: 'Zyphira', synopsis: ''),
  (title: 'Zyphora', synopsis: ''),
  (title: 'Zyphora Cortex', synopsis: ''),
};
