const Set<String> en = <String>{
  'Aether',
  'Aetheria',
  'Aetheria Essence',
  'Aetherial Glow',
  'Aetheris',
  'Alcyone',
  'Alcyone Glow',
  'Altair',
  'Altair Glow',
  'Altara',
  'Altaris',
  'Andromeda',
  'Andromeda Lumina',
  'Andromeda Veil',
  'Aquila',
  'Aquila Bellatrix',
  'Aquila Lyrastra',
  'Aquila Radiance',
  'Aquila Solara',
  'Aquila Solstice',
  'Aquilara',
  'Aquilaris',
  'Aquilian',
  'Aquiluna',
  'Asteria',
  'Asteria Radiance',
  'Astoria',
  'Astoria Ember',
  'Astorion',
  'Astra',
  'Astra Bellatrix',
  'Astra Lumina',
  'Astra Luminara',
  'Astra Zenithria',
  'Astradian',
  'Astradon',
  'Astradra',
  'Astraea',
  'Astraea Whisper',
  'Astraeus',
  'Astraeus Aquila',
  'Astraeus Essence',
  'Astraeus Nebularis',
  'Astraeus Phoenix',
  'Astraeus Pyranis',
  'Astraeus Solstice',
  'Astraeus Solvenna',
  'Astraeus Zephyrus',
  'Astral Alchemy',
  'Astral Belladris',
  'Astral Blossom',
  'Astral Borealis',
  'Astral Breeze',
  'Astral Cascade',
  'Astral Cascades',
  'Astral Celestia',
  'Astral Cosmos',
  'Astral Dreamer',
  'Astral Dreamscape',
  'Astral Echo',
  'Astral Echoes',
  'Astral Eclipse',
  'Astral Elixir',
  'Astral Ember',
  'Astral Enchantment',
  'Astral Enigma',
  'Astral Equinox',
  'Astral Essence',
  'Astral Guardian',
  'Astral Harmonia',
  'Astral Harmony',
  'Astral Haven',
  'Astral Horizon',
  'Astral Journey',
  'Astral Lullaby',
  'Astral Luminary',
  'Astral Lyric',
  'Astral Mirage',
  'Astral Nebulous',
  'Astral Nexus',
  'Astral Nova',
  'Astral Prism',
  'Astral Pyronova',
  'Astral Radiance',
  'Astral Reverie',
  'Astral Rhapsody',
  'Astral Seraph',
  'Astral Serenade',
  'Astral Serenity',
  'Astral Solace',
  'Astral Solstice',
  'Astral Sonata',
  'Astral Stardust',
  'Astral Symphony',
  'Astral Veil',
  'Astral Whisper',
  'Astral Zephyr',
  'Astrala',
  'Astralia',
  'Astraline',
  'Astralis',
  'Astralis Bellatrix',
  'Astralis Celestial',
  'Astralis Essence',
  'Astralis Halo',
  'Astralis Seraph',
  'Astralis Serenade',
  'Astralis Solarastra',
  'Astralis Stellarion',
  'Astralis Stellaris',
  'Astralis Zephyrana',
  'Astralyn',
  'Astralyn Luster',
  'Astranis',
  'Astrellis',
  'Astreluna',
  'Astrid',
  'Astrid Halo',
  'Astrid Luster',
  'Astridora',
  'Astrila',
  'Astriluna',
  'Astronea',
  'Astronix',
  'Astronova',
  'Auranova',
  'Aurelia',
  'Aurelia Lunaris',
  'Aurelia Nebularis',
  'Aurelia Spark',
  'Aurelian Blaze',
  'Aurelian Breeze',
  'Aurelian Cascade',
  'Aurelian Nova',
  'Aurelian Radiance',
  'Aurelian Symphony',
  'Auriel',
  'Auriel Grace',
  'Aurius',
  'Aurius Radiance',
  'Aurora',
  'Aurora Astraeus',
  'Aurora Borealis',
  'Aurora Breath',
  'Aurora Celestial',
  'Aurora Equinox',
  'Aurora Flare',
  'Aurora Harmonies',
  'Aurora Lunaris',
  'Aurora Nimbus',
  'Aurora Nova',
  'Aurora Seraphim',
  'Aurora Serenade',
  'Aurora Veil',
  'Aurora Whispers',
  'Aurorae Seraphim',
  'Auroras',
  'Auroria',
  'Auroria Vesperia',
  'Auroriana',
  'Aurorion',
  'Avalaris',
  'Avalon',
  'Avalon Aurora',
  'Avalon Celestia',
  'Avalon Horizon',
  'Avalon Whispers',
  'Avalonia',
  'Avalora',
  'Avaloria',
  'Belladra',
  'Belladris',
  'Belladris Solarastra',
  'Bellara',
  'Bellarian',
  'Bellatrix',
  'Bellatrix Aquilaris',
  'Bellatrix Gleam',
  'Bellatrix Halo',
  'Bellatrix Lunaris',
  'Bellatrixis',
  'Bellavara',
  'Bellaven',
  'Bellavox',
  'Caelum',
  'Caelum Glow',
  'Caelum Radiance',
  'Capella',
  'Capella Glow',
  'Cassarian',
  'Cassariana',
  'Cassiel',
  'Cassiel Whisper',
  'Cassiopae',
  'Cassiopeia',
  'Cassiopeia Lunarastra',
  'Cassiopeia Lyrastra',
  'Cassiopeia Veil',
  'Cassiopella',
  'Cassiopia',
  'Cassiopra',
  'Celestara',
  'Celestia',
  'Celestia Blaze',
  'Celestia Bliss',
  'Celestia Cascade',
  'Celestia Echo',
  'Celestia Eclipse',
  'Celestia Ember',
  'Celestia Equinox',
  'Celestia Luminary',
  'Celestia Lyricora',
  'Celestia Mirage',
  'Celestia Mist',
  'Celestia Nimbus',
  'Celestia Nova',
  'Celestia Prism',
  'Celestia Radiance',
  'Celestia Serenity',
  'Celestia Solstice',
  'Celestia Sylph',
  'Celestia Veil',
  'Celestia Zephyr',
  'Celestia Zephyrus',
  'Celestial Alchemy',
  'Celestial Aquila',
  'Celestial Breeze',
  'Celestial Brilliance',
  'Celestial Cascade',
  'Celestial Cosmos',
  'Celestial Dream',
  'Celestial Dreamer',
  'Celestial Echo',
  'Celestial Ember',
  'Celestial Embrace',
  'Celestial Euphoria',
  'Celestial Glow',
  'Celestial Guardian',
  'Celestial Halo',
  'Celestial Harmonia',
  'Celestial Harmony',
  'Celestial Haze',
  'Celestial Hydra',
  'Celestial Hymn',
  'Celestial Journey',
  'Celestial Lullaby',
  'Celestial Lumina',
  'Celestial Luminary',
  'Celestial Mirage',
  'Celestial Nebula',
  'Celestial Nexus',
  'Celestial Nova',
  'Celestial Pyxis',
  'Celestial Radiance',
  'Celestial Reverie',
  'Celestial Serenade',
  'Celestial Serenity',
  'Celestial Shimmer',
  'Celestial Solstice',
  'Celestial Sparkle',
  'Celestial Symphony',
  'Celestial Twilight',
  'Celestial Vortex',
  'Celestial Whisper',
  'Celestial Whispers',
  'Celestial Zephyr',
  'Celestine',
  'Celestine Astradra',
  'Celestine Astral',
  'Celestine Glow',
  'Celestine Halo',
  'Celestine Orion',
  'Celestine Orionis',
  'Celestine Pyrastra',
  'Celestine Radiance',
  'Celestine Veil',
  'Celestius',
  'Celestria',
  'Celestria Nebulia',
  'Celestrix',
  'Comet',
  'Comet Trail',
  'Cosmic Breeze',
  'Cosmic Cascade',
  'Cosmic Delight',
  'Cosmic Dream',
  'Cosmic Ember',
  'Cosmic Embrace',
  'Cosmic Harmony',
  'Cosmic Illusion',
  'Cosmic Mirage',
  'Cosmic Nova',
  'Cosmic Radiance',
  'Cosmic Serenade',
  'Cosmic Serenity',
  'Cosmic Solace',
  'Cosmic Sonnet',
  'Cosmic Symphony',
  'Cosmic Twilight',
  'Cosmic Whisper',
  'Cosmic Whispers',
  'Cosmic Zephyr',
  'Cosmo Cascade',
  'Cosmos',
  'Crystal Nebula',
  'Crystal Veil',
  'Cygnus',
  'Delphinus',
  'Delphinus Lumina',
  'Delphinus Veil',
  'Dracaris',
  'Draco',
  'Draco Astralis',
  'Draco Embrace',
  'Draco Lumina',
  'Draco Solara',
  'Dracoria',
  'Dracoria Solarastra',
  'Dracoria Solvenna',
  'Dracoria Zephyrella',
  'Dracorian',
  'Dracostra',
  'Elysara',
  'Elysaria',
  'Elysian Cascade',
  'Elysian Cosmos',
  'Elysian Ember',
  'Elysian Equinox',
  'Elysian Flare',
  'Elysian Harmony',
  'Elysian Lullaby',
  'Elysian Nebula',
  'Elysian Nebulon',
  'Elysian Nova',
  'Elysian Seraphim',
  'Elysian Serenade',
  'Elysian Solstice',
  'Elysian Stardust',
  'Elysian Symphony',
  'Elysian Twilight',
  'Elysian Whisper',
  'Elysian Whispers',
  'Elysian Zephyr',
  'Elysium',
  'Elysium Astradra',
  'Elysium Lunarastra',
  'Elysium Novastra',
  'Ember',
  'Ember Astralis',
  'Ember Blaze',
  'Ember Orionis',
  'Emberis',
  'Enchanted Harmonies',
  'Enchanted Harmony',
  'Enchanted Horizon',
  'Enchanted Nebula',
  'Enchanted Nebulosity',
  'Enchanted Nexus',
  'Enchanted Serenade',
  'Enchanted Solace',
  'Enchanted Solstice',
  'Enchanted Twilight',
  'Epsilon',
  'Epsilon Halo',
  'Epsilon Lumina',
  'Equilonis',
  'Equinova',
  'Equinox',
  'Equinox Aquilian',
  'Equinox Dracaris',
  'Equinox Pyronis',
  'Equinox Radiance',
  'Equinoxia',
  'Equinoxis',
  'Eridanis',
  'Eridanus',
  'Ethereal Cascade',
  'Ethereal Dreamer',
  'Ethereal Eclipse',
  'Ethereal Glow',
  'Ethereal Harmony',
  'Ethereal Mirage',
  'Ethereal Nebula',
  'Ethereal Nova',
  'Ethereal Radiance',
  'Ethereal Serenade',
  'Ethereal Solstice',
  'Ethereal Twilight',
  'Ethereal Whisper',
  'Ethereal Zephyr',
  'Everlight Cascade',
  'Everlight Harmony',
  'Everlight Nebulus',
  'Everlight Seraph',
  'Everlight Solara',
  'Everlight Sylph',
  'Galaxia',
  'Galaxia Breath',
  'Galaxia Enigma',
  'Galaxia Gleam',
  'Galaxia Lullaby',
  'Galaxia Song',
  'Galaxia Veil',
  'Galaxy Breeze',
  'Galaxy Cascade',
  'Galaxy Dream',
  'Galaxy Harmony',
  'Galaxy Serenade',
  'Galaxy Whisper',
  'Galaxy Zephyr',
  'Gemini',
  'Gemini Embrace',
  'Halcyon',
  'Halcyon Radiance',
  'Halcyria',
  'Helios',
  'Helios Radiant',
  'Horizon',
  'Horizon Embrace',
  'Horizonis',
  'Hydra',
  'Hydra Breath',
  'Luminara',
  'Luminara Equinox',
  'Luminara Halo',
  'Luminara Lyra',
  'Luminary Aether',
  'Luminary Aurora',
  'Luminary Cascade',
  'Luminary Dreamscape',
  'Luminary Ember',
  'Luminary Harmonies',
  'Luminary Lullaby',
  'Luminary Nexus',
  'Luminary Nova',
  'Luminary Reverie',
  'Luminary Serenade',
  'Luminary Serenity',
  'Luminary Solara',
  'Luminary Solstice',
  'Luminary Sonata',
  'Luminary Sparkle',
  'Luminary Stardust',
  'Luminary Sylph',
  'Luminary Veil',
  'Luminary Zephyrus',
  'Luminescent Cascade',
  'Luminescent Journey',
  'Luminous Dreamer',
  'Luminous Ember',
  'Luminous Glow',
  'Luminous Mirage',
  'Luminous Nebula',
  'Luminous Seraph',
  'Luminous Serenity',
  'Luminous Stardust',
  'Luminous Symphony',
  'Luminous Twilight',
  'Luminous Veil',
  'Luminous Zephyr',
  'Lumos Seraph',
  'Lumos Zephyr',
  'Luna',
  'Luna Astralis',
  'Luna Aurora',
  'Luna Cascade',
  'Luna Draco',
  'Luna Embrace',
  'Luna Equinoxis',
  'Luna Glow',
  'Luna Lumina',
  'Luna Mirage',
  'Luna Pyranis',
  'Luna Radiance',
  'Luna Serenade',
  'Luna Serenity',
  'Luna Solace',
  'Luna Solara',
  'Luna Solarastra',
  'Luna Solstice',
  'Luna Symphony',
  'Luna Veil',
  'Luna Vesperia',
  'Luna Whisper',
  'Luna Zephyr',
  'Lunar Aether',
  'Lunar Aurora',
  'Lunar Blaze',
  'Lunar Cascade',
  'Lunar Dream',
  'Lunar Elixir',
  'Lunar Ember',
  'Lunar Glimmer',
  'Lunar Harmony',
  'Lunar Ignis',
  'Lunar Mirage',
  'Lunar Nebula',
  'Lunar Nova',
  'Lunar Radiance',
  'Lunar Seraph',
  'Lunar Serenade',
  'Lunar Solstice',
  'Lunar Symphony',
  'Lunar Twilight',
  'Lunar Veil',
  'Lunar Whisper',
  'Lunar Whispers',
  'Lunar Zephyr',
  'Lunara',
  'Lunarastra',
  'Lunaria',
  'Lunaris',
  'Lunaris Alchemy',
  'Lunaris Cascade',
  'Lunaris Celestine',
  'Lunaris Ember',
  'Lunaris Harmonia',
  'Lunaris Nova',
  'Lunaris Seraph',
  'Lunaris Serenade',
  'Lunaris Symphony',
  'Lunaris Veil',
  'Luneth',
  'Lunova',
  'Lyra',
  'Lyra Altair',
  'Lyra Belladra',
  'Lyra Celestialis',
  'Lyra Equinox',
  'Lyra Halo',
  'Lyra Melody',
  'Lyra Nebula',
  'Lyra Nova',
  'Lyra Novastra',
  'Lyra Prism',
  'Lyra Solara',
  'Lyra Solstice',
  'Lyra Solsticea',
  'Lyra Stellastra',
  'Lyra Zephyrella',
  'Lyraelis',
  'Lyrastra',
  'Lyriastra',
  'Lyric',
  'Lyric Equinox',
  'Lyric Melody',
  'Lyric Nova',
  'Lyric Solara',
  'Lyric Solstice',
  'Lyricora',
  'Lyricora Astralia',
  'Lyricus',
  'Lyrielle',
  'Lyristar',
  'Lyristella',
  'Lyrius',
  'Lyroth',
  'Moonbeam Embrace',
  'Moonbeam Serenade',
  'Moonbeam Symphony',
  'Moonfire Cascade',
  'Moonfire Glimmer',
  'Moonfire Vortex',
  'Moonfire Whisper',
  'Moonlit Dreamscape',
  'Moonlit Ember',
  'Moonlit Enigma',
  'Moonlit Mirage',
  'Moonlit Nova',
  'Moonlit Prism',
  'Moonlit Radiance',
  'Moonlit Rhapsody',
  'Moonlit Serenade',
  'Moonlit Stardust',
  'Moonlit Symphony',
  'Moonlit Whisper',
  'Nebula Illusion',
  'Nebula Lumina',
  'Nebula Mist',
  'Nebula Nova',
  'Nebula Radiance',
  'Nebula Seraph',
  'Nebula Seraphim',
  'Nebula Serenity',
  'Nebula Solace',
  'Nebula Solara',
  'Nebula Solstice',
  'Nebula Solvenna',
  'Nebula Song',
  'Nebula Sparkle',
  'Nebula Stardust',
  'Nebula Symphony',
  'Nebula Twilight',
  'Nebula Veil',
  'Nebula Whisperer',
  'Nebula Whispers',
  'Nebulaic Radiance',
  'Nebulaic Realm',
  'Nebularis',
  'Nebulia',
  'Nebulon',
  'Nebulon Luster',
  'Nimbus',
  'Nimbus Radiance',
  'Nocturna',
  'Nocturna Lumina',
  'Novastra',
  'Novastris',
  'Ophelia',
  'Ophelia Veil',
  'Orinthia',
  'Orion',
  'Orion Glow',
  'Orion Halo',
  'Orion Luminary',
  'Orion Lunastra',
  'Orion Lyra',
  'Orion Path',
  'Orion Serenade',
  'Orion Solstice',
  'Orion Vesperia',
  'Orionia',
  'Orionis',
  'Orionis Nebula',
  'Phoenixia',
  'Phoenixia Flame',
  'Pyranis',
  'Pyranova',
  'Pyranova Stellaris',
  'Pyraphina',
  'Pyrastra',
  'Pyrastra Lunaria',
  'Pyrenis',
  'Pyro Nebula',
  'Pyro Novastra',
  'Pyronis',
  'Pyronis Avalaris',
  'Pyronis Lunarastra',
  'Pyronis Solsticea',
  'Pyronova',
  'Pyrora',
  'Pyrovia',
  'Pyrrus',
  'Pyxis',
  'Pyxis Aurora',
  'Pyxis Lumina',
  'Pyxis Nebulae',
  'Pyxis Twilight',
  'Radiant Aurora',
  'Radiant Borealis',
  'Radiant Cascade',
  'Radiant Dream',
  'Radiant Dreamer',
  'Radiant Dreams',
  'Radiant Dreamscape',
  'Radiant Echo',
  'Radiant Eclipse',
  'Radiant Ember',
  'Radiant Enigma',
  'Radiant Flare',
  'Radiant Harmony',
  'Radiant Horizon',
  'Radiant Lunar',
  'Radiant Nebula',
  'Radiant Nexus',
  'Radiant Nimbus',
  'Radiant Nova',
  'Radiant Prism',
  'Radiant Radiance',
  'Radiant Serenade',
  'Radiant Solara',
  'Radiant Solstice',
  'Radiant Stardust',
  'Radiant Symphony',
  'Radiant Twilight',
  'Radiant Whisper',
  'Radiant Zephyr',
  'Selene',
  'Selene Glow',
  'Selene Vesperis',
  'Seluna',
  'Selunara',
  'Selunaris',
  'Seranis',
  'Seraph',
  'Seraph Avaloria',
  'Seraph Novastra',
  'Seraph Orionis',
  'Serapheus',
  'Seraphic Alchemy',
  'Seraphic Blaze',
  'Seraphic Breeze',
  'Seraphic Cascade',
  'Seraphic Celestia',
  'Seraphic Echo',
  'Seraphic Eclipse',
  'Seraphic Ember',
  'Seraphic Harmonies',
  'Seraphic Luminara',
  'Seraphic Lyra',
  'Seraphic Nova',
  'Seraphic Radiance',
  'Seraphic Serenade',
  'Seraphic Solstice',
  'Seraphic Symphony',
  'Seraphic Twilight',
  'Seraphic Zephyrus',
  'Seraphina',
  'Seraphina Grace',
  'Seraphira',
  'Seraphis',
  'Serenara',
  'Serenaris',
  'Serene Aether',
  'Serene Bellatrix',
  'Serene Lyra',
  'Serene Seraphim',
  'Serene Solara',
  'Serene Solstice',
  'Serenith',
  'Serenity',
  'Serenity Astrala',
  'Serenity Aurora',
  'Serenity Grace',
  'Serenity Lunastra',
  'Serenity Lyra',
  'Serenity Nebulae',
  'Serenity Nebulon',
  'Sirius',
  'Sirius Lumina',
  'Solar Eclipse',
  'Solar Enchantment',
  'Solar Flame',
  'Solar Flare',
  'Solar Radiance',
  'Solar Sylph',
  'Solar Whisper',
  'Solara',
  'Solara Aether',
  'Solara Astralia',
  'Solara Aurora',
  'Solara Cascade',
  'Solara Celestria',
  'Solara Embrace',
  'Solara Enigma',
  'Solara Equinoxis',
  'Solara Halo',
  'Solara Harmonia',
  'Solara Light',
  'Solara Nebulae',
  'Solara Nebulon',
  'Solara Nova',
  'Solara Serenity',
  'Solara Stardust',
  'Solara Vortex',
  'Solara Whisper',
  'Solarastra',
  'Solariel',
  'Solarion',
  'Solaris',
  'Solaris Aether',
  'Solaris Blaze',
  'Solaris Borealis',
  'Solaris Breeze',
  'Solaris Dreamer',
  'Solaris Embrace',
  'Solaris Enigma',
  'Solaris Flame',
  'Solaris Harmonies',
  'Solaris Harmony',
  'Solaris Ignis',
  'Solaris Mirage',
  'Solaris Nebulous',
  'Solaris Nova',
  'Solaris Seraphim',
  'Solaris Serenade',
  'Solaris Solstice',
  'Solaris Symphony',
  'Solaris Twilight',
  'Solaris Veil',
  'Solaris Whisper',
  'Solarius',
  'Solarnova',
  'Solstaria',
  'Solstice',
  'Solstice Aria',
  'Solstice Aurora',
  'Solstice Blaze',
  'Solstice Cassiopra',
  'Solstice Celestia',
  'Solstice Echo',
  'Solstice Ember',
  'Solstice Luminary',
  'Solstice Luna',
  'Solstice Lunar',
  'Solstice Nova',
  'Solstice Phoenix',
  'Solstice Radiance',
  'Solstice Seraph',
  'Solstice Seraphim',
  'Solstice Serenade',
  'Solstice Sylph',
  'Solstice Zephyr',
  'Solsticea',
  'Solvenna',
  'Starborn Enchantment',
  'Starborn Flame',
  'Starborn Radiance',
  'Stardance',
  'Stardust',
  'Stardust Alchemy',
  'Stardust Aurora',
  'Stardust Blaze',
  'Stardust Breeze',
  'Stardust Cascade',
  'Stardust Celestia',
  'Stardust Dreamer',
  'Stardust Echo',
  'Stardust Ember',
  'Stardust Glow',
  'Stardust Harmonies',
  'Stardust Harmony',
  'Stardust Hydra',
  'Stardust Labyrinth',
  'Stardust Lullaby',
  'Stardust Luminary',
  'Stardust Lunar',
  'Stardust Lyrastra',
  'Stardust Mirage',
  'Stardust Nebulon',
  'Stardust Nebulus',
  'Stardust Nimbus',
  'Stardust Prism',
  'Stardust Radiance',
  'Stardust Reverie',
  'Stardust Seraph',
  'Stardust Seraphim',
  'Stardust Serenade',
  'Stardust Serenith',
  'Stardust Solstice',
  'Stardust Sonnet',
  'Stardust Stellaris',
  'Stardust Symphony',
  'Stardust Twilight',
  'Stardust Veil',
  'Stardust Whisper',
  'Stardust Whispers',
  'Stardust Zephyr',
  'Starfire Nova',
  'Starfire Symphony',
  'Starforge',
  'Stargazer Bliss',
  'Stargazer Breeze',
  'Stargazer Chorus',
  'Stargazer Dream',
  'Stargazer Serenade',
  'Stargazer Symphony',
  'Starlight Cascade',
  'Starlight Dreamscape',
  'Starlight Elixir',
  'Starlight Illusion',
  'Starlight Sonata',
  'Starlit Mirage',
  'Starlit Radiance',
  'Starlit Shimmer',
  'Starlit Symphony',
  'Stellar Aurora',
  'Stellar Blossom',
  'Stellar Breeze',
  'Stellar Cascade',
  'Stellar Dream',
  'Stellar Dreamer',
  'Stellar Dreamscape',
  'Stellar Eclipse',
  'Stellar Ember',
  'Stellar Enigma',
  'Stellar Essence',
  'Stellar Flare',
  'Stellar Glow',
  'Stellar Harmonies',
  'Stellar Harmony',
  'Stellar Lullaby',
  'Stellar Luminary',
  'Stellar Melody',
  'Stellar Nexus',
  'Stellar Nova',
  'Stellar Rhapsody',
  'Stellar Seraph',
  'Stellar Serenade',
  'Stellar Serenity',
  'Stellar Solstice',
  'Stellar Sylph',
  'Stellar Symphony',
  'Stellar Twilight',
  'Stellar Veil',
  'Stellar Whisper',
  'Stellar Zephyr',
  'Stellara Astralis',
  'Stellara Mist',
  'Stellara Solara',
  'Stellara Solstice',
  'Stellara Stardust',
  'Stellarion',
  'Stellaris',
  'Stellaris Nebulia',
  'Stellastra',
  'Stellastra Aquilaris',
  'Sylph',
  'Sylphic Mist',
  'Twilight',
  'Twilight Aurora',
  'Twilight Borealis',
  'Twilight Breeze',
  'Twilight Cascade',
  'Twilight Dream',
  'Twilight Ember',
  'Twilight Enigma',
  'Twilight Equinox',
  'Twilight Eternity',
  'Twilight Euphoria',
  'Twilight Flare',
  'Twilight Harmony',
  'Twilight Haven',
  'Twilight Haze',
  'Twilight Luminary',
  'Twilight Lyric',
  'Twilight Melody',
  'Twilight Mirage',
  'Twilight Mist',
  'Twilight Nebula',
  'Twilight Nebulae',
  'Twilight Nebulosity',
  'Twilight Nova',
  'Twilight Prism',
  'Twilight Radiance',
  'Twilight Reverie',
  'Twilight Seraph',
  'Twilight Serenade',
  'Twilight Shimmer',
  'Twilight Solara',
  'Twilight Solstice',
  'Twilight Sonata',
  'Twilight Sparkle',
  'Twilight Stardust',
  'Twilight Sylph',
  'Twilight Symphony',
  'Twilight Veil',
  'Twilight Whisper',
  'Twilight Zephyr',
  'Vega',
  'Vega Luster',
  'Vega Sparkle',
  'Vesper',
  'Vesperia',
  'Vesperion',
  'Vesperis',
  'Vesperis Serenith',
  'Zenith',
  'Zenith Glow',
  'Zenithra',
  'Zenithria',
  'Zephyr',
  'Zephyr Avaloria',
  'Zephyr Breath',
  'Zephyr Cascade',
  'Zephyr Dreamscape',
  'Zephyr Embrace',
  'Zephyr Harmony',
  'Zephyr Luminary',
  'Zephyr Nebula',
  'Zephyr Nebulae',
  'Zephyr Nova',
  'Zephyr Orionis',
  'Zephyr Pyrastra',
  'Zephyr Radiance',
  'Zephyr Seraph',
  'Zephyr Serenade',
  'Zephyr Solara',
  'Zephyr Song',
  'Zephyra',
  'Zephyrana',
  'Zephyrella',
  'Zephyrella Nebulia',
  'Zephyrena',
  'Zephyria',
  'Zephyria Whispers',
  'Zephyrian',
  'Zephyris',
  'Zephyrith',
  'Zephyrus',
  'Zephyrus Aurora',
  'Zephyrus Auroria',
  'Zephyrus Prism',
  'Zephyrus Solsticea',
  'Zephyrus Whirl',
  'Zodiac Hydra',
  'Zodiac Serenity',
  'Zodiac Solstice',
  'Zodiac Stardust',
  'Zodiac Zephyr',
};
