import '../name_r.dart';

const Set<NameR> en = {
  (name: 'Adaleko', synopsis: ''),
  (name: 'Adarak', synopsis: ''),
  (name: 'Adyke', synopsis: ''),
  (name: 'Aerilon', synopsis: ''),
  (name: 'Aeris', synopsis: ''),
  (name: 'Aerith', synopsis: ''),
  (name: 'Aeterna', synopsis: ''),
  (name: 'Aetherea', synopsis: ''),
  (name: 'Aethereon', synopsis: ''),
  (name: 'Aetheria', synopsis: ''),
  (name: 'Aetherion', synopsis: ''),
  (name: 'Aetherion Reach', synopsis: ''),
  (name: 'Aetheris', synopsis: ''),
  (name: 'Aetherium', synopsis: ''),
  (name: 'Aetherium Citadel', synopsis: ''),
  (name: 'Aetherium Etheria', synopsis: ''),
  (name: 'Aetherius', synopsis: ''),
  (name: 'Aetherlight', synopsis: ''),
  (name: 'Aetheron', synopsis: ''),
  (name: 'Agamar', synopsis: ''),
  (name: 'Ahebos', synopsis: ''),
  (name: 'Akeon', synopsis: ''),
  (name: 'Akippe', synopsis: ''),
  (name: 'Alaris', synopsis: ''),
  (name: 'Alazar', synopsis: ''),
  (name: 'Alderaan', synopsis: ''),
  (name: 'Alfadus', synopsis: ''),
  (name: 'Altair', synopsis: ''),
  (name: 'Alzoc', synopsis: ''),
  (name: 'Amethyst', synopsis: ''),
  (name: 'Amides', synopsis: ''),
  (name: 'Andoria', synopsis: ''),
  (name: 'Andromeda', synopsis: ''),
  (name: 'Angichi', synopsis: ''),
  (name: 'Anrigantu', synopsis: ''),
  (name: 'Antus', synopsis: ''),
  (name: 'Aolara', synopsis: ''),
  (name: 'Apollonia', synopsis: ''),
  (name: 'Aquafire', synopsis: ''),
  (name: 'Aqualis', synopsis: ''),
  (name: 'Aqualuna', synopsis: ''),
  (name: 'Aquara', synopsis: ''),
  (name: 'Aquaradia', synopsis: ''),
  (name: 'Aquaria', synopsis: ''),
  (name: 'Aquaria Enclave', synopsis: ''),
  (name: 'Aquaria Maris', synopsis: ''),
  (name: 'Aquaria Serene', synopsis: ''),
  (name: 'Aquaria Vale', synopsis: ''),
  (name: 'Aquaria Veil', synopsis: ''),
  (name: 'Aquariis', synopsis: ''),
  (name: 'Aquarion', synopsis: ''),
  (name: 'Aquarion Vale', synopsis: ''),
  (name: 'Aquaris', synopsis: ''),
  (name: 'Aquaterra', synopsis: ''),
  (name: 'Aquaterra Aquilon', synopsis: ''),
  (name: 'Aquaterra Enigma', synopsis: ''),
  (name: 'Aquila', synopsis: ''),
  (name: 'Aquilis', synopsis: ''),
  (name: 'Aquilon', synopsis: ''),
  (name: 'Aquilonia', synopsis: ''),
  (name: 'Aquilonis', synopsis: ''),
  (name: 'Aquilonis Enigma', synopsis: ''),
  (name: 'Aquilonis Terra', synopsis: ''),
  (name: 'Aquilonis Vale', synopsis: ''),
  (name: 'Aracnus', synopsis: ''),
  (name: 'Arboria', synopsis: ''),
  (name: 'Arcadia', synopsis: ''),
  (name: 'Arcana', synopsis: ''),
  (name: 'Arcana Mysticus', synopsis: ''),
  (name: 'Arcane', synopsis: ''),
  (name: 'Arcanis', synopsis: ''),
  (name: 'Arcanis Enclave', synopsis: ''),
  (name: 'Arcanis Vale', synopsis: ''),
  (name: 'Arcanith', synopsis: ''),
  (name: 'Arcanor', synopsis: ''),
  (name: 'Arcanor Glade', synopsis: ''),
  (name: 'Arcanor Vale', synopsis: ''),
  (name: 'Arcanora', synopsis: ''),
  (name: 'Arcanora Enclave', synopsis: ''),
  (name: 'Arcanox', synopsis: ''),
  (name: 'Arcantheon', synopsis: ''),
  (name: 'Arcantheon Ember', synopsis: ''),
  (name: 'Arcanum', synopsis: ''),
  (name: 'Arcanum Mystica', synopsis: ''),
  (name: 'Ardentia', synopsis: ''),
  (name: 'Ardentia Flame', synopsis: ''),
  (name: 'Aria', synopsis: ''),
  (name: 'Aridia', synopsis: ''),
  (name: 'Aroria', synopsis: ''),
  (name: 'Arorix', synopsis: ''),
  (name: 'Astoria', synopsis: ''),
  (name: 'Astra', synopsis: ''),
  (name: 'Astraal', synopsis: ''),
  (name: 'Astraal Fall', synopsis: ''),
  (name: 'Astradus', synopsis: ''),
  (name: 'Astradus Aether', synopsis: ''),
  (name: 'Astrafall', synopsis: ''),
  (name: 'Astrafira', synopsis: ''),
  (name: 'Astrafira Enclave', synopsis: ''),
  (name: 'Astrafira Vale', synopsis: ''),
  (name: 'Astrafire', synopsis: ''),
  (name: 'Astrafire Enigma', synopsis: ''),
  (name: 'Astrafyre', synopsis: ''),
  (name: 'Astrafyre Ember', synopsis: ''),
  (name: 'Astrafyre Enclave', synopsis: ''),
  (name: 'Astrafyre Glade', synopsis: ''),
  (name: 'Astrafyre Vale', synopsis: ''),
  (name: 'Astral Fire', synopsis: ''),
  (name: 'Astraldus', synopsis: ''),
  (name: 'Astralia', synopsis: ''),
  (name: 'Astralia Veil', synopsis: ''),
  (name: 'Astralis', synopsis: ''),
  (name: 'Astralisia', synopsis: ''),
  (name: 'Astralyn', synopsis: ''),
  (name: 'Astrastra', synopsis: ''),
  (name: 'Astravia', synopsis: ''),
  (name: 'Astridae', synopsis: ''),
  (name: 'Astridae Dawn', synopsis: ''),
  (name: 'Astriline', synopsis: ''),
  (name: 'Astrilis', synopsis: ''),
  (name: 'Astrilis Luminis', synopsis: ''),
  (name: 'Astrion', synopsis: ''),
  (name: 'Astrion Eclipse', synopsis: ''),
  (name: 'Astrion Vale', synopsis: ''),
  (name: 'Astrionis', synopsis: ''),
  (name: 'Astrionyx', synopsis: ''),
  (name: 'Astrionyx Glade', synopsis: ''),
  (name: 'Astro', synopsis: ''),
  (name: 'Astronaris', synopsis: ''),
  (name: 'Astronaris Astral', synopsis: ''),
  (name: 'Astronia', synopsis: ''),
  (name: 'Astronia Glade', synopsis: ''),
  (name: 'Astronia Prism', synopsis: ''),
  (name: 'Astroniax', synopsis: ''),
  (name: 'Astroniax Vale', synopsis: ''),
  (name: 'Astronus', synopsis: ''),
  (name: 'Astronyx', synopsis: ''),
  (name: 'Astronyx Lunara', synopsis: ''),
  (name: 'Astronyx Reach', synopsis: ''),
  (name: 'Astroria', synopsis: ''),
  (name: 'Astrum', synopsis: ''),
  (name: 'Astrum Cosmo', synopsis: ''),
  (name: 'Astrum Cosmos', synopsis: ''),
  (name: 'Athilles', synopsis: ''),
  (name: 'Athora', synopsis: ''),
  (name: 'Atune', synopsis: ''),
  (name: 'Auriel', synopsis: ''),
  (name: 'Auroria', synopsis: ''),
  (name: 'Aurorium', synopsis: ''),
  (name: 'Aurorium Lumyn', synopsis: ''),
  (name: 'Aurorium Realm', synopsis: ''),
  (name: 'Auros', synopsis: ''),
  (name: 'Aurum', synopsis: ''),
  (name: 'Auryn', synopsis: ''),
  (name: 'Auryn Twilight', synopsis: ''),
  (name: 'Azimuth', synopsis: ''),
  (name: 'Aziri', synopsis: ''),
  (name: 'Azulon', synopsis: ''),
  (name: 'Azura', synopsis: ''),
  (name: 'Azuran', synopsis: ''),
  (name: 'Azurea', synopsis: ''),
  (name: 'Azurelith', synopsis: ''),
  (name: 'Azurexis', synopsis: ''),
  (name: 'Azurya', synopsis: ''),
  (name: 'Bacarro', synopsis: ''),
  (name: 'Baiwei', synopsis: ''),
  (name: 'Baniri', synopsis: ''),
  (name: 'Bantalador', synopsis: ''),
  (name: 'Barisa', synopsis: ''),
  (name: 'Belore', synopsis: ''),
  (name: 'Belsana', synopsis: ''),
  (name: 'Beron', synopsis: ''),
  (name: 'Bespin', synopsis: ''),
  (name: 'Bisapus', synopsis: ''),
  (name: 'Bithowei', synopsis: ''),
  (name: 'Bliss', synopsis: ''),
  (name: 'Blue', synopsis: ''),
  (name: 'Bolaris', synopsis: ''),
  (name: 'Boxora', synopsis: ''),
  (name: 'Brapus', synopsis: ''),
  (name: 'Brara', synopsis: ''),
  (name: 'Breen', synopsis: ''),
  (name: 'Bretihines', synopsis: ''),
  (name: 'Brinda', synopsis: ''),
  (name: 'Brolnaistea', synopsis: ''),
  (name: 'Broxitera', synopsis: ''),
  (name: 'Brurn', synopsis: ''),
  (name: 'Bunvogantu', synopsis: ''),
  (name: 'Buphobos', synopsis: ''),
  (name: 'Caelis', synopsis: ''),
  (name: 'Caelum', synopsis: ''),
  (name: 'Caldonia', synopsis: ''),
  (name: 'Calmov', synopsis: ''),
  (name: 'Calypso', synopsis: ''),
  (name: 'Camrina', synopsis: ''),
  (name: 'Capricornus', synopsis: ''),
  (name: 'Celea', synopsis: ''),
  (name: 'Celea Vale', synopsis: ''),
  (name: 'Celeia', synopsis: ''),
  (name: 'Celeia Glade', synopsis: ''),
  (name: 'Celeia Vale', synopsis: ''),
  (name: 'Celestalis', synopsis: ''),
  (name: 'Celestalis Stellis', synopsis: ''),
  (name: 'Celesterra', synopsis: ''),
  (name: 'Celestia', synopsis: ''),
  (name: 'Celestial Ember', synopsis: ''),
  (name: 'Celestion', synopsis: ''),
  (name: 'Celestion Celestis', synopsis: ''),
  (name: 'Celestora', synopsis: ''),
  (name: 'Celestora Glade', synopsis: ''),
  (name: 'Celestoria', synopsis: ''),
  (name: 'Celestra', synopsis: ''),
  (name: 'Celestra Astoria', synopsis: ''),
  (name: 'Celestria', synopsis: ''),
  (name: 'Celestriax', synopsis: ''),
  (name: 'Celestris', synopsis: ''),
  (name: 'Celestrosa', synopsis: ''),
  (name: 'Centauri', synopsis: ''),
  (name: 'Cepra', synopsis: ''),
  (name: 'Cethea', synopsis: ''),
  (name: 'Cethenope', synopsis: ''),
  (name: 'Ceti', synopsis: ''),
  (name: 'Chacarvis', synopsis: ''),
  (name: 'Chagriaclite', synopsis: ''),
  (name: 'Charvis', synopsis: ''),
  (name: 'Chestrarth', synopsis: ''),
  (name: 'Chinda', synopsis: ''),
  (name: 'Choria', synopsis: ''),
  (name: 'Chosie', synopsis: ''),
  (name: 'Chov', synopsis: ''),
  (name: 'Chromis', synopsis: ''),
  (name: 'Chrona', synopsis: ''),
  (name: 'Chronos', synopsis: ''),
  (name: 'Chubrara', synopsis: ''),
  (name: 'Chuiruta', synopsis: ''),
  (name: 'Cicero', synopsis: ''),
  (name: 'Cichehines', synopsis: ''),
  (name: 'Cinderspire', synopsis: ''),
  (name: 'Cinoth', synopsis: ''),
  (name: 'Cippe', synopsis: ''),
  (name: 'Codrarth', synopsis: ''),
  (name: 'Cortinas', synopsis: ''),
  (name: 'Coruscant', synopsis: ''),
  (name: 'Corzor', synopsis: ''),
  (name: 'Cothorix', synopsis: ''),
  (name: 'Cov', synopsis: ''),
  (name: 'Crapus', synopsis: ''),
  (name: 'Crichi', synopsis: ''),
  (name: 'Criea', synopsis: ''),
  (name: 'Crinacury', synopsis: ''),
  (name: 'Crounus', synopsis: ''),
  (name: 'Cryke', synopsis: ''),
  (name: 'Crystallis', synopsis: ''),
  (name: 'Cuhavis', synopsis: ''),
  (name: 'Cungore', synopsis: ''),
  (name: 'Cunrars', synopsis: ''),
  (name: 'Cygnus', synopsis: ''),
  (name: 'Cyrana', synopsis: ''),
  (name: 'Cyrulas', synopsis: ''),
  (name: 'Dade', synopsis: ''),
  (name: 'Daeliv', synopsis: ''),
  (name: 'Dapus', synopsis: ''),
  (name: 'Dars', synopsis: ''),
  (name: 'Darus', synopsis: ''),
  (name: 'Dathomir', synopsis: ''),
  (name: 'Davinda', synopsis: ''),
  (name: 'Denides', synopsis: ''),
  (name: 'Denkerth', synopsis: ''),
  (name: 'Desolata', synopsis: ''),
  (name: 'Diea', synopsis: ''),
  (name: 'Diyilia', synopsis: ''),
  (name: 'Doanope', synopsis: ''),
  (name: 'Dograiruta', synopsis: ''),
  (name: 'Doloulea', synopsis: ''),
  (name: 'Draconis', synopsis: ''),
  (name: 'Drakoria', synopsis: ''),
  (name: 'Draoria', synopsis: ''),
  (name: 'Drehiri', synopsis: ''),
  (name: 'Dresuturn', synopsis: ''),
  (name: 'Drethuhiri', synopsis: ''),
  (name: 'Dricarro', synopsis: ''),
  (name: 'Drides', synopsis: ''),
  (name: 'Driea', synopsis: ''),
  (name: 'Drilora', synopsis: ''),
  (name: 'Drion', synopsis: ''),
  (name: 'Drippe', synopsis: ''),
  (name: 'Drixetera', synopsis: ''),
  (name: 'Dromia', synopsis: ''),
  (name: 'Drore', synopsis: ''),
  (name: 'Drorth', synopsis: ''),
  (name: 'Droutera', synopsis: ''),
  (name: 'Druinov', synopsis: ''),
  (name: 'Drypso', synopsis: ''),
  (name: 'Dua', synopsis: ''),
  (name: 'Dumavis', synopsis: ''),
  (name: 'Dumeron', synopsis: ''),
  (name: 'Dundeon', synopsis: ''),
  (name: 'Duntana', synopsis: ''),
  (name: 'Dusta', synopsis: ''),
  (name: 'Dustraphus', synopsis: ''),
  (name: 'Dustria', synopsis: ''),
  (name: 'Dypso', synopsis: ''),
  (name: 'Ebonara', synopsis: ''),
  (name: 'Ebonara Nocturna', synopsis: ''),
  (name: 'Ebonara Shadowgate', synopsis: ''),
  (name: 'Ebonara Twilight', synopsis: ''),
  (name: 'Ebonis', synopsis: ''),
  (name: 'Ebrarth', synopsis: ''),
  (name: 'Eclipsis', synopsis: ''),
  (name: 'Eden', synopsis: ''),
  (name: 'Edenia', synopsis: ''),
  (name: 'Edenis', synopsis: ''),
  (name: 'Edyria', synopsis: ''),
  (name: 'Eirene', synopsis: ''),
  (name: 'Eitur', synopsis: ''),
  (name: 'Elaris', synopsis: ''),
  (name: 'Eldoria', synopsis: ''),
  (name: 'Eldorium', synopsis: ''),
  (name: 'Eldrune', synopsis: ''),
  (name: 'Elethria', synopsis: ''),
  (name: 'Elethria Celestia', synopsis: ''),
  (name: 'Elethria Zephyr', synopsis: ''),
  (name: 'Elyria', synopsis: ''),
  (name: 'Elysar Veil', synopsis: ''),
  (name: 'Elysara', synopsis: ''),
  (name: 'Elysaria', synopsis: ''),
  (name: 'Elysaria Glade', synopsis: ''),
  (name: 'Elysia', synopsis: ''),
  (name: 'Elysia Glade', synopsis: ''),
  (name: 'Elysia Oasis', synopsis: ''),
  (name: 'Elysira', synopsis: ''),
  (name: 'Elysira Auriel', synopsis: ''),
  (name: 'Elysium', synopsis: ''),
  (name: 'Elysium Oasis', synopsis: ''),
  (name: 'Elysium Radiance', synopsis: ''),
  (name: 'Elysium Reach', synopsis: ''),
  (name: 'Elysium Veil', synopsis: ''),
  (name: 'Elysiuma', synopsis: ''),
  (name: 'Elysora', synopsis: ''),
  (name: 'Elyssar', synopsis: ''),
  (name: 'Elyssar Veil', synopsis: ''),
  (name: 'Elyssaria', synopsis: ''),
  (name: 'Elyssaria Glade', synopsis: ''),
  (name: 'Elyssia', synopsis: ''),
  (name: 'Emberia', synopsis: ''),
  (name: 'Emberon', synopsis: ''),
  (name: 'Eminiar', synopsis: ''),
  (name: 'Empyrea', synopsis: ''),
  (name: 'Empyreal', synopsis: ''),
  (name: 'Empyrealis', synopsis: ''),
  (name: 'Empyrean', synopsis: ''),
  (name: 'Endor', synopsis: ''),
  (name: 'Enigma', synopsis: ''),
  (name: 'Epheastea', synopsis: ''),
  (name: 'Epsilon', synopsis: ''),
  (name: 'Equinox', synopsis: ''),
  (name: 'Eridani', synopsis: ''),
  (name: 'Eridani Echo', synopsis: ''),
  (name: 'Eridanus', synopsis: ''),
  (name: 'Erkit', synopsis: ''),
  (name: 'Esomia', synopsis: ''),
  (name: 'Estrade', synopsis: ''),
  (name: 'Eternis', synopsis: ''),
  (name: 'Etheria', synopsis: ''),
  (name: 'Ethichi', synopsis: ''),
  (name: 'Etion', synopsis: ''),
  (name: 'Eturn', synopsis: ''),
  (name: 'Euphoria', synopsis: ''),
  (name: 'Exilon', synopsis: ''),
  (name: 'Exilon Astrae', synopsis: ''),
  (name: 'Exousia', synopsis: ''),
  (name: 'Eziastea', synopsis: ''),
  (name: 'Fazanama', synopsis: ''),
  (name: 'Felsen', synopsis: ''),
  (name: 'Fumus', synopsis: ''),
  (name: 'Gachuilia', synopsis: ''),
  (name: 'Gaia', synopsis: ''),
  (name: 'Galactra', synopsis: ''),
  (name: 'Galactra Reach', synopsis: ''),
  (name: 'Galatea', synopsis: ''),
  (name: 'Galor', synopsis: ''),
  (name: 'Gamadon', synopsis: ''),
  (name: 'Garilia', synopsis: ''),
  (name: 'Garvis', synopsis: ''),
  (name: 'Gatheron', synopsis: ''),
  (name: 'Gathiolea', synopsis: ''),
  (name: 'Gebippe', synopsis: ''),
  (name: 'Gelida', synopsis: ''),
  (name: 'Geonosis', synopsis: ''),
  (name: 'Gephahines', synopsis: ''),
  (name: 'Geron', synopsis: ''),
  (name: 'Gevora', synopsis: ''),
  (name: 'Gezephus', synopsis: ''),
  (name: 'Giggadon', synopsis: ''),
  (name: 'Gildor', synopsis: ''),
  (name: 'Gilea', synopsis: ''),
  (name: 'Gnao', synopsis: ''),
  (name: 'Gnichinope', synopsis: ''),
  (name: 'Gnilia', synopsis: ''),
  (name: 'Gnosie', synopsis: ''),
  (name: 'Gnulmoturn', synopsis: ''),
  (name: 'Gnurn', synopsis: ''),
  (name: 'Gnyke', synopsis: ''),
  (name: 'Gohihines', synopsis: ''),
  (name: 'Gosie', synopsis: ''),
  (name: 'Gragua', synopsis: ''),
  (name: 'Griri', synopsis: ''),
  (name: 'Grosehiri', synopsis: ''),
  (name: 'Gruyiter', synopsis: ''),
  (name: 'Gurn', synopsis: ''),
  (name: 'Hagel', synopsis: ''),
  (name: 'Hamazar', synopsis: ''),
  (name: 'Hegantu', synopsis: ''),
  (name: 'Helionis', synopsis: ''),
  (name: 'Helix', synopsis: ''),
  (name: 'Hion', synopsis: ''),
  (name: 'Hiptaron', synopsis: ''),
  (name: 'Horizon', synopsis: ''),
  (name: 'Horizon Solis', synopsis: ''),
  (name: 'Hosnian', synopsis: ''),
  (name: 'Hoth', synopsis: ''),
  (name: 'Hubborth', synopsis: ''),
  (name: 'Hydraxis', synopsis: ''),
  (name: 'Hydria', synopsis: ''),
  (name: 'Hydronis', synopsis: ''),
  (name: 'Hydronis Aquatica', synopsis: ''),
  (name: 'Hydronis Reach', synopsis: ''),
  (name: 'Hydrora', synopsis: ''),
  (name: 'Hydros', synopsis: ''),
  (name: 'Ia', synopsis: ''),
  (name: 'Ibbongo', synopsis: ''),
  (name: 'Ibreon', synopsis: ''),
  (name: 'Icarus', synopsis: ''),
  (name: 'Ignis', synopsis: ''),
  (name: 'Igolla', synopsis: ''),
  (name: 'Ikadus', synopsis: ''),
  (name: 'Iketer', synopsis: ''),
  (name: 'Illizar', synopsis: ''),
  (name: 'Imperium', synopsis: ''),
  (name: 'Inorth', synopsis: ''),
  (name: 'Insomnes', synopsis: ''),
  (name: 'Ipharth', synopsis: ''),
  (name: 'Iphuatov', synopsis: ''),
  (name: 'Iroria', synopsis: ''),
  (name: 'Itania', synopsis: ''),
  (name: 'Iutov', synopsis: ''),
  (name: 'Ivion', synopsis: ''),
  (name: 'Ixippe', synopsis: ''),
  (name: 'Izeon', synopsis: ''),
  (name: 'Jakku', synopsis: ''),
  (name: 'Janus', synopsis: ''),
  (name: 'Jillamar', synopsis: ''),
  (name: 'Jiplamar', synopsis: ''),
  (name: 'Jutrar', synopsis: ''),
  (name: 'Kallamatar', synopsis: ''),
  (name: 'Kedurn', synopsis: ''),
  (name: 'Kef', synopsis: ''),
  (name: 'Kegawa', synopsis: ''),
  (name: 'Kemazar', synopsis: ''),
  (name: 'Keria', synopsis: ''),
  (name: 'Kessel', synopsis: ''),
  (name: 'Ketera', synopsis: ''),
  (name: 'Kietera', synopsis: ''),
  (name: 'Kilia', synopsis: ''),
  (name: 'Krios', synopsis: ''),
  (name: 'Kumia', synopsis: ''),
  (name: 'Kuphuegantu', synopsis: ''),
  (name: 'Kuriuq', synopsis: ''),
  (name: 'Kustruna', synopsis: ''),
  (name: 'Kutmoria', synopsis: ''),
  (name: 'Ladenia', synopsis: ''),
  (name: 'Laetania', synopsis: ''),
  (name: 'Lakas', synopsis: ''),
  (name: 'Lecarro', synopsis: ''),
  (name: 'Lenia', synopsis: ''),
  (name: 'Leos', synopsis: ''),
  (name: 'Leron', synopsis: ''),
  (name: 'Lianrorix', synopsis: ''),
  (name: 'Lis', synopsis: ''),
  (name: 'Llanocury', synopsis: ''),
  (name: 'Llia', synopsis: ''),
  (name: 'Llizicarro', synopsis: ''),
  (name: 'Llore', synopsis: ''),
  (name: 'Lonadus', synopsis: ''),
  (name: 'Lorth', synopsis: ''),
  (name: 'Lothal', synopsis: ''),
  (name: 'Lotho', synopsis: ''),
  (name: 'Lougantu', synopsis: ''),
  (name: 'Lreus Zeta', synopsis: ''),
  (name: 'Lua', synopsis: ''),
  (name: 'Lua Reach', synopsis: ''),
  (name: 'Lukaria', synopsis: ''),
  (name: 'Lumina', synopsis: ''),
  (name: 'Luminae', synopsis: ''),
  (name: 'Luminae Glade', synopsis: ''),
  (name: 'Luminae Vale', synopsis: ''),
  (name: 'Luminae Veil', synopsis: ''),
  (name: 'Luminara', synopsis: ''),
  (name: 'Luminary', synopsis: ''),
  (name: 'Luminary Lumina', synopsis: ''),
  (name: 'Luminastra', synopsis: ''),
  (name: 'Luminex', synopsis: ''),
  (name: 'Lumynaris', synopsis: ''),
  (name: 'Lumynis', synopsis: ''),
  (name: 'Lumynis Veil', synopsis: ''),
  (name: 'Lumynyx', synopsis: ''),
  (name: 'Lumynyx Veil', synopsis: ''),
  (name: 'Luna', synopsis: ''),
  (name: 'Lunara', synopsis: ''),
  (name: 'Lunarae', synopsis: ''),
  (name: 'Lunaria', synopsis: ''),
  (name: 'Lunaria Astrum', synopsis: ''),
  (name: 'Lunariax', synopsis: ''),
  (name: 'Lunaris', synopsis: ''),
  (name: 'Lunaris Celestis', synopsis: ''),
  (name: 'Lunaris Noctis', synopsis: ''),
  (name: 'Lunaris Vale', synopsis: ''),
  (name: 'Lunaris Veil', synopsis: ''),
  (name: 'Lunaxis', synopsis: ''),
  (name: 'Lunos', synopsis: ''),
  (name: 'Lurn', synopsis: ''),
  (name: 'Luzars', synopsis: ''),
  (name: 'Lyke', synopsis: ''),
  (name: 'Lyra', synopsis: ''),
  (name: 'Lyra Celestialis', synopsis: ''),
  (name: 'Lyra Vortex', synopsis: ''),
  (name: 'Lyrius', synopsis: ''),
  (name: 'Lyrius Harmony', synopsis: ''),
  (name: 'Lyrius Nebula', synopsis: ''),
  (name: 'Maahines', synopsis: ''),
  (name: 'Magua', synopsis: ''),
  (name: 'Malkor', synopsis: ''),
  (name: 'Mandalore', synopsis: ''),
  (name: 'Manolla', synopsis: ''),
  (name: 'Maridian', synopsis: ''),
  (name: 'Maridian Aquaria', synopsis: ''),
  (name: 'Maridian Echo', synopsis: ''),
  (name: 'Maridian Reach', synopsis: ''),
  (name: 'Massiccio', synopsis: ''),
  (name: 'Mavros', synopsis: ''),
  (name: 'Megazol', synopsis: ''),
  (name: 'Mellirus', synopsis: ''),
  (name: 'Menviria', synopsis: ''),
  (name: 'Meridia', synopsis: ''),
  (name: 'Meridian', synopsis: ''),
  (name: 'Merth', synopsis: ''),
  (name: 'Meruta', synopsis: ''),
  (name: 'Mestryke', synopsis: ''),
  (name: 'Mezoria', synopsis: ''),
  (name: 'Mibboamia', synopsis: ''),
  (name: 'Micovis', synopsis: ''),
  (name: 'Micriea', synopsis: ''),
  (name: 'Mieliv', synopsis: ''),
  (name: 'Miuq', synopsis: ''),
  (name: 'Mogrion', synopsis: ''),
  (name: 'Mon Cala', synopsis: ''),
  (name: 'Muhimia', synopsis: ''),
  (name: 'Muunus', synopsis: ''),
  (name: 'Mya', synopsis: ''),
  (name: 'Myriad', synopsis: ''),
  (name: 'Myriad Nebula', synopsis: ''),
  (name: 'Mythos', synopsis: ''),
  (name: 'Naboo', synopsis: ''),
  (name: 'Nagua', synopsis: ''),
  (name: 'Nalarth', synopsis: ''),
  (name: 'Nalvurn', synopsis: ''),
  (name: 'Naphalia', synopsis: ''),
  (name: 'Nara', synopsis: ''),
  (name: 'Naxramma', synopsis: ''),
  (name: 'Nazyria', synopsis: ''),
  (name: 'Nebula', synopsis: ''),
  (name: 'Nebula Enigma', synopsis: ''),
  (name: 'Nebulara', synopsis: ''),
  (name: 'Nebulara Celestial', synopsis: ''),
  (name: 'Nebularis', synopsis: ''),
  (name: 'Nebularis Enclave', synopsis: ''),
  (name: 'Nebularis Enigma', synopsis: ''),
  (name: 'Nebulith', synopsis: ''),
  (name: 'Nebulon', synopsis: ''),
  (name: 'Nebulon Nebula', synopsis: ''),
  (name: 'Nebulon Reach', synopsis: ''),
  (name: 'Nebulonix', synopsis: ''),
  (name: 'Nebulora', synopsis: ''),
  (name: 'Nebulora Glade', synopsis: ''),
  (name: 'Nebulora Nebula', synopsis: ''),
  (name: 'Nebulore', synopsis: ''),
  (name: 'Nebuloria', synopsis: ''),
  (name: 'Nebuloria Enigma', synopsis: ''),
  (name: 'Nebuloria Vortex', synopsis: ''),
  (name: 'Nebuloris', synopsis: ''),
  (name: 'Nebulus', synopsis: ''),
  (name: 'Nebulus Zeta', synopsis: ''),
  (name: 'Nelore', synopsis: ''),
  (name: 'Nenviuwei', synopsis: ''),
  (name: 'Neotera', synopsis: ''),
  (name: 'Neoterra', synopsis: ''),
  (name: 'Nesippe', synopsis: ''),
  (name: 'Nesyke', synopsis: ''),
  (name: 'Nettoyer', synopsis: ''),
  (name: 'Newer', synopsis: ''),
  (name: 'Nibiru', synopsis: ''),
  (name: 'Night', synopsis: ''),
  (name: 'Nionazar', synopsis: ''),
  (name: 'Nippe', synopsis: ''),
  (name: 'Nirvana', synopsis: ''),
  (name: 'Niuq', synopsis: ''),
  (name: 'Nixamar', synopsis: ''),
  (name: 'Nocturna', synopsis: ''),
  (name: 'Nocturnara', synopsis: ''),
  (name: 'Nocturnia', synopsis: ''),
  (name: 'Nocturnis', synopsis: ''),
  (name: 'Nocturnis Dark', synopsis: ''),
  (name: 'Nocturnis Umbra', synopsis: ''),
  (name: 'Nogater', synopsis: ''),
  (name: 'Norix', synopsis: ''),
  (name: 'Noth', synopsis: ''),
  (name: 'Numidian', synopsis: ''),
  (name: 'Nupra', synopsis: ''),
  (name: 'Nyria', synopsis: ''),
  (name: 'Nyx', synopsis: ''),
  (name: 'Obragh', synopsis: ''),
  (name: 'Obsidian', synopsis: ''),
  (name: 'Obsydria', synopsis: ''),
  (name: 'Oceania', synopsis: ''),
  (name: 'Oceano', synopsis: ''),
  (name: 'Ogantu', synopsis: ''),
  (name: 'Ogore', synopsis: ''),
  (name: 'Olillon', synopsis: ''),
  (name: 'Oliv', synopsis: ''),
  (name: 'Olorix', synopsis: ''),
  (name: 'Ondion', synopsis: ''),
  (name: 'Oniea', synopsis: ''),
  (name: 'Ophelia', synopsis: ''),
  (name: 'Oranis', synopsis: ''),
  (name: 'Oranis Reach', synopsis: ''),
  (name: 'Orionis', synopsis: ''),
  (name: 'Orpheus', synopsis: ''),
  (name: 'Ouphus', synopsis: ''),
  (name: 'Ozuno', synopsis: ''),
  (name: 'Pacifica', synopsis: ''),
  (name: 'Pararaiha', synopsis: ''),
  (name: 'Phantos', synopsis: ''),
  (name: 'Phars', synopsis: ''),
  (name: 'Pherth', synopsis: ''),
  (name: 'Philia', synopsis: ''),
  (name: 'Pisces', synopsis: ''),
  (name: 'Polveshan', synopsis: ''),
  (name: 'Portum', synopsis: ''),
  (name: 'Prismis', synopsis: ''),
  (name: 'Prismis Radiance', synopsis: ''),
  (name: 'Prismora', synopsis: ''),
  (name: 'Prismora Radiant', synopsis: ''),
  (name: 'Proxima', synopsis: ''),
  (name: 'Punus', synopsis: ''),
  (name: 'Purilia', synopsis: ''),
  (name: 'Pyralia', synopsis: ''),
  (name: 'Pyralion', synopsis: ''),
  (name: 'Pyralis', synopsis: ''),
  (name: 'Pyralis Glade', synopsis: ''),
  (name: 'Pyralis Vale', synopsis: ''),
  (name: 'Pyraxis', synopsis: ''),
  (name: 'Pyraxis Flameheart', synopsis: ''),
  (name: 'Pyrion', synopsis: ''),
  (name: 'Pyrion Vale', synopsis: ''),
  (name: 'Pyronis', synopsis: ''),
  (name: 'Pyronis Astra', synopsis: ''),
  (name: 'Pyronis Inferno', synopsis: ''),
  (name: 'Pyronyx', synopsis: ''),
  (name: 'Pyroth', synopsis: ''),
  (name: 'Pyroth Firestorm', synopsis: ''),
  (name: 'Pyrothia', synopsis: ''),
  (name: 'Pyrothian', synopsis: ''),
  (name: 'Pyrothium', synopsis: ''),
  (name: 'Pyrothos', synopsis: ''),
  (name: 'Pyrovel', synopsis: ''),
  (name: 'Pyroxis', synopsis: ''),
  (name: 'Pyrrhia', synopsis: ''),
  (name: 'Pyrrhus', synopsis: ''),
  (name: 'Quasar', synopsis: ''),
  (name: 'Quasar Stellarum', synopsis: ''),
  (name: 'Quetzalia', synopsis: ''),
  (name: 'Quinox', synopsis: ''),
  (name: 'Quinox Equinox', synopsis: ''),
  (name: 'Ra', synopsis: ''),
  (name: 'Radiance', synopsis: ''),
  (name: 'Radiant Terra', synopsis: ''),
  (name: 'Radium', synopsis: ''),
  (name: 'Raplamar', synopsis: ''),
  (name: 'Rarohenga', synopsis: ''),
  (name: 'Recentibus', synopsis: ''),
  (name: 'Remus', synopsis: ''),
  (name: 'Reruta', synopsis: ''),
  (name: 'Retreron', synopsis: ''),
  (name: 'Ria', synopsis: ''),
  (name: 'Riagantu', synopsis: ''),
  (name: 'Ridoria', synopsis: ''),
  (name: 'Rigel', synopsis: ''),
  (name: 'Rion', synopsis: ''),
  (name: 'Rippundor', synopsis: ''),
  (name: 'Ris', synopsis: ''),
  (name: 'Ris Solaris', synopsis: ''),
  (name: 'Risa', synopsis: ''),
  (name: 'Risastor', synopsis: ''),
  (name: 'Rismuzar', synopsis: ''),
  (name: 'Ruccanides', synopsis: ''),
  (name: 'Rulveobos', synopsis: ''),
  (name: 'Rulveobos Theta', synopsis: ''),
  (name: 'Ruveutera', synopsis: ''),
  (name: 'Sablex', synopsis: ''),
  (name: 'Sade', synopsis: ''),
  (name: 'Sallavor', synopsis: ''),
  (name: 'Samia', synopsis: ''),
  (name: 'Sanilia', synopsis: ''),
  (name: 'Sario', synopsis: ''),
  (name: 'Sars', synopsis: ''),
  (name: 'Secriowei', synopsis: ''),
  (name: 'Seladon', synopsis: ''),
  (name: 'Selene', synopsis: ''),
  (name: 'Septario', synopsis: ''),
  (name: 'Septerion', synopsis: ''),
  (name: 'Seraphis', synopsis: ''),
  (name: 'Sere', synopsis: ''),
  (name: 'Serene', synopsis: ''),
  (name: 'Serenith', synopsis: ''),
  (name: 'Serenity', synopsis: ''),
  (name: 'Sexurus', synopsis: ''),
  (name: 'Sigrater', synopsis: ''),
  (name: 'Silles', synopsis: ''),
  (name: 'Sirocco', synopsis: ''),
  (name: 'Soalea', synopsis: ''),
  (name: 'Sola', synopsis: ''),
  (name: 'Solara', synopsis: ''),
  (name: 'Solara Dusk', synopsis: ''),
  (name: 'Solara Luminara', synopsis: ''),
  (name: 'Solara Veil', synopsis: ''),
  (name: 'Solara Vista', synopsis: ''),
  (name: 'Solarae', synopsis: ''),
  (name: 'Solarae Aurelia', synopsis: ''),
  (name: 'Solarae Oasis', synopsis: ''),
  (name: 'Solaria', synopsis: ''),
  (name: 'Solarion', synopsis: ''),
  (name: 'Solaris', synopsis: ''),
  (name: 'Solarius', synopsis: ''),
  (name: 'Solera', synopsis: ''),
  (name: 'Solis', synopsis: ''),
  (name: 'Solisoria', synopsis: ''),
  (name: 'Solla', synopsis: ''),
  (name: 'Solstice', synopsis: ''),
  (name: 'Solstice Orchid', synopsis: ''),
  (name: 'Solstice Reach', synopsis: ''),
  (name: 'Solsticea', synopsis: ''),
  (name: 'Solsticea Solis', synopsis: ''),
  (name: 'Solterra', synopsis: ''),
  (name: 'Soluna', synopsis: ''),
  (name: 'Soluna Lunara', synopsis: ''),
  (name: 'Solunara', synopsis: ''),
  (name: 'Solunis', synopsis: ''),
  (name: 'Solunis Solaris', synopsis: ''),
  (name: 'Solvenia', synopsis: ''),
  (name: 'Solvenis', synopsis: ''),
  (name: 'Solvenis Crystallis', synopsis: ''),
  (name: 'Solvenis Vale', synopsis: ''),
  (name: 'Solventis', synopsis: ''),
  (name: 'Solvenya', synopsis: ''),
  (name: 'Solvenyx', synopsis: ''),
  (name: 'Solvian Reach', synopsis: ''),
  (name: 'Solvira', synopsis: ''),
  (name: 'Solvius', synopsis: ''),
  (name: 'Solvius Solaris', synopsis: ''),
  (name: 'Solvoria', synopsis: ''),
  (name: 'Solvoria Vale', synopsis: ''),
  (name: 'Solynis', synopsis: ''),
  (name: 'Somia', synopsis: ''),
  (name: 'Soxupra', synopsis: ''),
  (name: 'Spectra', synopsis: ''),
  (name: 'Stellar', synopsis: ''),
  (name: 'Stellara', synopsis: ''),
  (name: 'Stellara Glade', synopsis: ''),
  (name: 'Stellara Light', synopsis: ''),
  (name: 'Stellaria', synopsis: ''),
  (name: 'Stellaris', synopsis: ''),
  (name: 'Stellaris Astralis', synopsis: ''),
  (name: 'Stellaris Ignis', synopsis: ''),
  (name: 'Stellarium', synopsis: ''),
  (name: 'Stellaron', synopsis: ''),
  (name: 'Stellora', synopsis: ''),
  (name: 'Stellora Glade', synopsis: ''),
  (name: 'Stelloria', synopsis: ''),
  (name: 'Stelloria Glade', synopsis: ''),
  (name: 'Stra', synopsis: ''),
  (name: 'Strachenov', synopsis: ''),
  (name: 'Strade', synopsis: ''),
  (name: 'Stralis', synopsis: ''),
  (name: 'Straputis', synopsis: ''),
  (name: 'Straxirus', synopsis: ''),
  (name: 'Strematis', synopsis: ''),
  (name: 'Strivinerth', synopsis: ''),
  (name: 'Strorth', synopsis: ''),
  (name: 'Sucury', synopsis: ''),
  (name: 'Sufocar', synopsis: ''),
  (name: 'Sukurn', synopsis: ''),
  (name: 'Suna', synopsis: ''),
  (name: 'Sylvana', synopsis: ''),
  (name: 'Sylvanus', synopsis: ''),
  (name: 'Sylvaria', synopsis: ''),
  (name: 'Sylvaria Seraph', synopsis: ''),
  (name: 'Sylvaris', synopsis: ''),
  (name: 'Sylvaris Glade', synopsis: ''),
  (name: 'Sylvaris Sylvan', synopsis: ''),
  (name: 'Sythra', synopsis: ''),
  (name: 'Tahiri', synopsis: ''),
  (name: 'Tara', synopsis: ''),
  (name: 'Tartu', synopsis: ''),
  (name: 'Tater', synopsis: ''),
  (name: 'Tatooine', synopsis: ''),
  (name: 'Tau Ceti', synopsis: ''),
  (name: 'Taurus', synopsis: ''),
  (name: 'Taxore', synopsis: ''),
  (name: 'Tearmann', synopsis: ''),
  (name: 'Tempador', synopsis: ''),
  (name: 'Terra', synopsis: ''),
  (name: 'Terra Solis', synopsis: ''),
  (name: 'Thagua', synopsis: ''),
  (name: 'Thazuruta', synopsis: ''),
  (name: 'Thelea', synopsis: ''),
  (name: 'Theon', synopsis: ''),
  (name: 'Thiirus', synopsis: ''),
  (name: 'Thimion', synopsis: ''),
  (name: 'Thisuvis', synopsis: ''),
  (name: 'Thocosie', synopsis: ''),
  (name: 'Thomilia', synopsis: ''),
  (name: 'Thora', synopsis: ''),
  (name: 'Thostrorth', synopsis: ''),
  (name: 'Thuinides', synopsis: ''),
  (name: 'Thulnyke', synopsis: ''),
  (name: 'Titanis', synopsis: ''),
  (name: 'To', synopsis: ''),
  (name: 'Tolatune', synopsis: ''),
  (name: 'Toxico', synopsis: ''),
  (name: 'Trilia', synopsis: ''),
  (name: 'Trilles', synopsis: ''),
  (name: 'Tryke', synopsis: ''),
  (name: 'Tubbethea', synopsis: ''),
  (name: 'Tulia', synopsis: ''),
  (name: 'Tutania', synopsis: ''),
  (name: 'Tuumomo', synopsis: ''),
  (name: 'Tyrian', synopsis: ''),
  (name: 'Uater', synopsis: ''),
  (name: 'Ucarro', synopsis: ''),
  (name: 'Uchilles', synopsis: ''),
  (name: 'Uchuna', synopsis: ''),
  (name: 'Udarvis', synopsis: ''),
  (name: 'Udone', synopsis: ''),
  (name: 'Ugnonerth', synopsis: ''),
  (name: 'Ulamaza', synopsis: ''),
  (name: 'Ultavor', synopsis: ''),
  (name: 'Umbria', synopsis: ''),
  (name: 'Umonoe', synopsis: ''),
  (name: 'Unairuta', synopsis: ''),
  (name: 'Uptoria', synopsis: ''),
  (name: 'Uruta', synopsis: ''),
  (name: 'Uter', synopsis: ''),
  (name: 'Valara', synopsis: ''),
  (name: 'Valdron', synopsis: ''),
  (name: 'Valoria', synopsis: ''),
  (name: 'Vandor', synopsis: ''),
  (name: 'Vanduthea', synopsis: ''),
  (name: 'Vega', synopsis: ''),
  (name: 'Vekao', synopsis: ''),
  (name: 'Vemiuq', synopsis: ''),
  (name: 'Verdania', synopsis: ''),
  (name: 'Verdania Verdora', synopsis: ''),
  (name: 'Verdant Oasis', synopsis: ''),
  (name: 'Verdantara', synopsis: ''),
  (name: 'Verdanthos', synopsis: ''),
  (name: 'Verdantia', synopsis: ''),
  (name: 'Verdantis', synopsis: ''),
  (name: 'Verdantis Glade', synopsis: ''),
  (name: 'Verdantis Vale', synopsis: ''),
  (name: 'Verdantium', synopsis: ''),
  (name: 'Verdantora', synopsis: ''),
  (name: 'Verdantoria', synopsis: ''),
  (name: 'Verdantus', synopsis: ''),
  (name: 'Verdantus Glade', synopsis: ''),
  (name: 'Verdantus Vale', synopsis: ''),
  (name: 'Verdantus Wilds', synopsis: ''),
  (name: 'Verdara', synopsis: ''),
  (name: 'Verdora', synopsis: ''),
  (name: 'Veridia', synopsis: ''),
  (name: 'Veridian', synopsis: ''),
  (name: 'Veridian Elysium', synopsis: ''),
  (name: 'Veridian Sylvanis', synopsis: ''),
  (name: 'Veridora', synopsis: ''),
  (name: 'Veridora Glade', synopsis: ''),
  (name: 'Veridora Oasis', synopsis: ''),
  (name: 'Veritas', synopsis: ''),
  (name: 'Vespera', synopsis: ''),
  (name: 'Vespera Dusk', synopsis: ''),
  (name: 'Vespera Vale', synopsis: ''),
  (name: 'Vesperia', synopsis: ''),
  (name: 'Vesperium', synopsis: ''),
  (name: 'Veunia', synopsis: ''),
  (name: 'Victoria', synopsis: ''),
  (name: 'Vides', synopsis: ''),
  (name: 'Viditera', synopsis: ''),
  (name: 'Virgo', synopsis: ''),
  (name: 'Vitalis', synopsis: ''),
  (name: 'Volantis', synopsis: ''),
  (name: 'Vortalis', synopsis: ''),
  (name: 'Vortexia', synopsis: ''),
  (name: 'Vorth', synopsis: ''),
  (name: 'Vubecarro', synopsis: ''),
  (name: 'Vulcan', synopsis: ''),
  (name: 'Vunzulea', synopsis: ''),
  (name: 'Vuruta', synopsis: ''),
  (name: 'Vyke', synopsis: ''),
  (name: 'Wolf', synopsis: ''),
  (name: 'Xanthis', synopsis: ''),
  (name: 'Xanthis Reach', synopsis: ''),
  (name: 'Xelarvis', synopsis: ''),
  (name: 'Xenaris', synopsis: ''),
  (name: 'Xileon', synopsis: ''),
  (name: 'Xiliv', synopsis: ''),
  (name: 'Xirilia', synopsis: ''),
  (name: 'Xis', synopsis: ''),
  (name: 'Xochilia', synopsis: ''),
  (name: 'Xore', synopsis: ''),
  (name: 'Xovunides', synopsis: ''),
  (name: 'Xunruawei', synopsis: ''),
  (name: 'Xuter', synopsis: ''),
  (name: 'Yastrotov', synopsis: ''),
  (name: 'Yavin', synopsis: ''),
  (name: 'Yemustea', synopsis: ''),
  (name: 'Yetania', synopsis: ''),
  (name: 'Yocowei', synopsis: ''),
  (name: 'Yubizuno', synopsis: ''),
  (name: 'Yulveron', synopsis: ''),
  (name: 'Zaclite', synopsis: ''),
  (name: 'Zao', synopsis: ''),
  (name: 'Zaphus', synopsis: ''),
  (name: 'Zeffo', synopsis: ''),
  (name: 'Zeldara', synopsis: ''),
  (name: 'Zendar', synopsis: ''),
  (name: 'Zendaria', synopsis: ''),
  (name: 'Zenithia', synopsis: ''),
  (name: 'Zephyr', synopsis: ''),
  (name: 'Zephyra Skyward', synopsis: ''),
  (name: 'Zephyrae', synopsis: ''),
  (name: 'Zephyraine', synopsis: ''),
  (name: 'Zephyraine Reach', synopsis: ''),
  (name: 'Zephyrara', synopsis: ''),
  (name: 'Zephyraris', synopsis: ''),
  (name: 'Zephyraris Vale', synopsis: ''),
  (name: 'Zephyrath', synopsis: ''),
  (name: 'Zephyria', synopsis: ''),
  (name: 'Zephyria Magna', synopsis: ''),
  (name: 'Zephyria Oasis', synopsis: ''),
  (name: 'Zephyriae', synopsis: ''),
  (name: 'Zephyrion', synopsis: ''),
  (name: 'Zephyrion Zephyrus', synopsis: ''),
  (name: 'Zephyrith', synopsis: ''),
  (name: 'Zephyrium', synopsis: ''),
  (name: 'Zephyrium Zephyrion', synopsis: ''),
  (name: 'Zephyron', synopsis: ''),
  (name: 'Zephyrora', synopsis: ''),
  (name: 'Zephyros', synopsis: ''),
  (name: 'Zephyrosa', synopsis: ''),
  (name: 'Zephyrus', synopsis: ''),
  (name: 'Zerith', synopsis: ''),
  (name: 'Zetune', synopsis: ''),
  (name: 'Zexade', synopsis: ''),
  (name: 'Zimater', synopsis: ''),
  (name: 'Ziopagawa', synopsis: ''),
  (name: 'Zirconia', synopsis: ''),
  (name: 'Zirconis', synopsis: ''),
  (name: 'Zirconis Twilight', synopsis: ''),
  (name: 'Ziwei', synopsis: ''),
  (name: 'Zocenus', synopsis: ''),
  (name: 'Zoclite', synopsis: ''),
  (name: 'Zonoe', synopsis: ''),
  (name: 'Zunricarro', synopsis: ''),
  (name: 'Zuthara', synopsis: ''),
  (name: 'Zypheria', synopsis: ''),
  (name: 'Zypheris', synopsis: ''),
  (name: 'Zypheris Zypher', synopsis: ''),
  (name: 'Zypherium', synopsis: ''),
  (name: 'Zypheron', synopsis: ''),
  (name: 'Zypheron Zephyrus', synopsis: ''),
  (name: 'Zypheron Zypher', synopsis: ''),
  (name: 'Zyphira', synopsis: ''),
  (name: 'Zyphira Zephyra', synopsis: ''),
  (name: 'Zyphora', synopsis: ''),
  (name: 'Zyphora Equinox', synopsis: ''),
  (name: 'Zyphora Lumina', synopsis: ''),
  (name: 'Zyphoria', synopsis: ''),
  (name: 'Zyphoriax', synopsis: ''),
  (name: 'Zyphorion', synopsis: ''),
  (name: 'Zyphorius', synopsis: ''),
  (name: 'Zyphos', synopsis: ''),
  (name: 'Zypso', synopsis: ''),
};
