import '../name_r.dart';

const Set<NameR> en = {
  (title: 'Adaleko', synopsis: null),
  (title: 'Adarak', synopsis: null),
  (title: 'Adyke', synopsis: null),
  (title: 'Aerilon', synopsis: null),
  (title: 'Aeris', synopsis: null),
  (title: 'Aerith', synopsis: null),
  (title: 'Aeterna', synopsis: null),
  (title: 'Aetherea', synopsis: null),
  (title: 'Aethereon', synopsis: null),
  (title: 'Aetheria', synopsis: null),
  (title: 'Aetherion', synopsis: null),
  (title: 'Aetherion Reach', synopsis: null),
  (title: 'Aetheris', synopsis: null),
  (title: 'Aetherium', synopsis: null),
  (title: 'Aetherium Citadel', synopsis: null),
  (title: 'Aetherium Etheria', synopsis: null),
  (title: 'Aetherius', synopsis: null),
  (title: 'Aetherlight', synopsis: null),
  (title: 'Aetheron', synopsis: null),
  (title: 'Agamar', synopsis: null),
  (title: 'Ahebos', synopsis: null),
  (title: 'Akeon', synopsis: null),
  (title: 'Akippe', synopsis: null),
  (title: 'Alaris', synopsis: null),
  (title: 'Alazar', synopsis: null),
  (title: 'Alderaan', synopsis: null),
  (title: 'Alfadus', synopsis: null),
  (title: 'Altair', synopsis: null),
  (title: 'Alzoc', synopsis: null),
  (title: 'Amethyst', synopsis: null),
  (title: 'Amides', synopsis: null),
  (title: 'Andoria', synopsis: null),
  (title: 'Andromeda', synopsis: null),
  (title: 'Angichi', synopsis: null),
  (title: 'Anrigantu', synopsis: null),
  (title: 'Antus', synopsis: null),
  (title: 'Aolara', synopsis: null),
  (title: 'Apollonia', synopsis: null),
  (title: 'Aquafire', synopsis: null),
  (title: 'Aqualis', synopsis: null),
  (title: 'Aqualuna', synopsis: null),
  (title: 'Aquara', synopsis: null),
  (title: 'Aquaradia', synopsis: null),
  (title: 'Aquaria', synopsis: null),
  (title: 'Aquaria Enclave', synopsis: null),
  (title: 'Aquaria Maris', synopsis: null),
  (title: 'Aquaria Serene', synopsis: null),
  (title: 'Aquaria Vale', synopsis: null),
  (title: 'Aquaria Veil', synopsis: null),
  (title: 'Aquariis', synopsis: null),
  (title: 'Aquarion', synopsis: null),
  (title: 'Aquarion Vale', synopsis: null),
  (title: 'Aquaris', synopsis: null),
  (title: 'Aquaterra', synopsis: null),
  (title: 'Aquaterra Aquilon', synopsis: null),
  (title: 'Aquaterra Enigma', synopsis: null),
  (title: 'Aquila', synopsis: null),
  (title: 'Aquilis', synopsis: null),
  (title: 'Aquilon', synopsis: null),
  (title: 'Aquilonia', synopsis: null),
  (title: 'Aquilonis', synopsis: null),
  (title: 'Aquilonis Enigma', synopsis: null),
  (title: 'Aquilonis Terra', synopsis: null),
  (title: 'Aquilonis Vale', synopsis: null),
  (title: 'Aracnus', synopsis: null),
  (title: 'Arboria', synopsis: null),
  (title: 'Arcadia', synopsis: null),
  (title: 'Arcana', synopsis: null),
  (title: 'Arcana Mysticus', synopsis: null),
  (title: 'Arcane', synopsis: null),
  (title: 'Arcanis', synopsis: null),
  (title: 'Arcanis Enclave', synopsis: null),
  (title: 'Arcanis Vale', synopsis: null),
  (title: 'Arcanith', synopsis: null),
  (title: 'Arcanor', synopsis: null),
  (title: 'Arcanor Glade', synopsis: null),
  (title: 'Arcanor Vale', synopsis: null),
  (title: 'Arcanora', synopsis: null),
  (title: 'Arcanora Enclave', synopsis: null),
  (title: 'Arcanox', synopsis: null),
  (title: 'Arcantheon', synopsis: null),
  (title: 'Arcantheon Ember', synopsis: null),
  (title: 'Arcanum', synopsis: null),
  (title: 'Arcanum Mystica', synopsis: null),
  (title: 'Ardentia', synopsis: null),
  (title: 'Ardentia Flame', synopsis: null),
  (title: 'Aria', synopsis: null),
  (title: 'Aridia', synopsis: null),
  (title: 'Aroria', synopsis: null),
  (title: 'Arorix', synopsis: null),
  (title: 'Astoria', synopsis: null),
  (title: 'Astra', synopsis: null),
  (title: 'Astraal', synopsis: null),
  (title: 'Astraal Fall', synopsis: null),
  (title: 'Astradus', synopsis: null),
  (title: 'Astradus Aether', synopsis: null),
  (title: 'Astrafall', synopsis: null),
  (title: 'Astrafira', synopsis: null),
  (title: 'Astrafira Enclave', synopsis: null),
  (title: 'Astrafira Vale', synopsis: null),
  (title: 'Astrafire', synopsis: null),
  (title: 'Astrafire Enigma', synopsis: null),
  (title: 'Astrafyre', synopsis: null),
  (title: 'Astrafyre Ember', synopsis: null),
  (title: 'Astrafyre Enclave', synopsis: null),
  (title: 'Astrafyre Glade', synopsis: null),
  (title: 'Astrafyre Vale', synopsis: null),
  (title: 'Astral Fire', synopsis: null),
  (title: 'Astraldus', synopsis: null),
  (title: 'Astralia', synopsis: null),
  (title: 'Astralia Veil', synopsis: null),
  (title: 'Astralis', synopsis: null),
  (title: 'Astralisia', synopsis: null),
  (title: 'Astralyn', synopsis: null),
  (title: 'Astrastra', synopsis: null),
  (title: 'Astravia', synopsis: null),
  (title: 'Astridae', synopsis: null),
  (title: 'Astridae Dawn', synopsis: null),
  (title: 'Astriline', synopsis: null),
  (title: 'Astrilis', synopsis: null),
  (title: 'Astrilis Luminis', synopsis: null),
  (title: 'Astrion', synopsis: null),
  (title: 'Astrion Eclipse', synopsis: null),
  (title: 'Astrion Vale', synopsis: null),
  (title: 'Astrionis', synopsis: null),
  (title: 'Astrionyx', synopsis: null),
  (title: 'Astrionyx Glade', synopsis: null),
  (title: 'Astro', synopsis: null),
  (title: 'Astronaris', synopsis: null),
  (title: 'Astronaris Astral', synopsis: null),
  (title: 'Astronia', synopsis: null),
  (title: 'Astronia Glade', synopsis: null),
  (title: 'Astronia Prism', synopsis: null),
  (title: 'Astroniax', synopsis: null),
  (title: 'Astroniax Vale', synopsis: null),
  (title: 'Astronus', synopsis: null),
  (title: 'Astronyx', synopsis: null),
  (title: 'Astronyx Lunara', synopsis: null),
  (title: 'Astronyx Reach', synopsis: null),
  (title: 'Astroria', synopsis: null),
  (title: 'Astrum', synopsis: null),
  (title: 'Astrum Cosmo', synopsis: null),
  (title: 'Astrum Cosmos', synopsis: null),
  (title: 'Athilles', synopsis: null),
  (title: 'Athora', synopsis: null),
  (title: 'Atune', synopsis: null),
  (title: 'Auriel', synopsis: null),
  (title: 'Auroria', synopsis: null),
  (title: 'Aurorium', synopsis: null),
  (title: 'Aurorium Lumyn', synopsis: null),
  (title: 'Aurorium Realm', synopsis: null),
  (title: 'Auros', synopsis: null),
  (title: 'Aurum', synopsis: null),
  (title: 'Auryn', synopsis: null),
  (title: 'Auryn Twilight', synopsis: null),
  (title: 'Azimuth', synopsis: null),
  (title: 'Aziri', synopsis: null),
  (title: 'Azulon', synopsis: null),
  (title: 'Azura', synopsis: null),
  (title: 'Azuran', synopsis: null),
  (title: 'Azurea', synopsis: null),
  (title: 'Azurelith', synopsis: null),
  (title: 'Azurexis', synopsis: null),
  (title: 'Azurya', synopsis: null),
  (title: 'Bacarro', synopsis: null),
  (title: 'Baiwei', synopsis: null),
  (title: 'Baniri', synopsis: null),
  (title: 'Bantalador', synopsis: null),
  (title: 'Barisa', synopsis: null),
  (title: 'Belore', synopsis: null),
  (title: 'Belsana', synopsis: null),
  (title: 'Beron', synopsis: null),
  (title: 'Bespin', synopsis: null),
  (title: 'Bisapus', synopsis: null),
  (title: 'Bithowei', synopsis: null),
  (title: 'Bliss', synopsis: null),
  (title: 'Blue', synopsis: null),
  (title: 'Bolaris', synopsis: null),
  (title: 'Boxora', synopsis: null),
  (title: 'Brapus', synopsis: null),
  (title: 'Brara', synopsis: null),
  (title: 'Breen', synopsis: null),
  (title: 'Bretihines', synopsis: null),
  (title: 'Brinda', synopsis: null),
  (title: 'Brolnaistea', synopsis: null),
  (title: 'Broxitera', synopsis: null),
  (title: 'Brurn', synopsis: null),
  (title: 'Bunvogantu', synopsis: null),
  (title: 'Buphobos', synopsis: null),
  (title: 'Caelis', synopsis: null),
  (title: 'Caelum', synopsis: null),
  (title: 'Caldonia', synopsis: null),
  (title: 'Calmov', synopsis: null),
  (title: 'Calypso', synopsis: null),
  (title: 'Camrina', synopsis: null),
  (title: 'Capricornus', synopsis: null),
  (title: 'Celea', synopsis: null),
  (title: 'Celea Vale', synopsis: null),
  (title: 'Celeia', synopsis: null),
  (title: 'Celeia Glade', synopsis: null),
  (title: 'Celeia Vale', synopsis: null),
  (title: 'Celestalis', synopsis: null),
  (title: 'Celestalis Stellis', synopsis: null),
  (title: 'Celesterra', synopsis: null),
  (title: 'Celestia', synopsis: null),
  (title: 'Celestial Ember', synopsis: null),
  (title: 'Celestion', synopsis: null),
  (title: 'Celestion Celestis', synopsis: null),
  (title: 'Celestora', synopsis: null),
  (title: 'Celestora Glade', synopsis: null),
  (title: 'Celestoria', synopsis: null),
  (title: 'Celestra', synopsis: null),
  (title: 'Celestra Astoria', synopsis: null),
  (title: 'Celestria', synopsis: null),
  (title: 'Celestriax', synopsis: null),
  (title: 'Celestris', synopsis: null),
  (title: 'Celestrosa', synopsis: null),
  (title: 'Centauri', synopsis: null),
  (title: 'Cepra', synopsis: null),
  (title: 'Cethea', synopsis: null),
  (title: 'Cethenope', synopsis: null),
  (title: 'Ceti', synopsis: null),
  (title: 'Chacarvis', synopsis: null),
  (title: 'Chagriaclite', synopsis: null),
  (title: 'Charvis', synopsis: null),
  (title: 'Chestrarth', synopsis: null),
  (title: 'Chinda', synopsis: null),
  (title: 'Choria', synopsis: null),
  (title: 'Chosie', synopsis: null),
  (title: 'Chov', synopsis: null),
  (title: 'Chromis', synopsis: null),
  (title: 'Chrona', synopsis: null),
  (title: 'Chronos', synopsis: null),
  (title: 'Chubrara', synopsis: null),
  (title: 'Chuiruta', synopsis: null),
  (title: 'Cicero', synopsis: null),
  (title: 'Cichehines', synopsis: null),
  (title: 'Cinderspire', synopsis: null),
  (title: 'Cinoth', synopsis: null),
  (title: 'Cippe', synopsis: null),
  (title: 'Codrarth', synopsis: null),
  (title: 'Cortinas', synopsis: null),
  (title: 'Coruscant', synopsis: null),
  (title: 'Corzor', synopsis: null),
  (title: 'Cothorix', synopsis: null),
  (title: 'Cov', synopsis: null),
  (title: 'Crapus', synopsis: null),
  (title: 'Crichi', synopsis: null),
  (title: 'Criea', synopsis: null),
  (title: 'Crinacury', synopsis: null),
  (title: 'Crounus', synopsis: null),
  (title: 'Cryke', synopsis: null),
  (title: 'Crystallis', synopsis: null),
  (title: 'Cuhavis', synopsis: null),
  (title: 'Cungore', synopsis: null),
  (title: 'Cunrars', synopsis: null),
  (title: 'Cygnus', synopsis: null),
  (title: 'Cyrana', synopsis: null),
  (title: 'Cyrulas', synopsis: null),
  (title: 'Dade', synopsis: null),
  (title: 'Daeliv', synopsis: null),
  (title: 'Dapus', synopsis: null),
  (title: 'Dars', synopsis: null),
  (title: 'Darus', synopsis: null),
  (title: 'Dathomir', synopsis: null),
  (title: 'Davinda', synopsis: null),
  (title: 'Denides', synopsis: null),
  (title: 'Denkerth', synopsis: null),
  (title: 'Desolata', synopsis: null),
  (title: 'Diea', synopsis: null),
  (title: 'Diyilia', synopsis: null),
  (title: 'Doanope', synopsis: null),
  (title: 'Dograiruta', synopsis: null),
  (title: 'Doloulea', synopsis: null),
  (title: 'Draconis', synopsis: null),
  (title: 'Drakoria', synopsis: null),
  (title: 'Draoria', synopsis: null),
  (title: 'Drehiri', synopsis: null),
  (title: 'Dresuturn', synopsis: null),
  (title: 'Drethuhiri', synopsis: null),
  (title: 'Dricarro', synopsis: null),
  (title: 'Drides', synopsis: null),
  (title: 'Driea', synopsis: null),
  (title: 'Drilora', synopsis: null),
  (title: 'Drion', synopsis: null),
  (title: 'Drippe', synopsis: null),
  (title: 'Drixetera', synopsis: null),
  (title: 'Dromia', synopsis: null),
  (title: 'Drore', synopsis: null),
  (title: 'Drorth', synopsis: null),
  (title: 'Droutera', synopsis: null),
  (title: 'Druinov', synopsis: null),
  (title: 'Drypso', synopsis: null),
  (title: 'Dua', synopsis: null),
  (title: 'Dumavis', synopsis: null),
  (title: 'Dumeron', synopsis: null),
  (title: 'Dundeon', synopsis: null),
  (title: 'Duntana', synopsis: null),
  (title: 'Dusta', synopsis: null),
  (title: 'Dustraphus', synopsis: null),
  (title: 'Dustria', synopsis: null),
  (title: 'Dypso', synopsis: null),
  (title: 'Ebonara', synopsis: null),
  (title: 'Ebonara Nocturna', synopsis: null),
  (title: 'Ebonara Shadowgate', synopsis: null),
  (title: 'Ebonara Twilight', synopsis: null),
  (title: 'Ebonis', synopsis: null),
  (title: 'Ebrarth', synopsis: null),
  (title: 'Eclipsis', synopsis: null),
  (title: 'Eden', synopsis: null),
  (title: 'Edenia', synopsis: null),
  (title: 'Edenis', synopsis: null),
  (title: 'Edyria', synopsis: null),
  (title: 'Eirene', synopsis: null),
  (title: 'Eitur', synopsis: null),
  (title: 'Elaris', synopsis: null),
  (title: 'Eldoria', synopsis: null),
  (title: 'Eldorium', synopsis: null),
  (title: 'Eldrune', synopsis: null),
  (title: 'Elethria', synopsis: null),
  (title: 'Elethria Celestia', synopsis: null),
  (title: 'Elethria Zephyr', synopsis: null),
  (title: 'Elyria', synopsis: null),
  (title: 'Elysar Veil', synopsis: null),
  (title: 'Elysara', synopsis: null),
  (title: 'Elysaria', synopsis: null),
  (title: 'Elysaria Glade', synopsis: null),
  (title: 'Elysia', synopsis: null),
  (title: 'Elysia Glade', synopsis: null),
  (title: 'Elysia Oasis', synopsis: null),
  (title: 'Elysira', synopsis: null),
  (title: 'Elysira Auriel', synopsis: null),
  (title: 'Elysium', synopsis: null),
  (title: 'Elysium Oasis', synopsis: null),
  (title: 'Elysium Radiance', synopsis: null),
  (title: 'Elysium Reach', synopsis: null),
  (title: 'Elysium Veil', synopsis: null),
  (title: 'Elysiuma', synopsis: null),
  (title: 'Elysora', synopsis: null),
  (title: 'Elyssar', synopsis: null),
  (title: 'Elyssar Veil', synopsis: null),
  (title: 'Elyssaria', synopsis: null),
  (title: 'Elyssaria Glade', synopsis: null),
  (title: 'Elyssia', synopsis: null),
  (title: 'Emberia', synopsis: null),
  (title: 'Emberon', synopsis: null),
  (title: 'Eminiar', synopsis: null),
  (title: 'Empyrea', synopsis: null),
  (title: 'Empyreal', synopsis: null),
  (title: 'Empyrealis', synopsis: null),
  (title: 'Empyrean', synopsis: null),
  (title: 'Endor', synopsis: null),
  (title: 'Enigma', synopsis: null),
  (title: 'Epheastea', synopsis: null),
  (title: 'Epsilon', synopsis: null),
  (title: 'Equinox', synopsis: null),
  (title: 'Eridani', synopsis: null),
  (title: 'Eridani Echo', synopsis: null),
  (title: 'Eridanus', synopsis: null),
  (title: 'Erkit', synopsis: null),
  (title: 'Esomia', synopsis: null),
  (title: 'Estrade', synopsis: null),
  (title: 'Eternis', synopsis: null),
  (title: 'Etheria', synopsis: null),
  (title: 'Ethichi', synopsis: null),
  (title: 'Etion', synopsis: null),
  (title: 'Eturn', synopsis: null),
  (title: 'Euphoria', synopsis: null),
  (title: 'Exilon', synopsis: null),
  (title: 'Exilon Astrae', synopsis: null),
  (title: 'Exousia', synopsis: null),
  (title: 'Eziastea', synopsis: null),
  (title: 'Fazanama', synopsis: null),
  (title: 'Felsen', synopsis: null),
  (title: 'Fumus', synopsis: null),
  (title: 'Gachuilia', synopsis: null),
  (title: 'Gaia', synopsis: null),
  (title: 'Galactra', synopsis: null),
  (title: 'Galactra Reach', synopsis: null),
  (title: 'Galatea', synopsis: null),
  (title: 'Galor', synopsis: null),
  (title: 'Gamadon', synopsis: null),
  (title: 'Garilia', synopsis: null),
  (title: 'Garvis', synopsis: null),
  (title: 'Gatheron', synopsis: null),
  (title: 'Gathiolea', synopsis: null),
  (title: 'Gebippe', synopsis: null),
  (title: 'Gelida', synopsis: null),
  (title: 'Geonosis', synopsis: null),
  (title: 'Gephahines', synopsis: null),
  (title: 'Geron', synopsis: null),
  (title: 'Gevora', synopsis: null),
  (title: 'Gezephus', synopsis: null),
  (title: 'Giggadon', synopsis: null),
  (title: 'Gildor', synopsis: null),
  (title: 'Gilea', synopsis: null),
  (title: 'Gnao', synopsis: null),
  (title: 'Gnichinope', synopsis: null),
  (title: 'Gnilia', synopsis: null),
  (title: 'Gnosie', synopsis: null),
  (title: 'Gnulmoturn', synopsis: null),
  (title: 'Gnurn', synopsis: null),
  (title: 'Gnyke', synopsis: null),
  (title: 'Gohihines', synopsis: null),
  (title: 'Gosie', synopsis: null),
  (title: 'Gragua', synopsis: null),
  (title: 'Griri', synopsis: null),
  (title: 'Grosehiri', synopsis: null),
  (title: 'Gruyiter', synopsis: null),
  (title: 'Gurn', synopsis: null),
  (title: 'Hagel', synopsis: null),
  (title: 'Hamazar', synopsis: null),
  (title: 'Hegantu', synopsis: null),
  (title: 'Helionis', synopsis: null),
  (title: 'Helix', synopsis: null),
  (title: 'Hion', synopsis: null),
  (title: 'Hiptaron', synopsis: null),
  (title: 'Horizon', synopsis: null),
  (title: 'Horizon Solis', synopsis: null),
  (title: 'Hosnian', synopsis: null),
  (title: 'Hoth', synopsis: null),
  (title: 'Hubborth', synopsis: null),
  (title: 'Hydraxis', synopsis: null),
  (title: 'Hydria', synopsis: null),
  (title: 'Hydronis', synopsis: null),
  (title: 'Hydronis Aquatica', synopsis: null),
  (title: 'Hydronis Reach', synopsis: null),
  (title: 'Hydrora', synopsis: null),
  (title: 'Hydros', synopsis: null),
  (title: 'Ia', synopsis: null),
  (title: 'Ibbongo', synopsis: null),
  (title: 'Ibreon', synopsis: null),
  (title: 'Icarus', synopsis: null),
  (title: 'Ignis', synopsis: null),
  (title: 'Igolla', synopsis: null),
  (title: 'Ikadus', synopsis: null),
  (title: 'Iketer', synopsis: null),
  (title: 'Illizar', synopsis: null),
  (title: 'Imperium', synopsis: null),
  (title: 'Inorth', synopsis: null),
  (title: 'Insomnes', synopsis: null),
  (title: 'Ipharth', synopsis: null),
  (title: 'Iphuatov', synopsis: null),
  (title: 'Iroria', synopsis: null),
  (title: 'Itania', synopsis: null),
  (title: 'Iutov', synopsis: null),
  (title: 'Ivion', synopsis: null),
  (title: 'Ixippe', synopsis: null),
  (title: 'Izeon', synopsis: null),
  (title: 'Jakku', synopsis: null),
  (title: 'Janus', synopsis: null),
  (title: 'Jillamar', synopsis: null),
  (title: 'Jiplamar', synopsis: null),
  (title: 'Jutrar', synopsis: null),
  (title: 'Kallamatar', synopsis: null),
  (title: 'Kedurn', synopsis: null),
  (title: 'Kef', synopsis: null),
  (title: 'Kegawa', synopsis: null),
  (title: 'Kemazar', synopsis: null),
  (title: 'Keria', synopsis: null),
  (title: 'Kessel', synopsis: null),
  (title: 'Ketera', synopsis: null),
  (title: 'Kietera', synopsis: null),
  (title: 'Kilia', synopsis: null),
  (title: 'Krios', synopsis: null),
  (title: 'Kumia', synopsis: null),
  (title: 'Kuphuegantu', synopsis: null),
  (title: 'Kuriuq', synopsis: null),
  (title: 'Kustruna', synopsis: null),
  (title: 'Kutmoria', synopsis: null),
  (title: 'Ladenia', synopsis: null),
  (title: 'Laetania', synopsis: null),
  (title: 'Lakas', synopsis: null),
  (title: 'Lecarro', synopsis: null),
  (title: 'Lenia', synopsis: null),
  (title: 'Leos', synopsis: null),
  (title: 'Leron', synopsis: null),
  (title: 'Lianrorix', synopsis: null),
  (title: 'Lis', synopsis: null),
  (title: 'Llanocury', synopsis: null),
  (title: 'Llia', synopsis: null),
  (title: 'Llizicarro', synopsis: null),
  (title: 'Llore', synopsis: null),
  (title: 'Lonadus', synopsis: null),
  (title: 'Lorth', synopsis: null),
  (title: 'Lothal', synopsis: null),
  (title: 'Lotho', synopsis: null),
  (title: 'Lougantu', synopsis: null),
  (title: 'Lreus Zeta', synopsis: null),
  (title: 'Lua', synopsis: null),
  (title: 'Lua Reach', synopsis: null),
  (title: 'Lukaria', synopsis: null),
  (title: 'Lumina', synopsis: null),
  (title: 'Luminae', synopsis: null),
  (title: 'Luminae Glade', synopsis: null),
  (title: 'Luminae Vale', synopsis: null),
  (title: 'Luminae Veil', synopsis: null),
  (title: 'Luminara', synopsis: null),
  (title: 'Luminary', synopsis: null),
  (title: 'Luminary Lumina', synopsis: null),
  (title: 'Luminastra', synopsis: null),
  (title: 'Luminex', synopsis: null),
  (title: 'Lumynaris', synopsis: null),
  (title: 'Lumynis', synopsis: null),
  (title: 'Lumynis Veil', synopsis: null),
  (title: 'Lumynyx', synopsis: null),
  (title: 'Lumynyx Veil', synopsis: null),
  (title: 'Luna', synopsis: null),
  (title: 'Lunara', synopsis: null),
  (title: 'Lunarae', synopsis: null),
  (title: 'Lunaria', synopsis: null),
  (title: 'Lunaria Astrum', synopsis: null),
  (title: 'Lunariax', synopsis: null),
  (title: 'Lunaris', synopsis: null),
  (title: 'Lunaris Celestis', synopsis: null),
  (title: 'Lunaris Noctis', synopsis: null),
  (title: 'Lunaris Vale', synopsis: null),
  (title: 'Lunaris Veil', synopsis: null),
  (title: 'Lunaxis', synopsis: null),
  (title: 'Lunos', synopsis: null),
  (title: 'Lurn', synopsis: null),
  (title: 'Luzars', synopsis: null),
  (title: 'Lyke', synopsis: null),
  (title: 'Lyra', synopsis: null),
  (title: 'Lyra Celestialis', synopsis: null),
  (title: 'Lyra Vortex', synopsis: null),
  (title: 'Lyrius', synopsis: null),
  (title: 'Lyrius Harmony', synopsis: null),
  (title: 'Lyrius Nebula', synopsis: null),
  (title: 'Maahines', synopsis: null),
  (title: 'Magua', synopsis: null),
  (title: 'Malkor', synopsis: null),
  (title: 'Mandalore', synopsis: null),
  (title: 'Manolla', synopsis: null),
  (title: 'Maridian', synopsis: null),
  (title: 'Maridian Aquaria', synopsis: null),
  (title: 'Maridian Echo', synopsis: null),
  (title: 'Maridian Reach', synopsis: null),
  (title: 'Massiccio', synopsis: null),
  (title: 'Mavros', synopsis: null),
  (title: 'Megazol', synopsis: null),
  (title: 'Mellirus', synopsis: null),
  (title: 'Menviria', synopsis: null),
  (title: 'Meridia', synopsis: null),
  (title: 'Meridian', synopsis: null),
  (title: 'Merth', synopsis: null),
  (title: 'Meruta', synopsis: null),
  (title: 'Mestryke', synopsis: null),
  (title: 'Mezoria', synopsis: null),
  (title: 'Mibboamia', synopsis: null),
  (title: 'Micovis', synopsis: null),
  (title: 'Micriea', synopsis: null),
  (title: 'Mieliv', synopsis: null),
  (title: 'Miuq', synopsis: null),
  (title: 'Mogrion', synopsis: null),
  (title: 'Mon Cala', synopsis: null),
  (title: 'Muhimia', synopsis: null),
  (title: 'Muunus', synopsis: null),
  (title: 'Mya', synopsis: null),
  (title: 'Myriad', synopsis: null),
  (title: 'Myriad Nebula', synopsis: null),
  (title: 'Mythos', synopsis: null),
  (title: 'Naboo', synopsis: null),
  (title: 'Nagua', synopsis: null),
  (title: 'Nalarth', synopsis: null),
  (title: 'Nalvurn', synopsis: null),
  (title: 'Naphalia', synopsis: null),
  (title: 'Nara', synopsis: null),
  (title: 'Naxramma', synopsis: null),
  (title: 'Nazyria', synopsis: null),
  (title: 'Nebula', synopsis: null),
  (title: 'Nebula Enigma', synopsis: null),
  (title: 'Nebulara', synopsis: null),
  (title: 'Nebulara Celestial', synopsis: null),
  (title: 'Nebularis', synopsis: null),
  (title: 'Nebularis Enclave', synopsis: null),
  (title: 'Nebularis Enigma', synopsis: null),
  (title: 'Nebulith', synopsis: null),
  (title: 'Nebulon', synopsis: null),
  (title: 'Nebulon Nebula', synopsis: null),
  (title: 'Nebulon Reach', synopsis: null),
  (title: 'Nebulonix', synopsis: null),
  (title: 'Nebulora', synopsis: null),
  (title: 'Nebulora Glade', synopsis: null),
  (title: 'Nebulora Nebula', synopsis: null),
  (title: 'Nebulore', synopsis: null),
  (title: 'Nebuloria', synopsis: null),
  (title: 'Nebuloria Enigma', synopsis: null),
  (title: 'Nebuloria Vortex', synopsis: null),
  (title: 'Nebuloris', synopsis: null),
  (title: 'Nebulus', synopsis: null),
  (title: 'Nebulus Zeta', synopsis: null),
  (title: 'Nelore', synopsis: null),
  (title: 'Nenviuwei', synopsis: null),
  (title: 'Neotera', synopsis: null),
  (title: 'Neoterra', synopsis: null),
  (title: 'Nesippe', synopsis: null),
  (title: 'Nesyke', synopsis: null),
  (title: 'Nettoyer', synopsis: null),
  (title: 'Newer', synopsis: null),
  (title: 'Nibiru', synopsis: null),
  (title: 'Night', synopsis: null),
  (title: 'Nionazar', synopsis: null),
  (title: 'Nippe', synopsis: null),
  (title: 'Nirvana', synopsis: null),
  (title: 'Niuq', synopsis: null),
  (title: 'Nixamar', synopsis: null),
  (title: 'Nocturna', synopsis: null),
  (title: 'Nocturnara', synopsis: null),
  (title: 'Nocturnia', synopsis: null),
  (title: 'Nocturnis', synopsis: null),
  (title: 'Nocturnis Dark', synopsis: null),
  (title: 'Nocturnis Umbra', synopsis: null),
  (title: 'Nogater', synopsis: null),
  (title: 'Norix', synopsis: null),
  (title: 'Noth', synopsis: null),
  (title: 'Numidian', synopsis: null),
  (title: 'Nupra', synopsis: null),
  (title: 'Nyria', synopsis: null),
  (title: 'Nyx', synopsis: null),
  (title: 'Obragh', synopsis: null),
  (title: 'Obsidian', synopsis: null),
  (title: 'Obsydria', synopsis: null),
  (title: 'Oceania', synopsis: null),
  (title: 'Oceano', synopsis: null),
  (title: 'Ogantu', synopsis: null),
  (title: 'Ogore', synopsis: null),
  (title: 'Olillon', synopsis: null),
  (title: 'Oliv', synopsis: null),
  (title: 'Olorix', synopsis: null),
  (title: 'Ondion', synopsis: null),
  (title: 'Oniea', synopsis: null),
  (title: 'Ophelia', synopsis: null),
  (title: 'Oranis', synopsis: null),
  (title: 'Oranis Reach', synopsis: null),
  (title: 'Orionis', synopsis: null),
  (title: 'Orpheus', synopsis: null),
  (title: 'Ouphus', synopsis: null),
  (title: 'Ozuno', synopsis: null),
  (title: 'Pacifica', synopsis: null),
  (title: 'Pararaiha', synopsis: null),
  (title: 'Phantos', synopsis: null),
  (title: 'Phars', synopsis: null),
  (title: 'Pherth', synopsis: null),
  (title: 'Philia', synopsis: null),
  (title: 'Pisces', synopsis: null),
  (title: 'Polveshan', synopsis: null),
  (title: 'Portum', synopsis: null),
  (title: 'Prismis', synopsis: null),
  (title: 'Prismis Radiance', synopsis: null),
  (title: 'Prismora', synopsis: null),
  (title: 'Prismora Radiant', synopsis: null),
  (title: 'Proxima', synopsis: null),
  (title: 'Punus', synopsis: null),
  (title: 'Purilia', synopsis: null),
  (title: 'Pyralia', synopsis: null),
  (title: 'Pyralion', synopsis: null),
  (title: 'Pyralis', synopsis: null),
  (title: 'Pyralis Glade', synopsis: null),
  (title: 'Pyralis Vale', synopsis: null),
  (title: 'Pyraxis', synopsis: null),
  (title: 'Pyraxis Flameheart', synopsis: null),
  (title: 'Pyrion', synopsis: null),
  (title: 'Pyrion Vale', synopsis: null),
  (title: 'Pyronis', synopsis: null),
  (title: 'Pyronis Astra', synopsis: null),
  (title: 'Pyronis Inferno', synopsis: null),
  (title: 'Pyronyx', synopsis: null),
  (title: 'Pyroth', synopsis: null),
  (title: 'Pyroth Firestorm', synopsis: null),
  (title: 'Pyrothia', synopsis: null),
  (title: 'Pyrothian', synopsis: null),
  (title: 'Pyrothium', synopsis: null),
  (title: 'Pyrothos', synopsis: null),
  (title: 'Pyrovel', synopsis: null),
  (title: 'Pyroxis', synopsis: null),
  (title: 'Pyrrhia', synopsis: null),
  (title: 'Pyrrhus', synopsis: null),
  (title: 'Quasar', synopsis: null),
  (title: 'Quasar Stellarum', synopsis: null),
  (title: 'Quetzalia', synopsis: null),
  (title: 'Quinox', synopsis: null),
  (title: 'Quinox Equinox', synopsis: null),
  (title: 'Ra', synopsis: null),
  (title: 'Radiance', synopsis: null),
  (title: 'Radiant Terra', synopsis: null),
  (title: 'Radium', synopsis: null),
  (title: 'Raplamar', synopsis: null),
  (title: 'Rarohenga', synopsis: null),
  (title: 'Recentibus', synopsis: null),
  (title: 'Remus', synopsis: null),
  (title: 'Reruta', synopsis: null),
  (title: 'Retreron', synopsis: null),
  (title: 'Ria', synopsis: null),
  (title: 'Riagantu', synopsis: null),
  (title: 'Ridoria', synopsis: null),
  (title: 'Rigel', synopsis: null),
  (title: 'Rion', synopsis: null),
  (title: 'Rippundor', synopsis: null),
  (title: 'Ris', synopsis: null),
  (title: 'Ris Solaris', synopsis: null),
  (title: 'Risa', synopsis: null),
  (title: 'Risastor', synopsis: null),
  (title: 'Rismuzar', synopsis: null),
  (title: 'Ruccanides', synopsis: null),
  (title: 'Rulveobos', synopsis: null),
  (title: 'Rulveobos Theta', synopsis: null),
  (title: 'Ruveutera', synopsis: null),
  (title: 'Sablex', synopsis: null),
  (title: 'Sade', synopsis: null),
  (title: 'Sallavor', synopsis: null),
  (title: 'Samia', synopsis: null),
  (title: 'Sanilia', synopsis: null),
  (title: 'Sario', synopsis: null),
  (title: 'Sars', synopsis: null),
  (title: 'Secriowei', synopsis: null),
  (title: 'Seladon', synopsis: null),
  (title: 'Selene', synopsis: null),
  (title: 'Septario', synopsis: null),
  (title: 'Septerion', synopsis: null),
  (title: 'Seraphis', synopsis: null),
  (title: 'Sere', synopsis: null),
  (title: 'Serene', synopsis: null),
  (title: 'Serenith', synopsis: null),
  (title: 'Serenity', synopsis: null),
  (title: 'Sexurus', synopsis: null),
  (title: 'Sigrater', synopsis: null),
  (title: 'Silles', synopsis: null),
  (title: 'Sirocco', synopsis: null),
  (title: 'Soalea', synopsis: null),
  (title: 'Sola', synopsis: null),
  (title: 'Solara', synopsis: null),
  (title: 'Solara Dusk', synopsis: null),
  (title: 'Solara Luminara', synopsis: null),
  (title: 'Solara Veil', synopsis: null),
  (title: 'Solara Vista', synopsis: null),
  (title: 'Solarae', synopsis: null),
  (title: 'Solarae Aurelia', synopsis: null),
  (title: 'Solarae Oasis', synopsis: null),
  (title: 'Solaria', synopsis: null),
  (title: 'Solarion', synopsis: null),
  (title: 'Solaris', synopsis: null),
  (title: 'Solarius', synopsis: null),
  (title: 'Solera', synopsis: null),
  (title: 'Solis', synopsis: null),
  (title: 'Solisoria', synopsis: null),
  (title: 'Solla', synopsis: null),
  (title: 'Solstice', synopsis: null),
  (title: 'Solstice Orchid', synopsis: null),
  (title: 'Solstice Reach', synopsis: null),
  (title: 'Solsticea', synopsis: null),
  (title: 'Solsticea Solis', synopsis: null),
  (title: 'Solterra', synopsis: null),
  (title: 'Soluna', synopsis: null),
  (title: 'Soluna Lunara', synopsis: null),
  (title: 'Solunara', synopsis: null),
  (title: 'Solunis', synopsis: null),
  (title: 'Solunis Solaris', synopsis: null),
  (title: 'Solvenia', synopsis: null),
  (title: 'Solvenis', synopsis: null),
  (title: 'Solvenis Crystallis', synopsis: null),
  (title: 'Solvenis Vale', synopsis: null),
  (title: 'Solventis', synopsis: null),
  (title: 'Solvenya', synopsis: null),
  (title: 'Solvenyx', synopsis: null),
  (title: 'Solvian Reach', synopsis: null),
  (title: 'Solvira', synopsis: null),
  (title: 'Solvius', synopsis: null),
  (title: 'Solvius Solaris', synopsis: null),
  (title: 'Solvoria', synopsis: null),
  (title: 'Solvoria Vale', synopsis: null),
  (title: 'Solynis', synopsis: null),
  (title: 'Somia', synopsis: null),
  (title: 'Soxupra', synopsis: null),
  (title: 'Spectra', synopsis: null),
  (title: 'Stellar', synopsis: null),
  (title: 'Stellara', synopsis: null),
  (title: 'Stellara Glade', synopsis: null),
  (title: 'Stellara Light', synopsis: null),
  (title: 'Stellaria', synopsis: null),
  (title: 'Stellaris', synopsis: null),
  (title: 'Stellaris Astralis', synopsis: null),
  (title: 'Stellaris Ignis', synopsis: null),
  (title: 'Stellarium', synopsis: null),
  (title: 'Stellaron', synopsis: null),
  (title: 'Stellora', synopsis: null),
  (title: 'Stellora Glade', synopsis: null),
  (title: 'Stelloria', synopsis: null),
  (title: 'Stelloria Glade', synopsis: null),
  (title: 'Stra', synopsis: null),
  (title: 'Strachenov', synopsis: null),
  (title: 'Strade', synopsis: null),
  (title: 'Stralis', synopsis: null),
  (title: 'Straputis', synopsis: null),
  (title: 'Straxirus', synopsis: null),
  (title: 'Strematis', synopsis: null),
  (title: 'Strivinerth', synopsis: null),
  (title: 'Strorth', synopsis: null),
  (title: 'Sucury', synopsis: null),
  (title: 'Sufocar', synopsis: null),
  (title: 'Sukurn', synopsis: null),
  (title: 'Suna', synopsis: null),
  (title: 'Sylvana', synopsis: null),
  (title: 'Sylvanus', synopsis: null),
  (title: 'Sylvaria', synopsis: null),
  (title: 'Sylvaria Seraph', synopsis: null),
  (title: 'Sylvaris', synopsis: null),
  (title: 'Sylvaris Glade', synopsis: null),
  (title: 'Sylvaris Sylvan', synopsis: null),
  (title: 'Sythra', synopsis: null),
  (title: 'Tahiri', synopsis: null),
  (title: 'Tara', synopsis: null),
  (title: 'Tartu', synopsis: null),
  (title: 'Tater', synopsis: null),
  (title: 'Tatooine', synopsis: null),
  (title: 'Tau Ceti', synopsis: null),
  (title: 'Taurus', synopsis: null),
  (title: 'Taxore', synopsis: null),
  (title: 'Tearmann', synopsis: null),
  (title: 'Tempador', synopsis: null),
  (title: 'Terra', synopsis: null),
  (title: 'Terra Solis', synopsis: null),
  (title: 'Thagua', synopsis: null),
  (title: 'Thazuruta', synopsis: null),
  (title: 'Thelea', synopsis: null),
  (title: 'Theon', synopsis: null),
  (title: 'Thiirus', synopsis: null),
  (title: 'Thimion', synopsis: null),
  (title: 'Thisuvis', synopsis: null),
  (title: 'Thocosie', synopsis: null),
  (title: 'Thomilia', synopsis: null),
  (title: 'Thora', synopsis: null),
  (title: 'Thostrorth', synopsis: null),
  (title: 'Thuinides', synopsis: null),
  (title: 'Thulnyke', synopsis: null),
  (title: 'Titanis', synopsis: null),
  (title: 'To', synopsis: null),
  (title: 'Tolatune', synopsis: null),
  (title: 'Toxico', synopsis: null),
  (title: 'Trilia', synopsis: null),
  (title: 'Trilles', synopsis: null),
  (title: 'Tryke', synopsis: null),
  (title: 'Tubbethea', synopsis: null),
  (title: 'Tulia', synopsis: null),
  (title: 'Tutania', synopsis: null),
  (title: 'Tuumomo', synopsis: null),
  (title: 'Tyrian', synopsis: null),
  (title: 'Uater', synopsis: null),
  (title: 'Ucarro', synopsis: null),
  (title: 'Uchilles', synopsis: null),
  (title: 'Uchuna', synopsis: null),
  (title: 'Udarvis', synopsis: null),
  (title: 'Udone', synopsis: null),
  (title: 'Ugnonerth', synopsis: null),
  (title: 'Ulamaza', synopsis: null),
  (title: 'Ultavor', synopsis: null),
  (title: 'Umbria', synopsis: null),
  (title: 'Umonoe', synopsis: null),
  (title: 'Unairuta', synopsis: null),
  (title: 'Uptoria', synopsis: null),
  (title: 'Uruta', synopsis: null),
  (title: 'Uter', synopsis: null),
  (title: 'Valara', synopsis: null),
  (title: 'Valdron', synopsis: null),
  (title: 'Valoria', synopsis: null),
  (title: 'Vandor', synopsis: null),
  (title: 'Vanduthea', synopsis: null),
  (title: 'Vega', synopsis: null),
  (title: 'Vekao', synopsis: null),
  (title: 'Vemiuq', synopsis: null),
  (title: 'Verdania', synopsis: null),
  (title: 'Verdania Verdora', synopsis: null),
  (title: 'Verdant Oasis', synopsis: null),
  (title: 'Verdantara', synopsis: null),
  (title: 'Verdanthos', synopsis: null),
  (title: 'Verdantia', synopsis: null),
  (title: 'Verdantis', synopsis: null),
  (title: 'Verdantis Glade', synopsis: null),
  (title: 'Verdantis Vale', synopsis: null),
  (title: 'Verdantium', synopsis: null),
  (title: 'Verdantora', synopsis: null),
  (title: 'Verdantoria', synopsis: null),
  (title: 'Verdantus', synopsis: null),
  (title: 'Verdantus Glade', synopsis: null),
  (title: 'Verdantus Vale', synopsis: null),
  (title: 'Verdantus Wilds', synopsis: null),
  (title: 'Verdara', synopsis: null),
  (title: 'Verdora', synopsis: null),
  (title: 'Veridia', synopsis: null),
  (title: 'Veridian', synopsis: null),
  (title: 'Veridian Elysium', synopsis: null),
  (title: 'Veridian Sylvanis', synopsis: null),
  (title: 'Veridora', synopsis: null),
  (title: 'Veridora Glade', synopsis: null),
  (title: 'Veridora Oasis', synopsis: null),
  (title: 'Veritas', synopsis: null),
  (title: 'Vespera', synopsis: null),
  (title: 'Vespera Dusk', synopsis: null),
  (title: 'Vespera Vale', synopsis: null),
  (title: 'Vesperia', synopsis: null),
  (title: 'Vesperium', synopsis: null),
  (title: 'Veunia', synopsis: null),
  (title: 'Victoria', synopsis: null),
  (title: 'Vides', synopsis: null),
  (title: 'Viditera', synopsis: null),
  (title: 'Virgo', synopsis: null),
  (title: 'Vitalis', synopsis: null),
  (title: 'Volantis', synopsis: null),
  (title: 'Vortalis', synopsis: null),
  (title: 'Vortexia', synopsis: null),
  (title: 'Vorth', synopsis: null),
  (title: 'Vubecarro', synopsis: null),
  (title: 'Vulcan', synopsis: null),
  (title: 'Vunzulea', synopsis: null),
  (title: 'Vuruta', synopsis: null),
  (title: 'Vyke', synopsis: null),
  (title: 'Wolf', synopsis: null),
  (title: 'Xanthis', synopsis: null),
  (title: 'Xanthis Reach', synopsis: null),
  (title: 'Xelarvis', synopsis: null),
  (title: 'Xenaris', synopsis: null),
  (title: 'Xileon', synopsis: null),
  (title: 'Xiliv', synopsis: null),
  (title: 'Xirilia', synopsis: null),
  (title: 'Xis', synopsis: null),
  (title: 'Xochilia', synopsis: null),
  (title: 'Xore', synopsis: null),
  (title: 'Xovunides', synopsis: null),
  (title: 'Xunruawei', synopsis: null),
  (title: 'Xuter', synopsis: null),
  (title: 'Yastrotov', synopsis: null),
  (title: 'Yavin', synopsis: null),
  (title: 'Yemustea', synopsis: null),
  (title: 'Yetania', synopsis: null),
  (title: 'Yocowei', synopsis: null),
  (title: 'Yubizuno', synopsis: null),
  (title: 'Yulveron', synopsis: null),
  (title: 'Zaclite', synopsis: null),
  (title: 'Zao', synopsis: null),
  (title: 'Zaphus', synopsis: null),
  (title: 'Zeffo', synopsis: null),
  (title: 'Zeldara', synopsis: null),
  (title: 'Zendar', synopsis: null),
  (title: 'Zendaria', synopsis: null),
  (title: 'Zenithia', synopsis: null),
  (title: 'Zephyr', synopsis: null),
  (title: 'Zephyra Skyward', synopsis: null),
  (title: 'Zephyrae', synopsis: null),
  (title: 'Zephyraine', synopsis: null),
  (title: 'Zephyraine Reach', synopsis: null),
  (title: 'Zephyrara', synopsis: null),
  (title: 'Zephyraris', synopsis: null),
  (title: 'Zephyraris Vale', synopsis: null),
  (title: 'Zephyrath', synopsis: null),
  (title: 'Zephyria', synopsis: null),
  (title: 'Zephyria Magna', synopsis: null),
  (title: 'Zephyria Oasis', synopsis: null),
  (title: 'Zephyriae', synopsis: null),
  (title: 'Zephyrion', synopsis: null),
  (title: 'Zephyrion Zephyrus', synopsis: null),
  (title: 'Zephyrith', synopsis: null),
  (title: 'Zephyrium', synopsis: null),
  (title: 'Zephyrium Zephyrion', synopsis: null),
  (title: 'Zephyron', synopsis: null),
  (title: 'Zephyrora', synopsis: null),
  (title: 'Zephyros', synopsis: null),
  (title: 'Zephyrosa', synopsis: null),
  (title: 'Zephyrus', synopsis: null),
  (title: 'Zerith', synopsis: null),
  (title: 'Zetune', synopsis: null),
  (title: 'Zexade', synopsis: null),
  (title: 'Zimater', synopsis: null),
  (title: 'Ziopagawa', synopsis: null),
  (title: 'Zirconia', synopsis: null),
  (title: 'Zirconis', synopsis: null),
  (title: 'Zirconis Twilight', synopsis: null),
  (title: 'Ziwei', synopsis: null),
  (title: 'Zocenus', synopsis: null),
  (title: 'Zoclite', synopsis: null),
  (title: 'Zonoe', synopsis: null),
  (title: 'Zunricarro', synopsis: null),
  (title: 'Zuthara', synopsis: null),
  (title: 'Zypheria', synopsis: null),
  (title: 'Zypheris', synopsis: null),
  (title: 'Zypheris Zypher', synopsis: null),
  (title: 'Zypherium', synopsis: null),
  (title: 'Zypheron', synopsis: null),
  (title: 'Zypheron Zephyrus', synopsis: null),
  (title: 'Zypheron Zypher', synopsis: null),
  (title: 'Zyphira', synopsis: null),
  (title: 'Zyphira Zephyra', synopsis: null),
  (title: 'Zyphora', synopsis: null),
  (title: 'Zyphora Equinox', synopsis: null),
  (title: 'Zyphora Lumina', synopsis: null),
  (title: 'Zyphoria', synopsis: null),
  (title: 'Zyphoriax', synopsis: null),
  (title: 'Zyphorion', synopsis: null),
  (title: 'Zyphorius', synopsis: null),
  (title: 'Zyphos', synopsis: null),
  (title: 'Zypso', synopsis: null),
};
